# Generated by Django 6.0.5 on 2026-05-29 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_streak_freeze_limit_user_streak_freezes_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
