import json
import os

vocab_path = "src/data/exports/daily_life/haircut/daily_life_haircut_vocabulary.json"

with open(vocab_path, "r", encoding="utf-8") as f:
    vocab = json.load(f)

translations = {
    "alla": "to the / at the",
    "amici": "friends",
    "amico": "friend",
    "aperti": "open",
    "avrà": "will have",
    "avrò": "I will have",
    "balsamo": "conditioner",
    "banca": "bank",
    "basette": "sideburns",
    "bellissimo": "beautiful / great",
    "biglietto": "card / ticket",
    "bravo": "good / skilled",
    "camminando": "walking",
    "capisco": "I understand",
    "cassa": "cash desk / counter",
    "certo": "sure / certainly",
    "comprare": "to buy",
    "conosco": "I know",
    "consiglio": "advice / recommendation",
    "corte": "short",
    "costa": "costs",
    "dal": "from the",
    "dalle": "from the (time)",
    "davvero": "really",
    "dei": "of the",
    "del": "of the",
    "della": "of the",
    "diretto": "direct",
    "dirò": "I will say",
    "dopo": "after",
    "due": "two",
    "effetto": "effect",
    "email": "email",
    "esperto": "expert",
    "fedeltà": "loyalty",
    "fido": "I trust",
    "folti": "thick",
    "frangia": "fringe / bangs",
    "funziona": "works",
    "giorni": "days",
    "giorno": "day",
    "già": "already",
    "iniziamo": "we start",
    "insegna": "sign",
    "interessante": "interesting",
    "iscriversi": "to sign up",
    "lasciamo": "we leave",
    "letto": "read",
    "look": "look / appearance",
    "lunedì": "Monday",
    "lunga": "long",
    "lunghe": "long",
    "manda": "sends",
    "mando": "I send",
    "meglio": "better",
    "messaggio": "message",
    "metto": "I put",
    "miei": "my",
    "morbidi": "soft",
    "nel": "in the",
    "nessuno": "nobody / any",
    "neutro": "neutral",
    "newsletter": "newsletter",
    "nostra": "our",
    "nostro": "our",
    "nove": "nine",
    "numero": "number",
    "nuovo": "new",
    "ogni": "every",
    "omaggio": "free gift / complimentary",
    "online": "online",
    "ottime": "excellent",
    "ottimo": "excellent",
    "otto": "eight",
    "particolare": "particular",
    "particolari": "particular",
    "perfettamente": "perfectly",
    "porta": "brings / door",
    "portafoglio": "wallet",
    "prego": "you're welcome / please",
    "prendo": "I take",
    "presto": "soon",
    "problemi": "problems",
    "prodotti": "products",
    "promemoria": "reminder",
    "pronto": "ready",
    "prossima": "next",
    "proverò": "I will try",
    "questa": "this",
    "questo": "this",
    "recensioni": "reviews",
    "renderli": "to make them",
    "ricevo": "I receive",
    "ricordi": "remember",
    "rilassi": "relax",
    "rivederla": "to see you again",
    "roma": "Rome",
    "sabato": "Saturday",
    "sarà": "will be",
    "scelta": "choice",
    "sconto": "discount",
    "seguo": "I follow",
    "sento": "I feel / I hear",
    "sfumate": "faded",
    "siamo": "we are",
    "sicuramente": "definitely",
    "speciale": "special",
    "stasera": "tonight",
    "strada": "street",
    "subito": "immediately",
    "telefono": "phone",
    "tessera": "card",
    "troppe": "too many",
    "trovarvi": "to find you",
    "trovati": "found",
    "undicesimo": "eleventh",
    "uno": "one",
    "usa": "uses / use",
    "usato": "used",
    "va": "goes",
    "vado": "I go",
    "vedo": "I see",
    "venga": "come",
    "venticinque": "twenty-five",
    "veramente": "really",
    "verrò": "I will come",
    "verso": "towards",
    "via": "via / street / away",
    "visita": "visit",
    "visto": "seen",
    "voglio": "I want",
    "volevo": "I wanted",
    "volentieri": "gladly",
    "vostra": "your",
    "vostro": "your",
    "sopracciglia": "eyebrows",
    "vicino": "near",
    "volta": "time",
    "zona": "area"
}

updated_count = 0
for item in vocab:
    if item["english"] == "":
        it = item["italian"]
        if it in translations:
            item["english"] = translations[it]
            updated_count += 1
        else:
            print(f"Still missing: {it}")

with open(vocab_path, "w", encoding="utf-8") as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} translations.")
