import json
import os

translations = {
    "acqua": "water",
    "affretti": "hurry",
    "aiutarmi": "help me",
    "all": "at the",
    "alla": "at the",
    "allora": "then",
    "altri": "others",
    "arrivando": "arriving",
    "arrivare": "to arrive",
    "aspetti": "wait",
    "attento": "careful",
    "avviso": "notice",
    "bagaglio": "luggage",
    "bar": "bar",
    "borsa": "bag",
    "buona": "good",
    "carrello": "trolley",
    "carrozze": "carriages",
    "cercherò": "I will look for",
    "che": "that",
    "chiaramente": "clearly",
    "cinque": "five",
    "come": "how",
    "controllare": "to check",
    "controllo": "check",
    "convalidare": "to validate",
    "corridoio": "corridor",
    "così": "so",
    "della": "of the",
    "destinazione": "destination",
    "destra": "right",
    "dimentichi": "forget",
    "display": "display",
    "dovrebbe": "should",
    "due": "two",
    "dura": "lasts",
    "educato": "polite",
    "elettronico": "electronic",
    "entrando": "entering",
    "entro": "I enter",
    "faccia": "do/make",
    "facile": "easy",
    "farò": "I will do",
    "ferma": "stop",
    "fermata": "stop",
    "funziona": "works",
    "gentile": "kind",
    "giornata": "day",
    "giusta": "right",
    "giusto": "right",
    "gli": "the",
    "grandi": "big",
    "idea": "idea",
    "importante": "important",
    "informazione": "information",
    "inizio": "beginning",
    "lasciar": "to let",
    "lascio": "I leave",
    "leggere": "to read",
    "libero": "free",
    "libro": "book",
    "lontano": "far",
    "macchinette": "machines",
    "magari": "maybe",
    "manca": "is missing",
    "mancano": "are missing",
    "mano": "hand",
    "meglio": "better",
    "mettere": "to put",
    "mia": "my",
    "molte": "many",
    "necessario": "necessary",
    "nel": "in the",
    "nulla": "nothing",
    "numerate": "numbered",
    "numero": "number",
    "oggi": "today",
    "ore": "hours",
    "ottima": "great",
    "panchina": "bench",
    "partenza": "departure",
    "passare": "to pass",
    "passeggeri": "passengers",
    "perfette": "perfect",
    "permanenza": "stay",
    "più": "more",
    "poco": "little",
    "porta": "door",
    "portata": "reach",
    "prenderò": "I will take",
    "preso": "taken",
    "prima": "before",
    "prossima": "next",
    "quando": "when",
    "quanto": "how much",
    "questo": "this",
    "quindi": "so",
    "ricordi": "remember",
    "scendano": "get off",
    "scendere": "to get off",
    "sedili": "seats",
    "sete": "thirst",
    "solo": "only",
    "spazi": "spaces",
    "sta": "is",
    "starò": "I will be",
    "stato": "been",
    "stazione": "station",
    "sua": "her/his/your",
    "sulla": "on the",
    "tasca": "pocket",
    "tempo": "time",
    "tenerlo": "to keep it",
    "tenga": "keep",
    "terrò": "I will keep",
    "tra": "between/in",
    "usarle": "to use them",
    "valigia": "suitcase",
    "vedo": "I see"
}

file_path = 'src/data/exports/travel/train_platform/travel_train_platform_vocabulary.json'
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for entry in data:
    word = entry['italian'].lower().strip()
    if not entry.get('english') or entry['english'] == "":
        if word in translations:
            entry['english'] = translations[word]
        else:
            print(f"Still missing translation for: {word}")

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
