import json
import os

mapping = {
    "abbastanza": "quite / enough",
    "abbia": "has / have (subjunctive)",
    "abbiamo": "we have",
    "accaduto": "happened / occurrence",
    "accetto": "I accept",
    "accordo": "agreement / OK",
    "addebitarle": "to charge you",
    "aggiorniamo": "let's update / catch up",
    "ahaha": "ahaha",
    "aiutare": "to help",
    "aiutarla": "to help you (formal)",
    "alla": "to the / at the",
    "alle": "to the / at the",
    "allora": "then / well",
    "almeno": "at least",
    "altri": "others",
    "altro": "other / anything else",
    "amici": "friends",
    "amico": "friend",
    "anch": "also",
    "anche": "also",
    "ancora": "still / again",
    "andare": "to go",
    "appuntamento": "appointment",
    "arrabbiato": "angry",
    "arrabbierei": "would get angry",
    "arrivederci": "goodbye",
    "aspetta": "wait",
    "aspettando": "waiting",
    "aspettare": "to wait",
    "aspettato": "waited",
    "aspettiamo": "we wait / let's wait",
    "assolutamente": "absolutely",
    "attento": "careful",
    "attesa": "waiting / wait",
    "avevamo": "we had",
    "avevo": "I had",
    "avrebbe": "would have",
    "avrei": "I would have",
    "avuto": "had",
    "avvisi": "let us know / notices",
    "beh": "well",
    "bene": "well",
    "benissimo": "very well",
    "bianchi": "Bianchi (name) / white",
    "bicchiere": "glass",
    "bicchieri": "glasses",
    "bisogno": "need",
    "buon": "good",
    "buona": "good",
    "buongiorno": "good morning",
    "buoni": "good",
    "buono": "good",
    "buttare": "to throw (away)",
    "caffè": "coffee",
    "calma": "calm",
    "capisco": "I understand",
    "capita": "it happens",
    "cappuccino": "cappuccino",
    "caso": "case / chance",
    "cena": "dinner",
    "centro": "center / downtown",
    "certamente": "certainly",
    "che": "that / what",
    "chiacchierare": "to chat",
    "chiamato": "called",
    "chiedo": "I ask",
    "ciao": "hi / bye",
    "cin": "cheers",
    "cinema": "cinema / movies",
    "cognizione": "cognition / awareness",
    "col": "with the",
    "colpa": "fault / guilt",
    "come": "how / like",
    "compleanno": "birthday",
    "completamente": "completely",
    "comprensione": "understanding",
    "comprerò": "I will buy",
    "comunque": "anyway",
    "con": "with",
    "controllo": "check / I check",
    "cornetto": "croissant",
    "cos": "what",
    "cosa": "what / thing",
    "costo": "cost",
    "così": "so / like this",
    "crema": "cream",
    "cucina": "kitchen",
    "cuore": "heart",
    "dai": "come on",
    "davvero": "really",
    "del": "of the",
    "della": "of the",
    "dentistico": "dental",
    "devo": "I must",
    "dice": "says",
    "dieci": "ten",
    "dimenticato": "forgotten",
    "disastro": "disaster",
    "dispiace": "sorry (it displeases)",
    "disponibilità": "availability",
    "distratto": "distracted",
    "disturbo": "disturbance / bother",
    "dopo": "after",
    "dove": "where",
    "dovremo": "we will have to",
    "dovuto": "had to / due",
    "due": "two",
    "ecco": "here",
    "effetti": "effects / in fact",
    "ehi": "hey",
    "era": "was",
    "essere": "to be",
    "esserti": "being to you",
    "facciamo": "we do / let's do",
    "faccio": "I do",
    "fantastico": "fantastic",
    "fare": "to do",
    "farmi": "to make me",
    "farti": "to make you",
    "fatica": "effort / struggle",
    "fatto": "done / fact",
    "favore": "favor",
    "fermo": "still / stopped",
    "festa": "party",
    "festeggiare": "to celebrate",
    "figurati": "don't mention it",
    "finire": "to finish",
    "fissare": "to fix / to schedule",
    "fossimo": "we were (subjunctive)",
    "foto": "photo",
    "frattempo": "meantime",
    "genere": "kind / gender",
    "gentile": "kind",
    "giornata": "day",
    "giorno": "day",
    "giovedì": "Thursday",
    "girato": "turned / drove around",
    "giuro": "I swear",
    "gli": "the / to him",
    "godiamoci": "let's enjoy",
    "grandi": "big / large",
    "grazie": "thanks",
    "hai": "you have",
    "idea": "idea",
    "ieri": "yesterday",
    "immagino": "I imagine",
    "impegnato": "busy",
    "imprevisto": "unexpected event",
    "incidenti": "incidents / accidents",
    "incredibile": "incredible",
    "incubo": "nightmare",
    "infinita": "infinite",
    "insisto": "I insist",
    "lasciami": "let me",
    "lavoro": "work",
    "libero": "free",
    "magari": "maybe",
    "mai": "never",
    "male": "bad / badly",
    "manca": "is missing",
    "mandarti": "to send you",
    "mani": "hands",
    "mario": "Mario",
    "meglio": "better",
    "messaggino": "little message",
    "messaggio": "message",
    "metà": "half",
    "mille": "thousand",
    "minimo": "minimum / least",
    "minuti": "minutes",
    "mio": "my",
    "moltissimo": "very much",
    "molto": "very / much",
    "morire": "to die",
    "muovere": "to move",
    "nel": "in the",
    "nessun": "no / none",
    "nessuno": "no one / nobody",
    "niente": "nothing",
    "nome": "name",
    "non": "not",
    "nuovi": "new",
    "nuovo": "new",
    "oddio": "oh god",
    "offrendoti": "offering you",
    "offro": "I offer / my treat",
    "oggi": "today",
    "ora": "now / hour",
    "ordinare": "to order",
    "ormai": "by now",
    "ospite": "guest",
    "ottima": "excellent",
    "ottimo": "excellent",
    "otto": "eight",
    "paletta": "dustpan",
    "parcheggio": "parking",
    "passata": "passed",
    "pausa": "break",
    "pazienza": "patience",
    "pensavo": "I thought",
    "per": "for",
    "perdonare": "to forgive",
    "perdonarmi": "to forgive me",
    "perdonato": "forgiven",
    "perfettamente": "perfectly",
    "perfetto": "perfect",
    "perso": "lost",
    "però": "however",
    "pessimo": "terrible",
    "pezzi": "pieces",
    "piacere": "pleasure",
    "piacerebbe": "would like",
    "piacerà": "will like",
    "piccolo": "small",
    "piuttosto": "rather",
    "più": "more",
    "porterò": "I will bring",
    "possibile": "possible",
    "posso": "I can",
    "posto": "place / spot",
    "potresti": "you could",
    "prego": "you're welcome / please",
    "prendi": "you take / you have",
    "prendo": "I take / I have",
    "preoccupando": "worrying",
    "preoccupare": "to worry",
    "preoccupi": "you worry (formal) / don't worry",
    "presto": "soon",
    "prima": "before / first",
    "problema": "problem",
    "progetto": "project",
    "prometto": "I promise",
    "proprio": "really / own",
    "prossima": "next",
    "provare": "to try",
    "puntualissimo": "very punctual",
    "qualche": "some",
    "qualcosa": "something",
    "quando": "when",
    "quel": "that",
    "quest": "this",
    "questa": "this",
    "questo": "this",
    "qui": "here",
    "quindici": "fifteen",
    "ragione": "reason / right",
    "ragioni": "reasons / right",
    "regalo": "gift",
    "ricordarle": "to remind you (formal)",
    "rilassati": "relax",
    "rimasto": "remained / left",
    "ringrazio": "I thank",
    "ristorante": "restaurant",
    "ritardo": "delay / lateness",
    "rossi": "Rossi",
    "rotto": "broken",
    "rumore": "noise",
    "sabato": "Saturday",
    "sarebbe": "would be",
    "sarà": "will be",
    "sarò": "I will be",
    "sbaglio": "mistake",
    "scelta": "choice",
    "scopa": "broom",
    "scusa": "sorry / excuse",
    "scusami": "excuse me / sorry",
    "scuse": "apologies",
    "scusi": "excuse me (formal)",
    "segnata": "marked / noted",
    "sei": "you are / six",
    "sempre": "always",
    "sentiamoci": "let's talk / let's hear from each other",
    "sentito": "felt / heard",
    "sento": "I feel / I hear",
    "senza": "without",
    "sera": "evening",
    "serata": "evening",
    "serve": "is needed / serves",
    "servono": "are needed / serve",
    "set": "set",
    "settimana": "week",
    "siamo": "we are",
    "sicuramente": "surely / definitely",
    "signor": "Mr.",
    "simili": "similar",
    "sincero": "sincere / honest",
    "solito": "usual",
    "sollevato": "relieved",
    "solo": "only / alone",
    "sono": "I am / they are",
    "speciale": "special",
    "spero": "I hope",
    "spiritoso": "funny / witty",
    "stai": "you stay / you are",
    "stamattina": "this morning",
    "starò": "I will be",
    "stato": "been / state",
    "stavo": "I was",
    "sto": "I am",
    "stress": "stress",
    "stretti": "close / tight",
    "studio": "studio / office / I study",
    "successo": "happened / success",
    "suo": "his / her / your (formal)",
    "suona": "sounds / plays",
    "tagliarti": "to cut yourself",
    "tantissimi": "many / so many",
    "tantissimo": "very much",
    "tanto": "so much",
    "tempo": "time",
    "terra": "ground / floor",
    "terrò": "I will keep",
    "tra": "between / among / in (time)",
    "traffico": "traffic",
    "tranquillo": "calm / don't worry",
    "troppo": "too much",
    "trovare": "to find",
    "trovarlo": "to find it",
    "tua": "your",
    "tue": "your",
    "tuo": "your",
    "tutte": "all",
    "tutti": "everyone / all",
    "tutto": "everything / all",
    "ultimamente": "lately",
    "una": "a / one",
    "valida": "valid",
    "vediamo": "we see / let's see",
    "vedo": "I see",
    "venerdì": "Friday",
    "venire": "to come",
    "venti": "twenty / winds",
    "venuto": "come",
    "vero": "true / real",
    "vetri": "glass shards / glasses",
    "via": "away / street",
    "vicino": "near / neighbor",
    "vino": "wine",
    "visto": "seen",
    "vogliamo": "we want",
    "volentieri": "gladly",
    "volevi": "you wanted",
    "volevo": "I wanted",
    "volta": "time / once",
    "volte": "times",
    "vorresti": "you would like",
    "vuoi": "you want",
    "vuole": "he/she wants / you want (formal)",
    "weekend": "weekend",
    "zona": "area"
}

file_path = "src/data/exports/social/apologizing/social_apologizing_vocabulary.json"

with open(file_path, "r", encoding="utf-8") as f:
    vocab = json.load(f)

missing = []
for item in vocab:
    it = item["italian"].lower().strip("!?,.")
    if it in mapping:
        item["english"] = mapping[it]
    elif item["italian"] in mapping:
        item["english"] = mapping[item["italian"]]
    else:
        # Try without some common endings or handle cases
        missing.append(item["italian"])

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)

if missing:
    print(f"Missing translations for: {set(missing)}")
else:
    print("All translations filled!")
