import json

vocab_path = "src/data/exports/shopping/electronics_store/shopping_electronics_store_vocabulary.json"

translations = {
    "abbiamo": "we have",
    "aiutarla": "to help you",
    "allora": "then",
    "anche": "also",
    "anni": "years",
    "anno": "year",
    "batteria": "battery",
    "bene": "well",
    "borsa": "bag",
    "buon": "good",
    "buongiorno": "good morning",
    "caricabatterie": "charger",
    "cellulare": "cell phone",
    "cento": "hundred",
    "centoventi": "one hundred twenty",
    "cerca": "searches/looking for",
    "certo": "of course",
    "chiaro": "clear",
    "circa": "about",
    "comode": "comfortable",
    "comprare": "to buy",
    "compresa": "included",
    "compro": "I buy",
    "computer": "computer",
    "coperta": "covered",
    "cosa": "what",
    "costa": "costs",
    "costano": "they cost",
    "cuffie": "headphones",
    "delle": "some",
    "desidera": "would you like",
    "dieci": "ten",
    "due": "two",
    "dura": "lasts",
    "durano": "they last",
    "euro": "euro",
    "fantastico": "fantastic",
    "fili": "wires",
    "garanzia": "warranty",
    "gigabyte": "gigabyte",
    "grande": "big",
    "hanno": "they have",
    "importante": "important",
    "informazioni": "information",
    "iva": "VAT",
    "lavorare": "to work",
    "legge": "law",
    "leggero": "light",
    "lei": "you (formal)",
    "lunga": "long",
    "memoria": "memory",
    "metto": "I put",
    "modello": "model",
    "molto": "very",
    "musica": "music",
    "novecento": "nine hundred",
    "nuovo": "new",
    "obbligatori": "mandatory",
    "ore": "hours",
    "originale": "original",
    "ottima": "excellent (f)",
    "ottime": "excellent (f. pl)",
    "ottimo": "excellent (m)",
    "pensa": "thinks/think",
    "per": "for",
    "perfetta": "perfect (f)",
    "perfetto": "perfect (m)",
    "piacciono": "they like",
    "piace": "it likes/you like",
    "portatile": "portable/laptop",
    "porto": "I carry",
    "posso": "I can",
    "prendo": "I take",
    "prezzo": "price",
    "promozione": "promotion",
    "protezione": "protection",
    "provare": "to try",
    "queste": "these",
    "questo": "this",
    "rassicura": "reassures",
    "salve": "hello",
    "scegliere": "to choose",
    "scelta": "choice",
    "schermo": "screen",
    "scontrino": "receipt",
    "sedici": "sixteen",
    "seicento": "six hundred",
    "senza": "without",
    "serve": "it serves/is needed",
    "sicuro": "safe/sure",
    "sono": "they are / I am",
    "sottile": "thin",
    "spesso": "often",
    "standard": "standard",
    "sufficiente": "sufficient",
    "sulla": "on the",
    "suono": "sound",
    "trenta": "thirty",
    "ufficio": "office",
    "una": "one",
    "vanno": "they go",
    "vorrei": "I would like"
}

with open(vocab_path, "r", encoding="utf-8") as f:
    vocab = json.load(f)

for item in vocab:
    it = item["italian"].lower()
    if it in translations:
        item["english"] = translations[it]

with open(vocab_path, "w", encoding="utf-8") as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)

print("Filled translations for vocabulary.")
