import json
import os

base_path = "src/data/exports/miscellaneous/police_report"
vocab_path = f"{base_path}/miscellaneous_police_report_vocabulary.json"

translations = {
    "accomodi": "make yourself comfortable",
    "aiutarla": "help you",
    "aiuto": "help",
    "albergo": "hotel",
    "alloggio": "I stay",
    "allhotel": "at the hotel",
    "amico": "friend",
    "autobus": "bus",
    "averlo": "having it",
    "basso": "bottom",
    "bene": "well",
    "berrò": "I will drink",
    "bevuto": "drunk",
    "blu": "blue",
    "borsa": "bag",
    "buongiorno": "good morning",
    "cappello": "hat",
    "carta": "card",
    "casa": "home",
    "cellulare": "cellphone",
    "centro": "center",
    "cera": "there was",
    "cercato": "searched",
    "certo": "sure",
    "che": "what",
    "chiamo": "I call",
    "chiamare": "call",
    "cinema": "cinema",
    "cognome": "surname",
    "compagnia": "company",
    "compili": "fill out",
    "comprato": "bought",
    "compro": "I buy",
    "con": "with",
    "conosce": "knows",
    "contattarla": "contact you",
    "correre": "run",
    "cosa": "what",
    "cotto": "cooked",
    "cover": "cover",
    "cucina": "kitchen",
    "cucinato": "cooked",
    "dappertutto": "everywhere",
    "data": "date",
    "dati": "details",
    "denuncia": "report",
    "deve": "must",
    "devo": "I must",
    "dimenticato": "forgotten",
    "didentità": "of identity",
    "dispiace": "I'm sorry",
    "dobbiamo": "we must",
    "documenti": "documents",
    "documento": "document",
    "dove": "where",
    "due": "two",
    "ecco": "here is",
    "era": "it was",
    "ero": "I was",
    "esame": "exam",
    "fare": "do",
    "farò": "I will do",
    "felice": "happy",
    "film": "movie",
    "firma": "signature",
    "firmi": "sign",
    "forno": "oven",
    "freddo": "cold",
    "gatto": "cat",
    "gente": "people",
    "giacca": "jacket",
    "grazie": "thank you",
    "hanno": "they have",
    "hotel": "hotel",
    "ieri": "yesterday",
    "il": "the",
    "immediatamente": "immediately",
    "in": "in",
    "indirizzo": "address",
    "italia": "Italy",
    "la": "the",
    "lavato": "washed",
    "le": "the",
    "leggerò": "I will read",
    "letto": "read",
    "lezione": "lesson",
    "libro": "book",
    "lo": "it",
    "macchina": "car",
    "madre": "mother",
    "mangiato": "ate",
    "mangio": "I eat",
    "marca": "brand",
    "mario": "Mario",
    "mare": "sea",
    "memoria": "memory",
    "messaggio": "message",
    "mi": "to me",
    "miei": "my",
    "mille": "a thousand",
    "mio": "my",
    "modello": "model",
    "modulo": "form",
    "molta": "a lot",
    "molto": "very",
    "nascita": "birth",
    "nato": "born",
    "nel": "in the",
    "nero": "black",
    "non": "not",
    "nuova": "new",
    "numero": "number",
    "oggi": "today",
    "ora": "now",
    "pane": "bread",
    "passaporto": "passport",
    "pasta": "pasta",
    "paura": "fear",
    "penna": "pen",
    "per": "for",
    "perché": "why",
    "perso": "lost",
    "personali": "personal",
    "piace": "like",
    "piacciono": "like",
    "piazza": "square",
    "piscina": "pool",
    "pizzeria": "pizzeria",
    "po": "bit",
    "portafoglio": "wallet",
    "posso": "can I",
    "prego": "please",
    "preso": "taken",
    "quaderno": "notebook",
    "qual": "which",
    "quale": "which",
    "quali": "which",
    "qualcuno": "someone",
    "quando": "when",
    "qui": "here",
    "regalo": "gift",
    "ricordo": "remember",
    "roma": "Rome",
    "rossa": "red",
    "rossi": "Rossi",
    "rubato": "stolen",
    "ruote": "wheels",
    "salve": "hello",
    "scarpe": "shoes",
    "scriva": "write",
    "scrivere": "write",
    "scuola": "school",
    "serie": "series",
    "sera": "evening",
    "servono": "are needed",
    "sicuro": "sure",
    "smartphone": "smartphone",
    "soldi": "money",
    "stamattina": "this morning",
    "stampatello": "block letters",
    "stanco": "tired",
    "studiato": "studied",
    "studiare": "study",
    "suo": "his/her",
    "suoi": "his/her",
    "tasca": "pocket",
    "teatro": "theater",
    "telefono": "phone",
    "telefonica": "telephone",
    "tre": "three",
    "trovava": "found oneself",
    "trovato": "found",
    "torta": "cake",
    "un": "a",
    "una": "a",
    "uno": "a",
    "uscire": "go out",
    "va": "goes",
    "vederti": "see you",
    "velocemente": "quickly",
    "verde": "green",
    "visto": "seen",
    "voglia": "desire"
}

with open(vocab_path, "r", encoding="utf-8") as f:
    vocab = json.load(f)

for v in vocab:
    if not v["english"]:
        w = v["italian"].lower()
        if w in translations:
            v["english"] = translations[w]
        else:
            # Simple fallback
            v["english"] = w

with open(vocab_path, "w", encoding="utf-8") as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)
