import json
import os

d = 'src/data/exports/tech/video_call'
v_path = f'{d}/tech_video_call_vocabulary.json'
p_path = f'{d}/tech_video_call_phrases.json'

trans = {
"accendere": "to turn on",
"accendo": "I turn on",
"accesa": "turned on",
"accordo": "agreement",
"adesso": "now",
"aggiorniamo": "we update",
"alla": "to the",
"allora": "then",
"altre": "other",
"altro": "other",
"anche": "also",
"andiamo": "we go",
"aperto": "open",
"apparire": "to appear",
"appena": "just",
"aprendo": "opening",
"apriamo": "we open",
"apro": "I open",
"aspetto": "I wait",
"attimo": "moment",
"avanti": "forward",
"avevo": "I had",
"basso": "low",
"bene": "well",
"benissimo": "very well",
"blocca": "blocks",
"buona": "good",
"cadesse": "would fall",
"carichi": "loads",
"cenno": "sign",
"certo": "sure",
"che": "that",
"chiamata": "call",
"chiara": "clear",
"chiaramente": "clearly",
"chiudere": "to close",
"chiudo": "I close",
"ciao": "hello",
"clicca": "click",
"clicco": "I click",
"come": "how",
"con": "with",
"condividi": "share",
"condivido": "I share",
"condiviso": "shared",
"conferma": "confirm",
"confermato": "confirmed",
"continua": "continues",
"controllo": "I check",
"correggo": "I correct",
"così": "so",
"credo": "I believe",
"dati": "data",
"davanti": "in front",
"debole": "weak",
"dei": "of the",
"del": "of the",
"della": "of the",
"dello": "of the",
"dimmi": "tell me",
"direttamente": "directly",
"dispiace": "I'm sorry",
"diverse": "different",
"documento": "document",
"domande": "questions",
"dopo": "after",
"dovrebbe": "should",
"due": "two",
"ecco": "here is",
"ehi": "hey",
"errore": "error",
"fammi": "make me",
"fare": "to do",
"fatto": "done",
"favore": "favor",
"file": "file",
"finestra": "window",
"forse": "maybe",
"forte": "strong",
"freccia": "arrow",
"giornata": "day",
"grazie": "thanks",
"hai": "you have",
"idea": "idea",
"immagine": "image",
"iniziamo": "we begin",
"iniziare": "to begin",
"intero": "whole",
"inviato": "sent",
"lavoro": "work",
"legge": "reads",
"leggi": "read",
"male": "badly",
"meglio": "better",
"meno": "less",
"menu": "menu",
"metterla": "to put it",
"mia": "my",
"migliorare": "to improve",
"mille": "a thousand",
"mio": "my",
"modalità": "mode",
"modifiche": "changes",
"molto": "very",
"monitor": "monitor",
"mostrare": "to show",
"necessario": "necessary",
"nell": "in the",
"nella": "in the",
"non": "not",
"numeri": "numbers",
"oggi": "today",
"opzioni": "options",
"ora": "now",
"ottimo": "excellent",
"pagina": "page",
"paragrafo": "paragraph",
"parlare": "to speak",
"parliamo": "we speak",
"parte": "part",
"passiamo": "we pass",
"passo": "I pass",
"pazienza": "patience",
"per": "for",
"perfetto": "perfect",
"più": "more",
"poi": "then",
"possiamo": "we can",
"posso": "I can",
"preoccupare": "worry",
"preoccuparti": "worry",
"presentazione": "presentation",
"presto": "soon",
"prima": "first",
"primo": "first",
"progetto": "project",
"pronto": "ready",
"prossima": "next",
"provo": "I try",
"pulsante": "button",
"punto": "point",
"puoi": "you can",
"pure": "also",
"purtroppo": "unfortunately",
"qualità": "quality",
"questo": "this",
"qui": "here",
"ragione": "reason",
"rapida": "fast",
"resto": "rest",
"riesci": "you succeed",
"riesco": "I succeed",
"riga": "line",
"salviamo": "we save",
"sbaglio": "I mistake",
"scegli": "choose",
"scusa": "sorry",
"seconda": "second",
"secondo": "second",
"segnalare": "to report",
"sei": "you are",
"sembra": "seems",
"senti": "you hear",
"sentiamo": "we hear",
"sento": "I hear",
"senza": "without",
"sia": "is",
"simbolo": "symbol",
"slide": "slide",
"sono": "I am",
"spegnere": "to turn off",
"spenga": "turns off",
"spengo": "I turn off",
"spento": "turned off",
"spiegare": "to explain",
"stabile": "stable",
"sto": "I am",
"strani": "strange",
"subito": "immediately",
"successiva": "next",
"sul": "on the",
"sullo": "on the",
"tardi": "late",
"temevo": "I feared",
"tempo": "time",
"tendina": "drop-down",
"tengo": "I keep",
"terminiamo": "we finish",
"testo": "text",
"togliere": "to remove",
"tranquillo": "calm",
"tua": "your",
"tuo": "your",
"tutto": "everything",
"una": "a",
"vado": "I go",
"vai": "you go",
"vedere": "to see",
"vederti": "to see you",
"vedi": "you see",
"vedo": "I see",
"verde": "green",
"vero": "true",
"visto": "seen",
"voce": "voice",
"vuoi": "you want",
"Bene, se non mi senti fammi un cenno.": "Good, if you don't hear me give me a sign.",
"Buona idea, spengo la mia telecamera adesso.": "Good idea, I'm turning off my camera now.",
"Certo, accendo la telecamera in un attimo.": "Sure, I'll turn on the camera in a moment.",
"Certo, clicco sul simbolo dello schermo intero.": "Sure, I'm clicking on the full screen symbol.",
"Certo, condivido lo schermo subito.": "Sure, I'll share the screen immediately.",
"Ci sono, scusa, avevo il microfono spento.": "I'm here, sorry, I had the microphone turned off.",
"Ciao, purtroppo ti sento molto male.": "Hello, unfortunately I hear you very badly.",
"Credo di sì, c'è un errore nella seconda riga.": "I believe so, there is an error in the second line.",
"D'accordo, ciao e a più tardi.": "All right, bye and see you later.",
"D'accordo, grazie per il tempo, ci sentiamo presto.": "All right, thanks for the time, we'll talk soon.",
"D'accordo, passo subito alla slide successiva.": "All right, I'll move on to the next slide immediately.",
"Fatto. Ora vedo una finestra con diverse opzioni.": "Done. Now I see a window with different options.",
"Forse, la tua immagine si blocca.": "Maybe your image freezes.",
"Grazie mille, chiudo la chiamata, buona giornata!": "Thank you very much, I'll close the call, have a good day!",
"Grazie, posso iniziare a spiegare la prima parte.": "Thanks, I can begin explaining the first part.",
"Hai ragione, controllo i dati adesso.": "You're right, I'm checking the data now.",
"Meno male, temevo che la connessione cadesse.": "Thank goodness, I feared the connection would drop.",
"No, il resto del testo va benissimo così.": "No, the rest of the text is fine as it is.",
"No, per me è tutto molto chiaro così.": "No, it's all very clear to me this way.",
"No, sembra che la connessione sia molto rapida.": "No, it seems the connection is very fast.",
"Non è necessario, riesco a vederti bene.": "It's not necessary, I can see you well.",
"Oh, mi dispiace. La connessione è un po' debole oggi.": "Oh, I'm sorry. The connection is a bit weak today.",
"Ok, ho confermato. Riesci a vedere il mio schermo?": "Ok, I confirmed. Can you see my screen?",
"Ottimo, la mia connessione oggi è buona.": "Excellent, my connection today is good.",
"Ottimo, ora apro il file della presentazione.": "Excellent, now I'll open the presentation file.",
"Perfetto, allora passiamo alla prossima slide.": "Perfect, then let's move on to the next slide.",
"Scusa, accendo subito il microfono.": "Sorry, I'll turn on the microphone immediately.",
"Sì, adesso la voce è più chiara.": "Yes, now the voice is clearer.",
"Sì, anche io ti sento chiaramente senza il video.": "Yes, I also hear you clearly without the video.",
"Sì, andiamo direttamente al primo punto.": "Yes, let's go directly to the first point.",
"Sì, apriamo il file condiviso per favore.": "Yes, let's open the shared file please.",
"Sì, clicco su condividi schermo subito.": "Yes, I'll click on share screen immediately.",
"Sì, ho il file aperto sullo schermo.": "Yes, I have the file open on the screen.",
"Sì, ho il testo davanti a me sul monitor.": "Yes, I have the text in front of me on the monitor.",
"Sì, l'ho appena aperto sul mio schermo.": "Yes, I just opened it on my screen.",
"Sì, la connessione è molto stabile.": "Yes, the connection is very stable.",
"Sì, sono pronto, dimmi come condividere.": "Yes, I'm ready, tell me how to share.",
"Sì, vedo il pulsante verde con la freccia.": "Yes, I see the green button with the arrow.",
"Tranquillo, aspetto che si carichi la pagina.": "Don't worry, I'll wait for the page to load.",
"Va bene, vado alla pagina due.": "Alright, I'll go to page two."
}

for path in [v_path, p_path]:
    with open(path) as f:
        data = json.load(f)
    for item in data:
        if not item.get('english'):
            item['english'] = trans.get(item['italian'], "")
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)

print("done")
