
import json
import os

def translate_item(it):
    # Dictionary for common words in this scenario
    d = {
        "abbiamo": "we have",
        "accordo": "agreement / agreed",
        "aggiungere": "to add",
        "alla": "to the / with",
        "allora": "then / so",
        "altro": "other / else",
        "anche": "also / too",
        "andate": "you go (plural)",
        "arrivederci": "goodbye",
        "aspri": "sour (plural)",
        "aspro": "sour",
        "assaggiare": "to taste",
        "attenzione": "attention / careful",
        "avere": "to have",
        "bel": "nice / beautiful",
        "bene": "well / good",
        "benissimo": "very well",
        "benvenuti": "welcome",
        "bianco": "white",
        "buona": "good",
        "buonasera": "good evening",
        "buongiorno": "good morning",
        "buono": "good",
        "caldo": "hot",
        "centesimi": "cents",
        "cercate": "you look for",
        "certamente": "certainly",
        "che": "that / what",
        "ciao": "hi / bye",
        "cinquanta": "fifty",
        "cioccolato": "chocolate",
        "con": "with",
        "cono": "cone",
        "coppetta": "small cup",
        "cosa": "thing / what",
        "costa": "it costs",
        "così": "so / like this",
        "crema": "cream / custard",
        "cucchiaino": "small spoon",
        "dal": "from the",
        "decidere": "to decide",
        "dei": "of the / some",
        "del": "of the",
        "della": "of the",
        "desidera": "you desire / would like",
        "dieci": "ten",
        "dimensione": "size / dimension",
        "dove": "where",
        "due": "two",
        "ecco": "here is / here are",
        "euro": "euro",
        "fare": "to do / to make",
        "favore": "favor",
        "fondente": "dark (chocolate)",
        "fragola": "strawberry",
        "fresca": "fresh",
        "fresco": "fresh",
        "fretta": "hurry",
        "frutta": "fruit",
        "fuori": "outside",
        "fuso": "melted",
        "gelati": "gelatos",
        "gelato": "gelato / ice cream",
        "giornata": "day",
        "goda": "enjoy (subjunctive/imperative formal)",
        "grande": "large",
        "grazie": "thank you",
        "gruppo": "group",
        "gusti": "flavors",
        "gusto": "flavor",
        "iniziamo": "we start",
        "insieme": "together",
        "latte": "milk",
        "leggero": "light",
        "lei": "you (formal) / she",
        "liberi": "free / vacant",
        "limone": "lemon",
        "mangiamo": "we eat",
        "mangiare": "to eat",
        "media": "medium",
        "medio": "medium",
        "mettere": "to put",
        "mettiamo": "we put",
        "mille": "thousand",
        "mio": "my",
        "misure": "sizes / measures",
        "molti": "many",
        "molto": "very / much",
        "montata": "whipped",
        "nella": "in the",
        "nocciola": "hazelnut",
        "noi": "us / we",
        "nostro": "our",
        "oggi": "today",
        "ora": "now / hour",
        "ottima": "excellent",
        "ottime": "excellent",
        "ottimo": "excellent",
        "pagare": "to pay",
        "paghiamo": "we pay",
        "pago": "I pay",
        "panna": "cream",
        "passeggiata": "walk",
        "per": "for",
        "perfetto": "perfect",
        "pezzetti": "small pieces",
        "piacciono": "they like",
        "piace": "it likes / to like",
        "piccola": "small",
        "piccolo": "small",
        "pistacchio": "pistachio",
        "porta": "takes / leads",
        "portarvi": "to bring to you",
        "posso": "I can",
        "preferisce": "you prefer",
        "preferito": "favorite",
        "prendo": "I take",
        "preparo": "I prepare",
        "presto": "soon / early",
        "prima": "before",
        "primo": "first",
        "può": "he/she/it can",
        "qualcosa": "something",
        "quale": "which",
        "quali": "which (plural)",
        "quanti": "how many",
        "quanto": "how much",
        "quattro": "four",
        "quello": "that one",
        "questi": "these",
        "riguarda": "regards / concerns",
        "sceglie": "you choose",
        "scelta": "choice",
        "scelte": "choices",
        "sciolgono": "they melt",
        "secondo": "second",
        "sedersi": "to sit down",
        "senza": "without",
        "serata": "evening",
        "serve": "it serves / is needed",
        "siedo": "I sit",
        "siete": "you are (plural)",
        "soldi": "money",
        "solo": "only",
        "sono": "I am / they are",
        "sopra": "above / on top",
        "stracciatella": "stracciatella (chocolate chip)",
        "sua": "your (formal) / her",
        "subito": "immediately",
        "sul": "on the",
        "suo": "your (formal) / his",
        "tavoli": "tables",
        "totale": "total",
        "tovagliolo": "napkin",
        "tre": "three",
        "tutti": "all / everyone",
        "tutto": "everything",
        "ultimo": "last",
        "una": "a / one",
        "vado": "I go",
        "vaniglia": "vanilla",
        "vanno": "they go",
        "vede": "he/she/it sees",
        "vegano": "vegan",
        "vero": "true / real",
        "via": "away / street",
        "volete": "you want (plural)",
        "vorrei": "I would like",
        "vorremmo": "we would like",
        "vostri": "your (plural)",
        "vuole": "he/she/it wants",
    }
    return d.get(it.lower().strip(), "")

def translate_phrase(it):
    d = {
        "Cioccolato, crema e pistacchio.": "Chocolate, cream and pistachio.",
        "Cioccolato, stracciatella e nocciola.": "Chocolate, stracciatella and hazelnut.",
        "Ecco a lei. Buona serata!": "Here you go. Have a good evening!",
        "Ecco a lei. Grazie mille.": "Here you go. Thank you very much.",
        "Ecco i soldi. Grazie mille.": "Here is the money. Thank you very much.",
        "Fragola e vaniglia, per favore.": "Strawberry and vanilla, please.",
        "Grazie mille, arrivederci!": "Thank you very much, goodbye!",
        "Grazie, arrivederci!": "Thank you, goodbye!",
        "Grazie, buona giornata anche a lei!": "Thank you, have a nice day as well!",
        "Grazie, li mangiamo subito!": "Thank you, we'll eat them right away!",
        "Il primo è un cono grande.": "The first one is a large cone.",
        "Il secondo è una coppetta piccola.": "The second one is a small cup.",
        "L'ultimo è un cono medio.": "The last one is a medium cone.",
        "Mi siedo fuori, grazie.": "I'll sit outside, thank you.",
        "No, così va bene. Grazie.": "No, this is fine. Thank you.",
        "No, grazie, questi tre vanno bene.": "No, thank you, these three are fine.",
        "No, grazie. Quanto costa?": "No, thank you. How much does it cost?",
        "No, senza panna, grazie.": "No, without cream, thank you.",
        "No, solo sul cono grande.": "No, only on the large cone.",
        "Ottimo, ecco a lei i soldi.": "Excellent, here is the money for you.",
        "Prendo il cioccolato fondente.": "I'll take the dark chocolate.",
        "Prendo una coppetta media.": "I'll take a medium cup.",
        "Sì, grazie. Quanto pago?": "Yes, thank you. How much do I pay?",
        "Sì, il cioccolato è il mio preferito.": "Yes, chocolate is my favorite.",
        "Sì, il gelato è perfetto ora.": "Yes, the gelato is perfect now.",
        "Sì, mi piace molto il limone.": "Yes, I like lemon very much.",
        "Sì, paghiamo tutto insieme.": "Yes, we'll pay all together.",
        "Sì, posso assaggiare il pistacchio?": "Yes, can I taste the pistachio?",
        "Sì, posso avere un tovagliolo?": "Yes, can I have a napkin?",
        "Sì, vorrei un gelato alla frutta.": "Yes, I would like a fruit gelato.",
        "Sì, vorrei un gelato, per favore.": "Yes, I would like a gelato, please.",
        "Sì, vorrei un po' di cioccolato fuso.": "Yes, I would like some melted chocolate.",
        "Sì, è delizioso! Prendo quello.": "Yes, it's delicious! I'll take that one.",
        "Un cono piccolo va bene.": "A small cone is fine.",
        "Una coppetta piccola, per favore.": "A small cup, please.",
        "Vado a fare una passeggiata.": "I'm going for a walk.",
        "Vorrei cioccolato e fragola.": "I would like chocolate and strawberry.",
        "Vorrei limone e fragola, grazie.": "I would like lemon and strawberry, thank you.",
        "Vorrei un cono, grazie.": "I would like a cone, thank you.",
        "Vorrei una coppetta di gelato.": "I would like a cup of gelato.",
        "Vorremmo tre gelati in totale.": "We would like three gelatos in total.",
    }
    return d.get(it.strip(), "")

def main():
    base = "src/data/exports/dining/gelato_shop/"
    
    # Vocabulary
    v_file = base + "dining_gelato_shop_vocabulary.json"
    with open(v_file, "r", encoding="utf-8") as f:
        vocab = json.load(f)
    for item in vocab:
        if not item.get("english"):
            item["english"] = translate_item(item["italian"])
    with open(v_file, "w", encoding="utf-8") as f:
        json.dump(vocab, f, indent=2, ensure_ascii=False)
        
    # Phrases
    p_file = base + "dining_gelato_shop_phrases.json"
    with open(p_file, "r", encoding="utf-8") as f:
        phrases = json.load(f)
    for item in phrases:
        if not item.get("english"):
            item["english"] = translate_phrase(item["italian"])
    with open(p_file, "w", encoding="utf-8") as f:
        json.dump(phrases, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    main()
