import json

translations = {
    "accordo": "agreement",
    "acqua": "water",
    "affascinante": "fascinating",
    "agli": "to the",
    "aiuto": "help",
    "albero": "tree",
    "alla": "to the",
    "alle": "to the",
    "alto": "high / tall",
    "altri": "others",
    "ama": "loves",
    "amici": "friends",
    "anche": "also / too",
    "animali": "animals",
    "assoluto": "absolute",
    "aver": "having",
    "bel": "beautiful / nice",
    "bella": "beautiful / nice",
    "belli": "beautiful / nice",
    "bellissimo": "very beautiful / wonderful",
    "benvenuti": "welcome",
    "beve": "drinks",
    "bianchi": "white",
    "buddy": "Buddy",
    "cani": "dogs",
    "cantano": "they sing",
    "capisco": "I understand",
    "capito": "understood / I see",
    "carne": "meat",
    "casa": "house / home",
    "cavalli": "horses",
    "certo": "sure / certainly",
    "chiama": "calls / is named",
    "colore": "color",
    "condiviso": "shared",
    "corre": "runs",
    "corrono": "they run",
    "così": "so / like this",
    "cuccioli": "puppies / cubs",
    "danno": "they give",
    "dare": "to give",
    "dei": "of the",
    "del": "of the",
    "della": "of the",
    "dentro": "inside",
    "difficile": "difficult",
    "divertente": "fun / funny",
    "dorme": "sleeps",
    "dormono": "they sleep",
    "ecco": "here is / here are",
    "erba": "grass",
    "fanno": "they do / they make",
    "felici": "happy",
    "foresta": "forest",
    "forse": "maybe",
    "forte": "strong",
    "forti": "strong",
    "galline": "chickens / hens",
    "gatti": "cats",
    "giocano": "they play",
    "giornata": "day",
    "giorno": "day",
    "già": "already",
    "gli": "the",
    "grandi": "big / great",
    "guarda": "look",
    "guardate": "look",
    "hai": "you have",
    "hanno": "they have",
    "importante": "important",
    "lui": "he / him",
    "mangia": "eats",
    "mangiando": "eating",
    "mangiano": "they eat",
    "marroni": "brown",
    "mattina": "morning",
    "miei": "my",
    "migliore": "best / better",
    "molta": "much / a lot of",
    "molte": "many",
    "molti": "many",
    "mucche": "cows",
    "nel": "in the",
    "nell": "in the",
    "nella": "in the",
    "oggi": "today",
    "ogni": "every / each",
    "ora": "now / hour",
    "palla": "ball",
    "parlare": "to speak / to talk",
    "pensieri": "thoughts",
    "perfetto": "perfect",
    "persone": "people",
    "piaccioni": "they like",
    "piacciono": "they like",
    "piace": "likes",
    "piacerebbe": "would like",
    "piccole": "small",
    "portano": "they bring",
    "porto": "I bring",
    "possono": "they can",
    "posto": "place",
    "preferisci": "you prefer",
    "preferisco": "I prefer",
    "preferiscono": "they prefer",
    "preferiti": "favorite",
    "preferito": "favorite",
    "puliti": "clean",
    "pulito": "clean",
    "qual": "which / what",
    "quanti": "how many",
    "quel": "that",
    "quell": "that",
    "rende": "makes / renders",
    "rilassante": "relaxing",
    "rispettare": "to respect",
    "rosso": "red",
    "scegliere": "to choose",
    "sei": "six / you are",
    "selvaggi": "wild",
    "sembra": "seems",
    "senti": "you hear / feel",
    "sentite": "you hear / feel",
    "sicuramente": "surely / certainly",
    "simpatici": "nice / friendly",
    "simpatico": "nice / friendly",
    "solo": "only / alone",
    "sono": "I am / they are",
    "sopra": "above / on",
    "spettacolo": "sight / show",
    "sta": "stays / is",
    "stanco": "tired",
    "stato": "been / state",
    "sua": "his / her",
    "subito": "immediately",
    "sugli": "on the",
    "sull": "on the",
    "suono": "sound",
    "tra": "between / among",
    "tranquilla": "peaceful / quiet",
    "trovare": "to find",
    "tuoi": "your",
    "tutti": "all / everyone",
    "tutto": "everything / all",
    "uccelli": "birds",
    "uno": "one / a",
    "vecchio": "old",
    "vederli": "to see them",
    "vedi": "you see",
    "vedo": "I see",
    "veloce": "fast",
    "vero": "true / right?",
    "vicino": "near / close",
    "visto": "seen",
    "vita": "life",
    "vivaci": "lively",
    "vive": "lives",
    "voce": "voice",
    "volano": "they fly",
    "volare": "to fly",
    "volete": "you want",
    "vorrei": "I would like",
    "vorresti": "you would like",
    "vuoi": "you want",
    "vuole": "wants"
}

vocab_path = 'src/data/exports/animals/animali/animals_animali_vocabulary.json'
with open(vocab_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    if item['italian'] in translations:
        item['english'] = translations[item['italian']]

with open(vocab_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
