import json

file_path = '/home/waseageru/parli-italiano/src/data/exports/dining/bakery/dining_bakery_vocabulary.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    "abbiamo": "we have",
    "accordo": "agreement / okay",
    "affettare": "to slice",
    "aiutarla": "to help you (formal)",
    "all": "at the / to the",
    "alla": "at the / to the",
    "alle": "at the / to the",
    "allora": "then / well",
    "altrettanto": "likewise / same to you",
    "altro": "else / other",
    "anche": "also / too",
    "ancora": "still / yet / more",
    "appena": "just / as soon as",
    "arrivederci": "goodbye",
    "aspettiamo": "we wait",
    "avere": "to have",
    "bambini": "children",
    "basta": "enough / that's enough",
    "bene": "well / good",
    "benissimo": "very well",
    "bianco": "white",
    "biscotti": "cookies / biscuits",
    "buon": "good",
    "buona": "good",
    "buonasera": "good evening",
    "buongiorno": "good morning",
    "buonissima": "very good / delicious",
    "burro": "butter",
    "busta": "bag / envelope",
    "canditi": "candied fruit",
    "carta": "paper / card",
    "casa": "home / house",
    "cena": "dinner",
    "certamente": "certainly",
    "certo": "of course / sure",
    "che": "that / what",
    "chilo": "kilo",
    "cinquanta": "fifty",
    "cinque": "five",
    "cinquecento": "five hundred",
    "cioccolato": "chocolate",
    "circa": "about / approximately",
    "colazione": "breakfast",
    "come": "how / like",
    "comodo": "convenient / comfortable",
    "consiglia": "recommends",
    "cornetti": "croissants",
    "cosa": "what / thing",
    "costa": "it costs",
    "così": "like this / so",
    "crema": "cream / custard",
    "croccante": "crunchy / crispy",
    "dei": "of the / some",
    "del": "of the",
    "deliziose": "delicious",
    "della": "of the",
    "delle": "of the / some",
    "dello": "of the",
    "desidera": "desires / you want (formal)",
    "devo": "I must / I have to",
    "dieci": "ten",
    "dolce": "sweet / dessert",
    "dovrebbero": "they should",
    "due": "two",
    "duecento": "two hundred",
    "ecco": "here is / here are",
    "esatto": "exact / correct",
    "etti": "hectograms (100g units)",
    "euro": "euro",
    "fatte": "made",
    "fatti": "made",
    "fatto": "made / done",
    "favore": "favor",
    "focaccia": "focaccia (Italian flatbread)",
    "fresca": "fresh",
    "gentile": "kind / polite",
    "gentilissimo": "very kind",
    "giornata": "day",
    "grammi": "grams",
    "grande": "big / large",
    "grazie": "thank you / thanks",
    "grissini": "breadsticks",
    "insieme": "together",
    "integrale": "whole wheat / wholemeal",
    "intera": "whole",
    "interessa": "interests",
    "interessante": "interesting",
    "lasci": "leaves / you leave (formal)",
    "lavoro": "work / job",
    "lei": "she / you (formal)",
    "magari": "maybe / perhaps",
    "mangio": "I eat",
    "mano": "hand",
    "medio": "medium",
    "metta": "put (formal imperative)",
    "metterli": "to put them",
    "metà": "half",
    "mezzo": "half",
    "mille": "thousand",
    "molto": "very / much",
    "morbidi": "soft",
    "non": "not",
    "nostra": "our",
    "oggi": "today",
    "olio": "oil",
    "olive": "olives",
    "ora": "now / hour",
    "ottima": "excellent",
    "ottimo": "excellent",
    "otto": "eight",
    "pagnotta": "loaf of bread",
    "pagnotte": "loaves of bread",
    "pane": "bread",
    "panini": "rolls / small sandwiches",
    "per": "for",
    "perfetta": "perfect",
    "perfetti": "perfect",
    "perfetto": "perfect",
    "pesare": "to weigh",
    "pezzetto": "small piece",
    "pezzi": "pieces",
    "pezzo": "piece",
    "piacciono": "they like",
    "piccolo": "small",
    "più": "more",
    "portare": "to bring / to carry",
    "porto": "I bring / port",
    "posso": "I can",
    "posto": "place / spot",
    "prendo": "I take",
    "presto": "soon / early",
    "pronta": "ready",
    "prossima": "next",
    "proverò": "I will try",
    "provo": "I try",
    "pure": "also / even / go ahead",
    "può": "can / you can (formal)",
    "qualcuno": "someone",
    "quanto": "how much",
    "quattro": "four",
    "quella": "that",
    "quello": "that",
    "questi": "these",
    "qui": "here",
    "resto": "rest / change (money)",
    "ricotta": "ricotta (cheese)",
    "ripiene": "filled / stuffed",
    "riscaldi": "you heat up (formal)",
    "rosmarino": "rosemary",
    "sacchetti": "bags",
    "salata": "salty / savory",
    "salutare": "to greet / healthy",
    "sapere": "to know",
    "saporita": "flavorful / tasty",
    "scelta": "choice",
    "schiacciata": "schiacciata (Tuscan flatbread)",
    "scontrino": "receipt",
    "sei": "six / you are",
    "sembra": "it seems",
    "sembrano": "they seem",
    "semplice": "simple",
    "semplici": "simple",
    "separati": "separate",
    "serve": "serves / is needed",
    "sfogliatella": "sfogliatella (Italian pastry)",
    "sfogliatelle": "sfogliatelle",
    "sfornata": "just baked / out of the oven",
    "sfornate": "just baked",
    "siamo": "we are",
    "sicuramente": "surely / for sure",
    "sono": "I am / they are",
    "sopra": "above / on top",
    "specialità": "specialty",
    "stamattina": "this morning",
    "stasera": "tonight / this evening",
    "suo": "his / her / your (formal)",
    "tagli": "you cut / cuts",
    "tardi": "late",
    "tavola": "table",
    "tenere": "to keep / to hold",
    "tenga": "keep (formal imperative)",
    "tipo": "type / kind",
    "totale": "total",
    "tre": "three",
    "troppo": "too / too much",
    "tutto": "all / everything",
    "una": "a / an",
    "uno": "a / an / one",
    "vassoio": "tray",
    "velo": "veil / thin layer",
    "via": "away / street",
    "volentieri": "gladly / with pleasure",
    "volta": "time / turn",
    "vorrei": "I would like",
    "vuole": "wants / you want (formal)",
    "zucchero": "sugar"
}

for item in data:
    if item['italian'] in translations:
        item['english'] = translations[item['italian']]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
