import json
import os

scenario_id = "s64"
category = "workstudy"
scenario_name = "email_follow_up"
base_id = f"{scenario_id}"

def create_entry(item_type, index, italian, english, choices_ital, choices_eng, feedback_correct_it, feedback_incorrect_it, feedback_correct_en, feedback_incorrect_en):
    return {
        "id": f"{base_id}-{item_type[0]}{index}",
        "italian": italian,
        "english": english,
        "type": item_type,
        "choicesItalian": choices_ital,
        "choicesEnglish": choices_eng,
        "correctAnswerItalian": italian,
        "correctAnswerEnglish": english,
        "feedback": {
            "correctItalian": feedback_correct_it,
            "incorrectItalian": feedback_incorrect_it,
            "correctEnglish": feedback_correct_en,
            "incorrectEnglish": feedback_incorrect_en
        }
    }

# VOCABULARY
vocab_data = [
    ("l'email", "the email", ["l'email", "la lettera", "il messaggio", "la nota"], ["the email", "the letter", "the message", "the note"], "Esatto! La posta elettronica.", "No, è 'l'email'.", "Exactly! Electronic mail.", "No, it's 'the email'."),
    ("il seguito", "the follow-up", ["il seguito", "l'inizio", "la fine", "il ritardo"], ["the follow-up", "the beginning", "the end", "the delay"], "Ottimo! Dare seguito a qualcosa.", "No, 'il seguito' significa follow-up.", "Great! To follow up on something.", "No, 'il seguito' means follow-up."),
    ("l'allegato", "the attachment", ["l'allegato", "l'oggetto", "la bozza", "il link"], ["the attachment", "the subject", "the draft", "the link"], "Perfetto! Il file unito all'email.", "No, è 'l'allegato'.", "Perfect! The file joined to the email.", "No, it's 'the attachment'."),
    ("l'oggetto", "the subject", ["l'oggetto", "il testo", "la firma", "il mittente"], ["the subject", "the text", "the signature", "the sender"], "Giusto! Il titolo dell'email.", "No, è 'l'oggetto'.", "Right! The title of the email.", "No, it's 'the subject'."),
    ("la bozza", "the draft", ["la bozza", "la copia", "l'invio", "la risposta"], ["the draft", "the copy", "the sending", "the reply"], "Esatto! Un'email non ancora inviata.", "No, è 'la bozza'.", "Exactly! An email not yet sent.", "No, it's 'the draft'."),
    ("inviare", "to send", ["inviare", "ricevere", "leggere", "scrivere"], ["to send", "to receive", "to read", "to write"], "Ottimo verbo! Mandare l'email.", "No, 'inviare' significa mandare.", "Great verb! To send the email.", "No, 'inviare' means to send."),
    ("ricevere", "to receive", ["ricevere", "spedire", "cancellare", "salvare"], ["to receive", "to ship", "to delete", "to save"], "Esatto! Ottenere un messaggio.", "No, è 'ricevere'.", "Exactly! To get a message.", "No, it's 'to receive'."),
    ("rispondere", "to reply", ["rispondere", "domandare", "ignorare", "chiudere"], ["to reply", "to ask", "to ignore", "to close"], "Giusto! Dare una risposta.", "No, è 'rispondere'.", "Right! To give a reply.", "No, it's 'to reply'."),
    ("inoltrare", "to forward", ["inoltrare", "copiare", "stampare", "allegare"], ["to forward", "to copy", "to print", "to attach"], "Perfetto! Mandare a un altro destinatario.", "No, 'inoltrare' significa forward.", "Perfect! To send to another recipient.", "No, 'inoltrare' means to forward."),
    ("lo spam", "the spam", ["lo spam", "la posta", "il virus", "il cestino"], ["the spam", "the mail", "the virus", "the trash"], "Esatto! La posta indesiderata.", "No, è 'lo spam'.", "Exactly! Junk mail.", "No, it's 'the spam'."),
    ("la cartella", "the folder", ["la cartella", "il file", "il disco", "lo schermo"], ["the folder", "the file", "the disk", "the screen"], "Giusto! Dove organizzi i file.", "No, è 'la cartella'.", "Right! Where you organize files.", "No, it's 'the folder'."),
    ("la conferma", "the confirmation", ["la conferma", "il dubbio", "la smentita", "l'attesa"], ["the confirmation", "the doubt", "the denial", "the wait"], "Ottimo! La prova della ricezione.", "No, è 'la conferma'.", "Great! Proof of receipt.", "No, it's 'the confirmation'."),
    ("la disponibilità", "the availability", ["la disponibilità", "la mancanza", "il costo", "la qualità"], ["the availability", "the lack", "the cost", "the quality"], "Esatto! Se qualcosa è presente.", "No, è 'la disponibilità'.", "Exactly! If something is present.", "No, it's 'the availability'."),
    ("il magazzino", "the warehouse", ["il magazzino", "l'ufficio", "il negozio", "la fabbrica"], ["the warehouse", "the office", "the store", "the factory"], "Giusto! Dove si tiene la merce.", "No, è 'il magazzino'.", "Right! Where goods are kept.", "No, it's 'the warehouse'."),
    ("l'ordine", "the order", ["l'ordine", "il caos", "la vendita", "l'acquisto"], ["the order", "the chaos", "the sale", "the purchase"], "Perfetto! La richiesta di acquisto.", "No, è 'l'ordine'.", "Perfect! The purchase request.", "No, it's 'the order'."),
    ("la spedizione", "the shipping", ["la spedizione", "il viaggio", "la consegna", "il ritiro"], ["the shipping", "the trip", "the delivery", "the pickup"], "Esatto! L'invio della merce.", "No, è 'la spedizione'.", "Exactly! Sending the goods.", "No, it's 'the shipping'."),
    ("urgente", "urgent", ["urgente", "lento", "calmo", "opzionale"], ["urgent", "slow", "calm", "optional"], "Ottimo! Da fare subito.", "No, significa 'urgent'.", "Great! To be done immediately.", "No, it means 'urgent'."),
    ("entro", "by / within", ["entro", "dopo", "fuori", "sopra"], ["by / within", "after", "outside", "above"], "Giusto! Indica una scadenza.", "No, 'entro' significa by o within.", "Right! Indicates a deadline.", "No, 'entro' means by or within."),
    ("l'attesa", "the wait", ["l'attesa", "la fretta", "la corsa", "il riposo"], ["the wait", "the hurry", "the race", "the rest"], "Esatto! Il tempo che si aspetta.", "No, è 'l'attesa'.", "Exactly! The time one waits.", "No, it's 'the wait'."),
    ("la riunione", "the meeting", ["la riunione", "la festa", "il pranzo", "la pausa"], ["the meeting", "the party", "the lunch", "the break"], "Ottimo! Incontro di lavoro.", "No, è 'la riunione'.", "Great! Work meeting.", "No, it's 'the meeting'."),
    ("il feedback", "the feedback", ["il feedback", "la domanda", "il silenzio", "il rifiuto"], ["the feedback", "the question", "the silence", "the rejection"], "Perfetto! Un commento o risposta.", "No, è 'il feedback'.", "Perfect! A comment or response.", "No, it's 'the feedback'."),
    ("la policy", "the policy", ["la policy", "la legge", "il gioco", "la strada"], ["the policy", "the law", "the game", "the road"], "Esatto! Le regole aziendali.", "No, è 'la policy'.", "Exactly! Company rules.", "No, it's 'the policy'."),
    ("aziendale", "company / corporate", ["aziendale", "personale", "privato", "pubblico"], ["company / corporate", "personal", "private", "public"], "Giusto! Relativo all'azienda.", "No, significa 'corporate'.", "Right! Relating to the company.", "No, it means 'corporate'."),
    ("il collega", "the colleague", ["il collega", "l'amico", "il capo", "il cliente"], ["the colleague", "the friend", "the boss", "the customer"], "Ottimo! Chi lavora con te.", "No, è 'il collega'.", "Great! Who works with you.", "No, it's 'the colleague'."),
    ("la risposta", "the response", ["la risposta", "il quesito", "il dubbio", "la nota"], ["the response", "the query", "the doubt", "the note"], "Esatto! Ciò che si risponde.", "No, è 'la risposta'.", "Exactly! What one replies.", "No, it's 'the response'."),
    ("controllare", "to check", ["controllare", "perdere", "ignorare", "rompere"], ["to check", "to lose", "to ignore", "to break"], "Giusto! Verificare qualcosa.", "No, significa 'to check'.", "Right! To verify something.", "No, it means 'to check'."),
    ("verificare", "to verify", ["verificare", "sbagliare", "fingere", "scordare"], ["to verify", "to make a mistake", "to pretend", "to forget"], "Ottimo! Accertarsi di qualcosa.", "No, è 'verificare'.", "Great! To make sure of something.", "No, it's 'to verify'."),
    ("immediato", "immediate", ["immediato", "ritardato", "lontano", "futuro"], ["immediate", "delayed", "far", "future"], "Esatto! Subito, senza attesa.", "No, significa 'immediate'.", "Exactly! Right away, no wait.", "No, it means 'immediate'."),
    ("il ritardo", "the delay", ["il ritardo", "l'anticipo", "la puntualità", "la velocità"], ["the delay", "the advance", "the punctuality", "the speed"], "Giusto! Quando si è in ritardo.", "No, è 'il ritardo'.", "Right! When one is late.", "No, it's 'the delay'."),
    ("la scadenza", "the deadline", ["la scadenza", "l'inizio", "il rinnovo", "la nascita"], ["the deadline", "the beginning", "the renewal", "the birth"], "Ottimo! Il termine ultimo.", "No, è 'la scadenza'.", "Great! The final term.", "No, it's 'the deadline'."),
    ("la priorità", "the priority", ["la priorità", "l'urgenza", "il dettaglio", "la noia"], ["the priority", "the urgency", "the detail", "the boredom"], "Esatto! Cosa viene prima.", "No, è 'la priorità'.", "Exactly! What comes first.", "No, it's 'the priority'."),
    ("importante", "important", ["importante", "banale", "inutile", "piccolo"], ["important", "trivial", "useless", "small"], "Giusto! Che ha valore.", "No, significa 'important'.", "Right! That has value.", "No, it means 'important'."),
    ("la notifica", "the notification", ["la notifica", "il silenzio", "l'avviso", "la chiamata"], ["the notification", "the silence", "the notice", "the call"], "Ottimo! Un segnale di arrivo.", "No, è 'la notifica'.", "Great! A signal of arrival.", "No, it's 'the notification'."),
    ("scrivere", "to write", ["scrivere", "leggere", "parlare", "ascoltare"], ["to write", "to read", "to speak", "to listen"], "Esatto! Comporre un testo.", "No, è 'scrivere'.", "Exactly! To compose a text.", "No, it's 'to write'."),
    ("l'indirizzo", "the address", ["l'indirizzo", "la via", "il numero", "il nome"], ["the address", "the street", "the number", "the name"], "Giusto! Dove mandare l'email.", "No, è 'l'indirizzo'.", "Right! Where to send the email.", "No, it's 'the address'."),
    ("il contatto", "the contact", ["il contatto", "l'estraneo", "il nemico", "il muro"], ["the contact", "the stranger", "the enemy", "the wall"], "Ottimo! La persona da sentire.", "No, è 'il contatto'.", "Great! The person to reach.", "No, it's 'the contact'."),
    ("i dettagli", "the details", ["i dettagli", "il tutto", "la sintesi", "il vuoto"], ["the details", "the whole", "the summary", "the void"], "Esatto! Le minuzie.", "No, sono 'i dettagli'.", "Exactly! The minutiae.", "No, it's 'the details'."),
    ("le informazioni", "the information", ["le informazioni", "i dati", "i segreti", "le bugie"], ["the information", "the data", "the secrets", "the lies"], "Giusto! Notizie utili.", "No, sono 'le informazioni'.", "Right! Useful news.", "No, it's 'the information'."),
    ("la richiesta", "the request", ["la richiesta", "l'offerta", "il comando", "il dono"], ["the request", "the offer", "the command", "the gift"], "Ottimo! Ciò che si chiede.", "No, è 'la richiesta'.", "Great! What is asked.", "No, it's 'the request'."),
    ("il problema", "the problem", ["il problema", "la soluzione", "il gioco", "la gioia"], ["the problem", "the solution", "the game", "the joy"], "Esatto! Una difficoltà.", "No, è 'il problema'.", "Exactly! A difficulty.", "No, it's 'the problem'."),
    ("la soluzione", "the solution", ["la soluzione", "il dubbio", "il guaio", "la fine"], ["the solution", "the doubt", "the trouble", "the end"], "Giusto! Come si risolve.", "No, è 'la soluzione'.", "Right! How it's solved.", "No, it's 'the solution'."),
    ("ringraziare", "to thank", ["ringraziare", "offendere", "salutare", "partire"], ["to thank", "to offend", "to greet", "to leave"], "Ottimo! Dire grazie.", "No, è 'ringraziare'.", "Great! To say thank you.", "No, it's 'to thank'."),
    ("la firma", "the signature", ["la firma", "il nome", "il timbro", "il foglio"], ["the signature", "the name", "the stamp", "the sheet"], "Esatto! Il nome a fine email.", "No, è 'la firma'.", "Exactly! The name at the end.", "No, it's 'the signature'."),
    ("il link", "the link", ["il link", "la catena", "la rete", "il sito"], ["the link", "the chain", "the web", "the site"], "Giusto! Il collegamento ipertestuale.", "No, è 'il link'.", "Right! The hyperlink.", "No, it's 'the link'."),
    ("cliccare", "to click", ["cliccare", "toccare", "premere", "battere"], ["to click", "to touch", "to press", "to beat"], "Ottimo! Usare il mouse.", "No, è 'cliccare'.", "Great! To use the mouse.", "No, it's 'to click'."),
    ("la bacheca", "the bulletin board", ["la bacheca", "il tavolo", "il muro", "la sedia"], ["the bulletin board", "the table", "the wall", "the chair"], "Esatto! Dove si mettono avvisi.", "No, è 'la bacheca'.", "Exactly! Where notices are put.", "No, it's 'the bulletin board'."),
    ("il mittente", "the sender", ["il mittente", "il destinatario", "il corriere", "il postino"], ["the sender", "the recipient", "the courier", "the mailman"], "Giusto! Chi manda l'email.", "No, è 'il mittente'.", "Right! Who sends the email.", "No, it's 'the sender'."),
    ("il destinatario", "the recipient", ["il destinatario", "il mittente", "l'autore", "il lettore"], ["the recipient", "the sender", "the author", "the reader"], "Ottimo! Chi riceve l'email.", "No, è 'il destinatario'.", "Great! Who receives the email.", "No, it's 'the recipient'."),
    ("la posta in arrivo", "the inbox", ["la posta in arrivo", "la posta inviata", "il cestino", "lo spam"], ["the inbox", "the sent mail", "the trash", "the spam"], "Esatto! Dove arrivano i messaggi.", "No, è 'la posta in arrivo'.", "Exactly! Where messages arrive.", "No, it's 'the inbox'."),
    ("la bozza", "the draft", ["la bozza", "la copia", "l'originale", "la stampa"], ["the draft", "the copy", "the original", "the print"], "Giusto! Versione non finale.", "No, è 'la bozza'.", "Right! Non-final version.", "No, it's 'the draft'."),
    ("sollecitare", "to urge / to prompt", ["sollecitare", "aspettare", "calmare", "evitare"], ["to urge / to prompt", "to wait", "to calm", "to avoid"], "Ottimo! Chiedere con insistenza.", "No, è 'sollecitare'.", "Great! To ask insistently.", "No, it's 'to urge'."),
    ("la comunicazione", "the communication", ["la comunicazione", "il silenzio", "il grido", "la radio"], ["the communication", "the silence", "the shout", "the radio"], "Esatto! Lo scambio di info.", "No, è 'la comunicazione'.", "Exactly! Exchange of info.", "No, it's 'the communication'."),
]

# PHRASES
phrases_data = [
    ("Ho mandato un'email.", "I sent an email.", ["Ho mandato un'email.", "Ho ricevuto un'email.", "Ho letto un'email.", "Ho scritto un'email."], ["I sent an email.", "I received an email.", "I read an email.", "I wrote an email."], "Esatto! Passato prossimo di mandare.", "No, significa 'I sent an email'.", "Exactly! Past tense of to send.", "No, it means 'I sent an email'."),
    ("Hai visto la mia email?", "Did you see my email?", ["Hai visto la mia email?", "Hai preso la mia email?", "Hai perso la mia email?", "Hai dato la mia email?"], ["Did you see my email?", "Did you take my email?", "Did you lose my email?", "Did you give my email?"], "Ottimo! Chiedere conferma.", "No, è 'Hai visto...?'.", "Great! Asking for confirmation.", "No, it's 'Did you see...?'."),
    ("Non ho ricevuto nulla.", "I haven't received anything.", ["Non ho ricevuto nulla.", "Non ho visto nulla.", "Non ho detto nulla.", "Non ho fatto nulla."], ["I haven't received anything.", "I haven't seen anything.", "I haven't said anything.", "I haven't done anything."], "Esatto! Negazione della ricezione.", "No, significa 'I haven't received anything'.", "Exactly! Negation of receipt.", "No, it means 'I haven't received anything'."),
    ("Controlla nello spam.", "Check in the spam.", ["Controlla nello spam.", "Guarda nella cartella.", "Apri l'allegato.", "Invia il file."], ["Check in the spam.", "Look in the folder.", "Open the attachment.", "Send the file."], "Giusto! Un consiglio comune.", "No, è 'Controlla nello spam'.", "Right! Common advice.", "No, it's 'Check in the spam'."),
    ("Ti rispondo subito.", "I'll reply to you right away.", ["Ti rispondo subito.", "Ti chiamo dopo.", "Ti scrivo domani.", "Ti vedo stasera."], ["I'll reply to you right away.", "I'll call you later.", "I'll write to you tomorrow.", "I'll see you tonight."], "Perfetto! Indica immediatezza.", "No, significa 'I'll reply right away'.", "Perfect! Indicates immediacy.", "No, it means 'I'll reply right away'."),
    ("Le faccio sapere.", "I'll let you know.", ["Le faccio sapere.", "Le dico tutto.", "Le porto il file.", "Le mando l'email."], ["I'll let you know.", "I'll tell you everything.", "I'll bring you the file.", "I'll send you the email."], "Esatto! Espressione formale.", "No, significa 'I'll let you know'.", "Exactly! Formal expression.", "No, it means 'I'll let you know'."),
    ("Dare seguito a...", "To follow up on...", ["Dare seguito a...", "Iniziare a...", "Finire di...", "Cercare di..."], ["To follow up on...", "To start to...", "To finish...", "To try to..."], "Ottimo! Espressione chiave.", "No, è 'Dare seguito a...'.", "Great! Key expression.", "No, it's 'To follow up on...'."),
    ("La spedizione è urgente.", "The shipping is urgent.", ["La spedizione è urgente.", "L'ordine è pronto.", "Il pacco è arrivato.", "La merce è finita."], ["The shipping is urgent.", "The order is ready.", "The package has arrived.", "The goods are finished."], "Esatto! Indica priorità.", "No, significa 'The shipping is urgent'.", "Exactly! Indicates priority.", "No, it means 'The shipping is urgent'."),
    ("Mi serve entro domani.", "I need it by tomorrow.", ["Mi serve entro domani.", "Lo voglio per ieri.", "Arriva tra poco.", "È pronto adesso."], ["I need it by tomorrow.", "I want it for yesterday.", "It's arriving soon.", "It's ready now."], "Giusto! Una scadenza vicina.", "No, è 'entro domani'.", "Right! A close deadline.", "No, it's 'by tomorrow'."),
    ("Grazie per il feedback.", "Thanks for the feedback.", ["Grazie per il feedback.", "Prego per l'aiuto.", "Scusa per il ritardo.", "Ciao per ora."], ["Thanks for the feedback.", "You're welcome for the help.", "Sorry for the delay.", "Bye for now."], "Ottimo! Ringraziamento comune.", "No, è 'Grazie per il feedback'.", "Great! Common thanks.", "No, it's 'Thanks for the feedback'."),
    ("Scusa il ritardo.", "Sorry for the delay.", ["Scusa il ritardo.", "Prego il disturbo.", "Guarda l'email.", "Leggi il file."], ["Sorry for the delay.", "You're welcome for the bother.", "Look at the email.", "Read the file."], "Esatto! Scusa formale/informale.", "No, è 'Scusa il ritardo'.", "Exactly! Formal/informal apology.", "No, it's 'Sorry for the delay'."),
    ("Ho dimenticato l'allegato.", "I forgot the attachment.", ["Ho dimenticato l'allegato.", "Ho perso l'email.", "Ho visto il link.", "Ho inviato la bozza."], ["I forgot the attachment.", "I lost the email.", "I saw the link.", "I sent the draft."], "Giusto! Errore molto comune.", "No, significa 'I forgot the attachment'.", "Right! Very common error.", "No, it means 'I forgot the attachment'."),
    ("Qual è l'oggetto?", "What is the subject?", ["Qual è l'oggetto?", "Chi è il mittente?", "Dove è il file?", "Quando è l'invio?"], ["What is the subject?", "Who is the sender?", "Where is the file?", "When is the sending?"], "Perfetto! Chiedere il titolo.", "No, è 'Qual è l'oggetto?'.", "Perfect! Asking for the title.", "No, it's 'What is the subject?'."),
    ("Inoltro l'email a Mario.", "I'm forwarding the email to Mario.", ["Inoltro l'email a Mario.", "Scrivo l'email a Mario.", "Leggo l'email di Mario.", "Cancello l'email per Mario."], ["I'm forwarding the email to Mario.", "I'm writing the email to Mario.", "I'm reading Mario's email.", "I'm deleting the email for Mario."], "Esatto! Azione di inoltrare.", "No, significa 'I'm forwarding...'.", "Exactly! Action of forwarding.", "No, it means 'I'm forwarding...'."),
    ("Ci sentiamo più tardi.", "We'll talk later.", ["Ci sentiamo più tardi.", "Ci vediamo domani.", "Ci scriviamo ora.", "Ci sentiamo subito."], ["We'll talk later.", "We'll see each other tomorrow.", "We'll write each other now.", "We'll talk right away."], "Ottimo! Chiusura di conversazione.", "No, significa 'We'll talk later'.", "Great! Conversation closer.", "No, it means 'We'll talk later'."),
    ("Rimango in attesa.", "I'll wait / I remain waiting.", ["Rimango in attesa.", "Vado via ora.", "Torno subito.", "Spero bene."], ["I'll wait / I remain waiting.", "I'm leaving now.", "I'll be right back.", "I hope so."], "Giusto! Chiusura formale.", "No, significa 'I remain waiting'.", "Right! Formal closing.", "No, it means 'I remain waiting'."),
    ("Cordiali saluti.", "Best regards.", ["Cordiali saluti.", "Cari amici.", "Tanti auguri.", "Buona fortuna."], ["Best regards.", "Dear friends.", "Best wishes.", "Good luck."], "Esatto! Saluto formale.", "No, è 'Cordiali saluti'.", "Exactly! Formal greeting.", "No, it's 'Best regards'."),
    ("Fammi sapere cosa ne pensi.", "Let me know what you think.", ["Fammi sapere cosa ne pensi.", "Dimmi dove vai.", "Chiedimi aiuto.", "Senti questo."], ["Let me know what you think.", "Tell me where you go.", "Ask me for help.", "Hear this."], "Ottimo! Chiedere un parere.", "No, significa 'Let me know...'.", "Great! Asking for an opinion.", "No, it means 'Let me know...'."),
    ("Ne parliamo in riunione.", "We'll talk about it in the meeting.", ["Ne parliamo in riunione.", "Lo scriviamo in email.", "Lo vediamo dopo.", "Ci pensiamo domani."], ["We'll talk about it in the meeting.", "We'll write it in email.", "We'll see it later.", "We'll think about it tomorrow."], "Esatto! Rimandare alla riunione.", "No, è 'in riunione'.", "Exactly! Postponing to the meeting.", "No, it's 'in the meeting'."),
    ("Verifica la disponibilità.", "Verify the availability.", ["Verifica la disponibilità.", "Controlla il prezzo.", "Compra l'oggetto.", "Vendi tutto."], ["Verify the availability.", "Check the price.", "Buy the object.", "Sell everything."], "Giusto! Un ordine o richiesta.", "No, è 'Verifica la...'.", "Right! A command or request.", "No, it's 'Verify the...'."),
    ("Mi dia un attimo.", "Give me a second.", ["Mi dia un attimo.", "Mi porti il file.", "Mi scusi ora.", "Mi dica tutto."], ["Give me a second.", "Bring me the file.", "Excuse me now.", "Tell me everything."], "Perfetto! Chiedere tempo.", "No, significa 'Give me a second'.", "Perfect! Asking for time.", "No, it means 'Give me a second'."),
    ("Controllo subito.", "I'll check right away.", ["Controllo subito.", "Leggo dopo.", "Scrivo domani.", "Vado ora."], ["I'll check right away.", "I'll read later.", "I'll write tomorrow.", "I'm going now."], "Esatto! Risposta solerte.", "No, significa 'I'll check right away'.", "Exactly! Prompt response.", "No, it means 'I'll check right away'."),
    ("Conferma ricevuta.", "Confirmation received.", ["Conferma ricevuta.", "Email inviata.", "File perso.", "Dati errati."], ["Confirmation received.", "Email sent.", "File lost.", "Wrong data."], "Giusto! Stato di un processo.", "No, è 'Conferma ricevuta'.", "Right! State of a process.", "No, it's 'Confirmation received'."),
    ("La policy aziendale.", "The company policy.", ["La policy aziendale.", "Il piano di studi.", "L'orario delle lezioni.", "Il regolamento scolastico."], ["The company policy.", "The study plan.", "The class schedule.", "The school regulation."], "Ottimo! Contesto lavorativo.", "No, è 'La policy aziendale'.", "Great! Work context.", "No, it's 'The company policy'."),
    ("Ho visto l'email ieri.", "I saw the email yesterday.", ["Ho visto l'email ieri.", "Ho letto il libro oggi.", "Ho scritto la nota ora.", "Ho perso la chiave poi."], ["I saw the email yesterday.", "I read the book today.", "I wrote the note now.", "I lost the key then."], "Esatto! Riferimento temporale.", "No, è 'ieri'.", "Exactly! Time reference.", "No, it's 'yesterday'."),
    ("Può rispondere entro oggi?", "Can you reply by today?", ["Può rispondere entro oggi?", "Può venire domani?", "Può chiamare ora?", "Può andare via?"], ["Can you reply by today?", "Can you come tomorrow?", "Can you call now?", "Can you go away?"], "Giusto! Richiesta di urgenza.", "No, è 'entro oggi?'.", "Right! Urgent request.", "No, it's 'by today?'."),
    ("È molto importante.", "It's very important.", ["È molto importante.", "È poco utile.", "È troppo caro.", "È molto bello."], ["It's very important.", "It's not very useful.", "It's too expensive.", "It's very beautiful."], "Perfetto! Sottolineare rilievo.", "No, significa 'important'.", "Perfect! Emphasizing importance.", "No, it means 'important'."),
    ("Non ho ancora deciso.", "I haven't decided yet.", ["Non ho ancora deciso.", "Non ho ancora finito.", "Non ho ancora visto.", "Non ho ancora detto."], ["I haven't decided yet.", "I haven't finished yet.", "I haven't seen yet.", "I haven't said yet."], "Esatto! Stato di incertezza.", "No, significa 'I haven't decided yet'.", "Exactly! State of uncertainty.", "No, it means 'I haven't decided yet'."),
    ("Scrivimi pure.", "Feel free to write to me.", ["Scrivimi pure.", "Chiamami dopo.", "Vieni qui.", "Guarda questo."], ["Feel free to write to me.", "Call me later.", "Come here.", "Look at this."], "Ottimo! Invito amichevole.", "No, è 'Scrivimi pure'.", "Great! Friendly invitation.", "No, it's 'Feel free to write to me'."),
    ("Mandami il link.", "Send me the link.", ["Mandami il link.", "Portami il file.", "Dami l'email.", "Fammi la bozza."], ["Send me the link.", "Bring me the file.", "Give me the email.", "Make me the draft."], "Esatto! Richiesta di risorsa.", "No, è 'Mandami il link'.", "Exactly! Resource request.", "No, it's 'Send me the link'."),
    ("Hai letto la bozza?", "Did you read the draft?", ["Hai letto la bozza?", "Hai visto il film?", "Hai scritto l'email?", "Hai inviato il file?"], ["Did you read the draft?", "Did you see the movie?", "Did you write the email?", "Did you send the file?"], "Giusto! Chiedere parere.", "No, è 'la bozza?'.", "Right! Asking for an opinion.", "No, it's 'the draft?'."),
    ("Clicca sull'allegato.", "Click on the attachment.", ["Clicca sull'allegato.", "Apri la porta.", "Guarda lo schermo.", "Chiudi il file."], ["Click on the attachment.", "Open the door.", "Look at the screen.", "Close the file."], "Perfetto! Istruzione tecnica.", "No, significa 'Click on the attachment'.", "Perfect! Technical instruction.", "No, it means 'Click on the attachment'."),
    ("La riunione è alle dieci.", "The meeting is at ten.", ["La riunione è alle dieci.", "La lezione è alle nove.", "Il pranzo è a mezzogiorno.", "La cena è alle otto."], ["The meeting is at ten.", "The lesson is at nine.", "The lunch is at noon.", "The dinner is at eight."], "Esatto! Orario di lavoro.", "No, è 'alle dieci'.", "Exactly! Work time.", "No, it's 'at ten'."),
    ("Serve una risposta.", "A response is needed.", ["Serve una risposta.", "Manca un file.", "C'è un problema.", "Va tutto bene."], ["A response is needed.", "A file is missing.", "There is a problem.", "Everything is fine."], "Giusto! Necessità di feedback.", "No, significa 'A response is needed'.", "Right! Need for feedback.", "No, it means 'A response is needed'."),
    ("Tutto chiaro?", "Everything clear?", ["Tutto chiaro?", "Tutto pronto?", "Tutto fatto?", "Tutto vero?"], ["Everything clear?", "Everything ready?", "Everything done?", "Everything true?"], "Ottimo! Chiedere conferma.", "No, è 'Tutto chiaro?'.", "Great! Asking for confirmation.", "No, it's 'Everything clear?'."),
    ("Ci sono novità?", "Any news?", ["Ci sono novità?", "Ci sono problemi?", "Ci sono file?", "Ci sono amici?"], ["Any news?", "Any problems?", "Any files?", "Any friends?"], "Esatto! Chiedere aggiornamenti.", "No, significa 'Any news?'.", "Exactly! Asking for updates.", "No, it means 'Any news?'."),
    ("Nessuna novità.", "No news.", ["Nessuna novità.", "Qualche novità.", "Molte novità.", "Troppe novità."], ["No news.", "Some news.", "Many news.", "Too many news."], "Giusto! Risposta negativa.", "No, è 'Nessuna novità'.", "Right! Negative response.", "No, it's 'No news'."),
    ("Sono in ferie.", "I'm on vacation.", ["Sono in ferie.", "Sono in ufficio.", "Sono a casa.", "Sono in riunione."], ["I'm on vacation.", "I'm in the office.", "I'm at home.", "I'm in a meeting."], "Perfetto! Assenza dal lavoro.", "No, significa 'on vacation'.", "Perfect! Absence from work.", "No, it means 'on vacation'."),
    ("Ufficio acquisti.", "Purchasing office.", ["Ufficio acquisti.", "Ufficio tecnico.", "Ufficio vendite.", "Ufficio personale."], ["Purchasing office.", "Technical office.", "Sales office.", "Personnel office."], "Esatto! Reparto aziendale.", "No, è 'Ufficio acquisti'.", "Exactly! Company department.", "No, it's 'Purchasing office'."),
    ("Segreteria studenti.", "Student office.", ["Segreteria studenti.", "Aula magna.", "Mensa scolastica.", "Biblioteca centrale."], ["Student office.", "Great hall.", "School canteen.", "Central library."], "Giusto! Contesto universitario.", "No, è 'Segreteria studenti'.", "Right! University context.", "No, it's 'Student office'."),
    ("Professore, le ho scritto.", "Professor, I wrote to you.", ["Professore, le ho scritto.", "Dottore, la chiamo.", "Amico, ti vedo.", "Capo, le parlo."], ["Professor, I wrote to you.", "Doctor, I'm calling you.", "Friend, I see you.", "Boss, I'm talking to you."], "Ottimo! Approccio formale.", "No, è 'le ho scritto'.", "Great! Formal approach.", "No, it's 'I wrote to you'."),
    ("Seguendo la nostra conversazione...", "Following our conversation...", ["Seguendo la nostra conversazione...", "Iniziando la nostra giornata...", "Finendo il nostro lavoro...", "Cambiando il nostro piano..."], ["Following our conversation...", "Starting our day...", "Finishing our work...", "Changing our plan..."], "Esatto! Chiusura/Apertura formale.", "No, è 'Seguendo la...'.", "Exactly! Formal closing/opening.", "No, it's 'Following our...'."),
    ("Come concordato...", "As agreed...", ["Come concordato...", "Come scritto...", "Come visto...", "Come detto..."], ["As agreed...", "As written...", "As seen...", "As said..."], "Giusto! Riferimento a patti presi.", "No, significa 'As agreed'.", "Right! Reference to agreements made.", "No, it means 'As agreed'."),
    ("In allegato i documenti.", "Attached are the documents.", ["In allegato i documenti.", "In ufficio i file.", "In borsa le chiavi.", "In posta le lettere."], ["Attached are the documents.", "In the office the files.", "In the bag the keys.", "In the mail the letters."], "Perfetto! Segnalare allegati.", "No, è 'In allegato...'.", "Perfect! Pointing out attachments.", "No, it's 'Attached are...'."),
    ("Grazie per l'attesa.", "Thanks for waiting.", ["Grazie per l'attesa.", "Scusa per il ritardo.", "Prego per l'aiuto.", "Ciao per sempre."], ["Thanks for waiting.", "Sorry for the delay.", "You're welcome for the help.", "Bye forever."], "Esatto! Cortesia verso il cliente.", "No, è 'l'attesa'.", "Exactly! Courtesy towards the client.", "No, it's 'waiting'."),
    ("Mi scusi ancora.", "I apologize again.", ["Mi scusi ancora.", "Mi chiami dopo.", "Mi dica ora.", "Mi porti via."], ["I apologize again.", "Call me later.", "Tell me now.", "Take me away."], "Giusto! Ribadire le scuse.", "No, significa 'I apologize again'.", "Right! Repeating apologies.", "No, it means 'I apologize again'."),
    ("Buona giornata.", "Have a good day.", ["Buona giornata.", "Buona sera.", "Buon appetito.", "Buon viaggio."], ["Have a good day.", "Good evening.", "Enjoy your meal.", "Have a good trip."], "Ottimo! Augurio comune.", "No, è 'Buona giornata'.", "Great! Common wish.", "No, it's 'Have a good day'."),
    ("Buon lavoro.", "Have a good workday.", ["Buon lavoro.", "Buon studio.", "Buon divertimento.", "Buon riposo."], ["Have a good workday.", "Good study.", "Have fun.", "Good rest."], "Esatto! Augurio ai colleghi.", "No, è 'Buon lavoro'.", "Exactly! Wish for colleagues.", "No, it's 'Have a good workday'."),
    ("A presto.", "See you soon.", ["A presto.", "A dopo.", "A domani.", "A mai più."], ["See you soon.", "See you later.", "See you tomorrow.", "See you never."], "Giusto! Saluto informale/formale.", "No, è 'A presto'.", "Right! Informal/formal greeting.", "No, it's 'See you soon'."),
    ("Cordiali saluti.", "Kind regards.", ["Cordiali saluti.", "Cari amici.", "Distinti saluti.", "Migliori auguri."], ["Kind regards.", "Dear friends.", "Yours faithfully.", "Best wishes."], "Perfetto! Variante di chiusura.", "No, è 'Cordiali saluti'.", "Perfect! Closing variant.", "No, it's 'Kind regards'."),
]

# SENTENCES
sentences_data = [
    ("Ho inviato l'email ieri ma non ho avuto risposta.", "I sent the email yesterday but I didn't get a reply.", ["Ho inviato l'email ieri ma non ho avuto risposta.", "Ho letto l'email oggi e ho dato risposta.", "Ho perso l'email ieri e non ho cercato risposta.", "Ho inviato il file ieri ma non ho avuto conferma."], ["I sent the email yesterday but I didn't get a reply.", "I read the email today and I gave a reply.", "I lost the email yesterday and I didn't look for a reply.", "I sent the file yesterday but I didn't get confirmation."], "Esatto! Una lamentela comune.", "No, significa 'I sent the email yesterday but didn't get a reply'.", "Exactly! A common complaint.", "No, it means 'I sent the email yesterday but didn't get a reply'."),
    ("Potrebbe controllare se l'email è finita nello spam?", "Could you check if the email ended up in the spam?", ["Potrebbe controllare se l'email è finita nello spam?", "Potrebbe vedere se l'email è nella posta inviata?", "Potrebbe inviare l'email di nuovo allo spam?", "Potrebbe cancellare l'email dallo spam subito?"], ["Could you check if the email ended up in the spam?", "Could you see if the email is in the sent mail?", "Could you send the email again to the spam?", "Could you delete the email from the spam right away?"], "Ottimo! Richiesta di verifica.", "No, è 'nello spam?'.", "Great! Request for verification.", "No, it's 'in the spam?'."),
    ("Ti ho mandato il file mezz'ora fa, l'hai ricevuto?", "I sent you the file half an hour ago, did you get it?", ["Ti ho mandato il file mezz'ora fa, l'hai ricevuto?", "Ti ho dato il libro un'ora fa, l'hai letto?", "Ti ho scritto l'email dieci minuti fa, l'hai vista?", "Ti ho mandato il link poco fa, l'hai aperto?"], ["I sent you the file half an hour ago, did you get it?", "I gave you the book an hour ago, did you read it?", "I wrote you the email ten minutes ago, did you see it?", "I sent you the link a while ago, did you open it?"], "Esatto! Chiedere conferma di ricezione.", "No, significa 'I sent the file half an hour ago...'.", "Exactly! Asking for confirmation of receipt.", "No, it means 'I sent the file half an hour ago...'."),
    ("Mi scusi, ho dimenticato di includere l'allegato nell'email.", "I'm sorry, I forgot to include the attachment in the email.", ["Mi scusi, ho dimenticato di includere l'allegato nell'email.", "Mi dispiace, ho scordato di scrivere l'oggetto nell'email.", "Scusami, ho mancato di inviare l'email con l'allegato.", "Mi scusi, ho dimenticato di firmare l'email alla fine."], ["I'm sorry, I forgot to include the attachment in the email.", "I'm sorry, I forgot to write the subject in the email.", "Sorry, I failed to send the email with the attachment.", "I'm sorry, I forgot to sign the email at the end."], "Giusto! Un errore classico.", "No, è 'l'allegato'.", "Right! A classic error.", "No, it's 'the attachment'."),
    ("Darei seguito volentieri alla tua richiesta entro oggi.", "I would gladly follow up on your request by today.", ["Darei seguito volentieri alla tua richiesta entro oggi.", "Inizierei volentieri la tua pratica entro domani.", "Finirei volentieri il tuo lavoro entro stasera.", "Manderei volentieri la tua email entro le sedici."], ["I would gladly follow up on your request by today.", "I would gladly start your file by tomorrow.", "I would gladly finish your work by tonight.", "I would gladly send your email by 4 PM."], "Perfetto! Disponibilità immediata.", "No, significa 'I would gladly follow up...'.", "Perfect! Immediate availability.", "No, it means 'I would gladly follow up...'."),
    ("Abbiamo verificato in magazzino e il prodotto non c'è.", "We checked the warehouse and the product isn't there.", ["Abbiamo verificato in magazzino e il prodotto non c'è.", "Abbiamo cercato in ufficio e il file non si trova.", "Abbiamo visto in negozio e il prezzo è alto.", "Abbiamo controllato in banca e il conto è vuoto."], ["We checked the warehouse and the product isn't there.", "We looked in the office and the file isn't found.", "We saw in the store and the price is high.", "We checked in the bank and the account is empty."], "Esatto! Riscontro negativo.", "No, significa 'the product isn't there'.", "Exactly! Negative feedback.", "No, it means 'the product isn't there'."),
    ("La spedizione dell'ordine 504 è prevista per domani.", "The shipping of order 504 is scheduled for tomorrow.", ["La spedizione dell'ordine 504 è prevista per domani.", "La consegna del pacco 302 è fatta per oggi.", "L'invio del file 101 è previsto per stasera.", "La vendita della merce 504 è prevista per domani."], ["The shipping of order 504 is scheduled for tomorrow.", "The delivery of package 302 is done for today.", "The sending of file 101 is scheduled for tonight.", "The sale of goods 504 is scheduled for tomorrow."], "Giusto! Informazione logistica.", "No, è 'prevista per domani'.", "Right! Logistic information.", "No, it's 'scheduled for tomorrow'."),
    ("Mi serve il tuo feedback sulla nuova policy entro domani.", "I need your feedback on the new policy by tomorrow.", ["Mi serve il tuo feedback sulla nuova policy entro domani.", "Mi serve il tuo aiuto sulla nuova bozza entro stasera.", "Mi serve il tuo parere sulla nuova riunione entro domani.", "Mi serve la tua firma sulla nuova policy entro ora."], ["I need your feedback on the new policy by tomorrow.", "I need your help on the new draft by tonight.", "I need your opinion on the new meeting by tomorrow.", "I need your signature on the new policy by now."], "Ottimo! Richiesta di collaborazione.", "No, significa 'I need your feedback...'.", "Great! Request for collaboration.", "No, it means 'I need your feedback...'."),
    ("Non preoccuparti, leggo l'email adesso e ti faccio sapere.", "Don't worry, I'm reading the email now and I'll let you know.", ["Non preoccuparti, leggo l'email adesso e ti faccio sapere.", "Non temere, scrivo l'email dopo e ti chiamo subito.", "Stai tranquillo, vedo il file ora e ti mando tutto.", "Non preoccuparti, leggo la nota poi e ti dico cosa fare."], ["Don't worry, I'm reading the email now and I'll let you know.", "Don't fear, I'm writing the email later and I'll call you right away.", "Stay calm, I'm seeing the file now and I'll send you everything.", "Don't worry, I'll read the note later and tell you what to do."], "Esatto! Rassicurazione al collega.", "No, significa 'I'm reading the email now...'.", "Exactly! Reassurance to the colleague.", "No, it means 'I'm reading the email now...'."),
    ("Ho inoltrato la tua richiesta all'ufficio competente.", "I forwarded your request to the relevant office.", ["Ho inoltrato la tua richiesta all'ufficio competente.", "Ho mandato la tua domanda all'ufficio postale.", "Ho inviato la tua nota all'ufficio tecnico.", "Ho inoltrato il tuo file all'ufficio acquisti."], ["I forwarded your request to the relevant office.", "I sent your question to the post office.", "I sent your note to the technical office.", "I forwarded your file to the purchasing office."], "Giusto! Gestione della pratica.", "No, è 'all'ufficio competente'.", "Right! Managing the file.", "No, it's 'to the relevant office'."),
    ("Potrebbe darmi una risposta definitiva entro le sedici?", "Could you give me a final answer by 4 PM?", ["Potrebbe darmi una risposta definitiva entro le sedici?", "Potrebbe dirmi una cosa importante entro le cinque?", "Potrebbe darmi un file nuovo entro le quattro?", "Potrebbe darmi una risposta breve entro le sedici?"], ["Could you give me a final answer by 4 PM?", "Could you tell me an important thing by 5 PM?", "Could you give me a new file by 4 PM?", "Could you give me a short answer by 4 PM?"], "Perfetto! Richiesta di termine ultimo.", "No, è 'entro le sedici' (4 PM).", "Perfect! Request for final deadline.", "No, it's 'by 4 PM'."),
    ("La ringrazio per la sua email e per l'interesse.", "Thank you for your email and for the interest.", ["La ringrazio per la sua email e per l'interesse.", "La scuso per la sua nota e per il ritardo.", "La prego per la sua risposta e per l'aiuto.", "La saluto per la sua email e per il tempo."], ["Thank you for your email and for the interest.", "I excuse you for your note and for the delay.", "I beg you for your answer and for the help.", "I greet you for your email and for the time."], "Esatto! Risposta formale di cortesia.", "No, è 'per l'interesse'.", "Exactly! Formal courtesy response.", "No, it's 'for the interest'."),
    ("Scusa, mi era sfuggita l'email tra i tanti messaggi.", "Sorry, I missed the email among the many messages.", ["Scusa, mi era sfuggita l'email tra i tanti messaggi.", "Scusa, ho perso l'email tra i tanti file.", "Scusa, ho cancellato l'email tra i tanti spam.", "Scusa, ho visto l'email tra i tanti avvisi."], ["Sorry, I missed the email among the many messages.", "Sorry, I lost the email among the many files.", "Sorry, I deleted the email among the many spams.", "Sorry, I saw the email among the many notices."], "Giusto! Giustificazione per il ritardo.", "No, significa 'I missed the email'.", "Right! Justification for the delay.", "No, it means 'I missed the email'."),
    ("L'oggetto dell'email era poco chiaro, per questo non l'ho aperta.", "The email subject was unclear, that's why I didn't open it.", ["L'oggetto dell'email era poco chiaro, per questo non l'ho aperta.", "Il testo dell'email era molto lungo, per questo non l'ho letto.", "Il file dell'email era troppo grande, per questo non l'ho scaricato.", "L'indirizzo dell'email era sbagliato, per questo non l'ho mandato."], ["The email subject was unclear, that's why I didn't open it.", "The email text was very long, that's why I didn't read it.", "The email file was too large, that's why I didn't download it.", "The email address was wrong, that's why I didn't send it."], "Perfetto! Spiegazione del problema.", "No, significa 'the subject was unclear'.", "Perfect! Explanation of the problem.", "No, it means 'the subject was unclear'."),
    ("Rimango in attesa di un suo gentile riscontro.", "I remain waiting for your kind feedback.", ["Rimango in attesa di un suo gentile riscontro.", "Vado in attesa di un suo pronto aiuto.", "Spero in attesa di un suo caro saluto.", "Resto in attesa di un suo nuovo file."], ["I remain waiting for your kind feedback.", "I go waiting for your prompt help.", "I hope waiting for your dear greeting.", "I stay waiting for your new file."], "Esatto! Chiusura email formale classica.", "No, è 'un suo gentile riscontro'.", "Exactly! Classic formal email closing.", "No, it's 'your kind feedback'."),
    ("Come abbiamo discusso al telefono, ecco i dettagli.", "As we discussed on the phone, here are the details.", ["Come abbiamo discusso al telefono, ecco i dettagli.", "Come abbiamo scritto in email, ecco i file.", "Come abbiamo visto in ufficio, ecco i dati.", "Come abbiamo detto in riunione, ecco le note."], ["As we discussed on the phone, here are the details.", "As we wrote in email, here are the files.", "As we saw in the office, here are the data.", "As we said in the meeting, here are the notes."], "Giusto! Riferimento a colloquio precedente.", "No, è 'al telefono'.", "Right! Reference to previous call.", "No, it's 'on the phone'."),
    ("Ti invio la bozza del progetto per suggerimenti.", "I'm sending you the project draft for suggestions.", ["Ti invio la bozza del progetto per suggerimenti.", "Ti mando la copia del file per correzioni.", "Ti do l'originale del piano per aiuti.", "Ti invio la nota del lavoro per pareri."], ["I'm sending you the project draft for suggestions.", "I'm sending you the file copy for corrections.", "I'm giving you the plan original for help.", "I'm sending you the work note for opinions."], "Ottimo! Collaborazione sul lavoro.", "No, è 'la bozza'.", "Great! Collaboration at work.", "No, it's 'the draft'."),
    ("Non dimenticare di mettere in copia il responsabile.", "Don't forget to CC the manager.", ["Non dimenticare di mettere in copia il responsabile.", "Non scordare di inviare il file al capo.", "Non dimenticare di scrivere l'oggetto al collega.", "Non scordare di allegare il file al messaggio."], ["Don't forget to CC the manager.", "Don't forget to send the file to the boss.", "Don't forget to write the subject to the colleague.", "Don't forget to attach the file to the message."], "Esatto! Istruzione per CC.", "No, è 'mettere in copia'.", "Exactly! Instruction for CC.", "No, it's 'to CC'."),
    ("Ho ricevuto la conferma dell'ordine ma mancano dati.", "I received the order confirmation but data is missing.", ["Ho ricevuto la conferma dell'ordine ma mancano dati.", "Ho visto la nota dell'acquisto ma manca il prezzo.", "Ho mandato la conferma del file ma manca il link.", "Ho perso la conferma dell'ordine e mancano le info."], ["I received the order confirmation but data is missing.", "I saw the purchase note but the price is missing.", "I sent the file confirmation but the link is missing.", "I lost the order confirmation and info is missing."], "Giusto! Segnalazione incompleta.", "No, è 'mancano dati'.", "Right! Reporting incompleteness.", "No, it's 'data is missing'."),
    ("La policy aziendale è cambiata e dobbiamo aggiornare tutto.", "The company policy has changed and we must update everything.", ["La policy aziendale è cambiata e dobbiamo aggiornare tutto.", "Il piano di studi è cambiato e dobbiamo rifare l'esame.", "L'orario è cambiato e dobbiamo venire prima.", "La legge è cambiata e dobbiamo pagare tutto."], ["The company policy has changed and we must update everything.", "The study plan has changed and we must redo the exam.", "The schedule has changed and we must come earlier.", "The law has changed and we must pay everything."], "Perfetto! Annuncio di cambiamenti.", "No, è 'La policy aziendale'.", "Perfect! Announcing changes.", "No, it's 'The company policy'."),
    ("Mi dispiace, il server ha avuto un problema ieri.", "I'm sorry, the server had a problem yesterday.", ["Mi dispiace, il server ha avuto un problema ieri.", "Scusami, il computer ha avuto un guasto oggi.", "Mi spiace, l'email ha avuto un ritardo poi.", "Scusi, il sistema ha avuto un errore ora."], ["I'm sorry, the server had a problem yesterday.", "Sorry, the computer had a breakdown today.", "I'm sorry, the email had a delay then.", "Excuse me, the system had an error now."], "Esatto! Scusa tecnica.", "No, è 'il server'.", "Exactly! Technical apology.", "No, it's 'the server'."),
    ("Se hai bisogno di informazioni, contattami pure.", "If you need information, feel free to contact me.", ["Se hai bisogno di informazioni, contattami pure.", "Se vuoi un aiuto, chiamami dopo.", "Se hai tempo ora, vediamoci qui.", "Se serve un file, mandami un link."], ["If you need information, feel free to contact me.", "If you want help, call me later.", "If you have time now, let's meet here.", "If a file is needed, send me a link."], "Giusto! Disponibilità finale.", "No, significa 'feel free to contact me'.", "Right! Final availability.", "No, it means 'feel free to contact me'."),
    ("Hai già risposto alla segreteria per l'esame?", "Have you already replied to the office for the exam?", ["Hai già risposto alla segreteria per l'esame?", "Hai già scritto al professore per la tesi?", "Hai già visto l'avviso per il corso?", "Hai già pagato la tassa per lo studio?"], ["Have you already replied to the office for the exam?", "Have you already written to the professor for the thesis?", "Have you already seen the notice for the course?", "Have you already paid the fee for the study?"], "Ottimo! Contesto accademico.", "No, è 'alla segreteria'.", "Great! Academic context.", "No, it's 'to the office'."),
    ("Il professore non ha ancora visto l'email con la tesi.", "The professor hasn't seen the email with the thesis yet.", ["Il professore non ha ancora visto l'email con la tesi.", "Il dottore non ha ancora letto la nota con i dati.", "Il capo non ha ancora firmato l'email con il piano.", "Il collega non ha ancora inoltrato l'email con il file."], ["The professor hasn't seen the email with the thesis yet.", "The doctor hasn't read the note with the data yet.", "The boss hasn't signed the email with the plan yet.", "The colleague hasn't forwarded the email with the file yet."], "Esatto! Problema di attesa in università.", "No, è 'con la tesi'.", "Exactly! Waiting problem at university.", "No, it's 'with the thesis'."),
    ("Ti ricordi di inviarmi quel link di ieri?", "Do you remember to send me that link from yesterday?", ["Ti ricordi di inviarmi quel link di ieri?", "Ti scordi di portarmi quel file di oggi?", "Ti ricordi di scrivermi quell'email di domani?", "Ti scordi di vedermi quel film di poi?"], ["Do you remember to send me that link from yesterday?", "Do you forget to bring me that file from today?", "Do you remember to write me that email from tomorrow?", "Do you forget to see me that movie from then?"], "Giusto! Promemoria informale.", "No, è 'quel link di ieri'.", "Right! Informal reminder.", "No, it's 'that link from yesterday'."),
    ("La posta in arrivo è piena e non ricevo messaggi.", "The inbox is full and I'm not receiving messages.", ["La posta in arrivo è piena e non ricevo messaggi.", "La cartella dei file è vuota e non trovo nulla.", "La borsa della spesa è piena e non porto altro.", "La classe di studio è piena e non entro oggi."], ["The inbox is full and I'm not receiving messages.", "The files folder is empty and I find nothing.", "The grocery bag is full and I carry nothing else.", "The study class is full and I'm not entering today."], "Perfetto! Problema tecnico comune.", "No, è 'piena'.", "Perfect! Common technical problem.", "No, it's 'full'."),
    ("Ho salvato l'email importante in una cartella.", "I saved the important email in a folder.", ["Ho salvato l'email importante in una cartella.", "Ho perso l'email inutile in un cestino.", "Ho inviato l'email urgente in un attimo.", "Ho letto l'email lunga in un'ora."], ["I saved the important email in a folder.", "I lost the useless email in a trash can.", "I sent the urgent email in a second.", "I read the long email in an hour."], "Esatto! Organizzazione digitale.", "No, è 'in una cartella'.", "Exactly! Digital organization.", "No, it's 'in a folder'."),
    ("Grazie per avermi segnalato l'errore nell'ultimo invio.", "Thanks for pointing out the error in the last send-out.", ["Grazie per avermi segnalato l'errore nell'ultimo invio.", "Prego per avermi detto la verità nell'ultimo file.", "Scusa per avermi fatto lo sbaglio nell'ultimo link.", "Grazie per avermi visto il problema nell'ultimo piano."], ["Thanks for pointing out the error in the last send-out.", "You're welcome for telling me the truth in the last file.", "Sorry for making me the mistake in the last link.", "Thanks for seeing the problem in the last plan."], "Giusto! Riconoscimento di un errore.", "No, è 'segnalato l'errore'.", "Right! Acknowledging an error.", "No, it's 'pointed out the error'."),
    ("Ci aggiorniamo via email appena avrò novità.", "We'll update each other via email as soon as I have news.", ["Ci aggiorniamo via email appena avrò novità.", "Ci vediamo via Zoom appena avrai tempo.", "Ci scriviamo via chat appena saremo pronti.", "Ci sentiamo via telefono appena sarò a casa."], ["We'll update each other via email as soon as I have news.", "We'll see each other via Zoom as soon as you have time.", "We'll write each other via chat as soon as we're ready.", "We'll talk via phone as soon as I'm at home."], "Ottimo! Promessa di aggiornamento.", "No, è 'appena avrò novità'.", "Great! Promise of update.", "No, it's 'as soon as I have news'."),
    ("Per favore, conferma la ricezione di questo messaggio.", "Please confirm receipt of this message.", ["Per favore, conferma la ricezione di questo messaggio.", "Per cortesia, leggi la nota di questo file.", "Per piacere, invia la bozza di questo piano.", "Per favore, cancella l'email di questo mittente."], ["Please confirm receipt of this message.", "Please read the note of this file.", "Please send the draft of this plan.", "Please delete the email of this sender."], "Esatto! Richiesta di conferma formale.", "No, è 'la ricezione'.", "Exactly! Formal confirmation request.", "No, it's 'receipt'."),
    ("Mi serve un attimo per controllare i dati nel database.", "I need a moment to check the data in the database.", ["Mi serve un attimo per controllare i dati nel database.", "Mi serve un giorno per scrivere i file nel disco.", "Mi serve un'ora per leggere le note nel foglio.", "Mi serve un secondo per vedere il link nel sito."], ["I need a moment to check the data in the database.", "I need a day to write the files on the disk.", "I need an hour to read the notes on the sheet.", "I need a second to see the link on the site."], "Giusto! Tempo per verifica tecnica.", "No, è 'nel database'.", "Right! Time for technical verification.", "No, it's 'in the database'."),
    ("L'ordine sarà evaso appena riceveremo il pagamento.", "The order will be processed as soon as we receive payment.", ["L'ordine sarà evaso appena riceveremo il pagamento.", "Il pacco sarà mandato appena vedremo l'email.", "La merce sarà venduta appena avremo lo sconto.", "Il file sarà inviato appena riceveremo la bozza."], ["The order will be processed as soon as we receive payment.", "The package will be sent as soon as we see the email.", "The goods will be sold as soon as we have the discount.", "The file will be sent as soon as we receive the draft."], "Perfetto! Procedura commerciale.", "No, è 'appena riceveremo il pagamento'.", "Perfect! Commercial procedure.", "No, it's 'as soon as we receive payment'."),
    ("Scrivo per sollecitare una risposta alla mia email.", "I am writing to urge a response to my email.", ["Scrivo per sollecitare una risposta alla mia email.", "Chiamo per chiedere un aiuto alla mia domanda.", "Vengo per dare un parere alla mia bozza.", "Scrivo per annullare una nota alla mia cartella."], ["I am writing to urge a response to my email.", "I'm calling to ask for help with my question.", "I'm coming to give an opinion on my draft.", "I'm writing to cancel a note in my folder."], "Esatto! Sollecito formale.", "No, è 'per sollecitare'.", "Exactly! Formal reminder.", "No, it's 'to urge'."),
    ("Spero di aver chiarito ogni dubbio con questa spiegazione.", "I hope I have cleared every doubt with this explanation.", ["Spero di aver chiarito ogni dubbio con questa spiegazione.", "Credo di aver perso ogni file con questa azione.", "Penso di aver visto ogni link con questa ricerca.", "Spero di aver dato ogni aiuto con questa email."], ["I hope I have cleared every doubt with this explanation.", "I believe I lost every file with this action.", "I think I saw every link with this search.", "I hope I gave every help with this email."], "Giusto! Chiusura chiarificatrice.", "No, è 'ogni dubbio'.", "Right! Clarifying closing.", "No, it's 'every doubt'."),
    ("Cordiali saluti e buon proseguimento di giornata.", "Best regards and have a good rest of the day.", ["Cordiali saluti e buon proseguimento di giornata.", "Cari amici e buona fortuna a tutti.", "Tanti auguri e felice anno nuovo.", "Distinti saluti e arrivederci a presto."], ["Best regards and have a good rest of the day.", "Dear friends and good luck to everyone.", "Best wishes and happy new year.", "Yours faithfully and see you soon."], "Ottimo! Augurio formale completo.", "No, è 'proseguimento di giornata'.", "Great! Complete formal wish.", "No, it's 'rest of the day'."),
    ("Hai visto l'avviso sulla bacheca aziendale stamattina?", "Did you see the notice on the company bulletin board this morning?", ["Hai visto l'avviso sulla bacheca aziendale stamattina?", "Hai letto il file sulla scrivania personale oggi?", "Hai scritto la nota sulla lavagna scolastica ora?", "Hai perso la chiave sulla porta dell'ufficio ieri?"], ["Did you see the notice on the company bulletin board this morning?", "Did you read the file on the personal desk today?", "Did you write the note on the school blackboard now?", "Did you lose the key on the office door yesterday?"], "Esatto! Comunicazione interna.", "No, è 'sulla bacheca aziendale'.", "Exactly! Internal communication.", "No, it's 'on the company bulletin board'."),
    ("Non riesco ad aprire l'allegato, forse il formato è errato.", "I can't open the attachment, maybe the format is wrong.", ["Non riesco ad aprire l'allegato, forse il formato è errato.", "Non posso vedere il file, forse il nome è lungo.", "Non voglio leggere l'email, forse il testo è brutto.", "Non riesco a trovare il link, forse il sito è chiuso."], ["I can't open the attachment, maybe the format is wrong.", "I can't see the file, maybe the name is long.", "I don't want to read the email, maybe the text is bad.", "I can't find the link, maybe the site is closed."], "Giusto! Problema tecnico comune.", "No, è 'il formato è errato'.", "Right! Common technical problem.", "No, it's 'the format is wrong'."),
    ("Ti ho messo in copia conoscenza nell'email al capo.", "I put you in CC in the email to the boss.", ["Ti ho messo in copia conoscenza nell'email al capo.", "Ti ho dato in regalo un libro nell'ufficio al piano.", "Ti ho visto in riunione nell'aula al centro.", "Ti ho scritto in fretta nell'email al collega."], ["I put you in CC in the email to the boss.", "I gave you a book as a gift in the office on the floor.", "I saw you in a meeting in the room in the center.", "I wrote you in a hurry in the email to the colleague."], "Perfetto! Gergo da ufficio.", "No, è 'in copia conoscenza' (CC).", "Perfect! Office jargon.", "No, it's 'in CC'."),
    ("La riunione è stata posticipata alla prossima settimana.", "The meeting has been postponed to next week.", ["La riunione è stata posticipata alla prossima settimana.", "La lezione è stata annullata per questa mattina.", "La festa è stata anticipata a domani sera.", "Il pranzo è stato spostato in un altro posto."], ["The meeting has been postponed to next week.", "The lesson has been cancelled for this morning.", "The party has been moved up to tomorrow evening.", "The lunch has been moved to another place."], "Esatto! Cambio di programma.", "No, è 'posticipata'.", "Exactly! Change of plans.", "No, it's 'postponed'."),
    ("Grazie per la collaborazione e per la tempestività.", "Thanks for the cooperation and for the promptness.", ["Grazie per la collaborazione e per la tempestività.", "Prego per l'aiuto e per la gentilezza.", "Scusa per il ritardo e per la confusione.", "Grazie per la visita e per il tempo."], ["Thanks for the cooperation and for the promptness.", "You're welcome for the help and for the kindness.", "Sorry for the delay and for the confusion.", "Thanks for the visit and for the time."], "Giusto! Ringraziamento professionale.", "No, è 'per la tempestività'.", "Right! Professional thanks.", "No, it's 'for the promptness'."),
    ("Potrebbe inoltrare questa comunicazione a tutto il team?", "Could you forward this communication to the whole team?", ["Potrebbe inoltrare questa comunicazione a tutto il team?", "Potrebbe mandare questo file a tutto l'ufficio?", "Potrebbe dare questa nota a tutti i colleghi?", "Potrebbe scrivere questa email a tutto il mondo?"], ["Could you forward this communication to the whole team?", "Could you send this file to the whole office?", "Could you give this note to all colleagues?", "Could you write this email to the whole world?"], "Perfetto! Richiesta di diffusione info.", "No, è 'inoltrare'.", "Perfect! Request to spread info.", "No, it's 'forward'."),
    ("Ho appena finito di scrivere la bozza della presentazione.", "I just finished writing the presentation draft.", ["Ho appena finito di scrivere la bozza della presentazione.", "Ho appena iniziato a leggere il libro della scuola.", "Ho appena visto di perdere la chiave della casa.", "Ho appena sentito di fare la riunione della ditta."], ["I just finished writing the presentation draft.", "I just started reading the school book.", "I just saw losing the house key.", "I just heard of having the company meeting."], "Esatto! Stato del lavoro.", "No, è 'la bozza'.", "Exactly! Work status.", "No, it's 'the draft'."),
    ("Mi servirebbe il tuo parere professionale su questo.", "I would need your professional opinion on this.", ["Mi servirebbe il tuo parere professionale su questo.", "Mi vorrebbe il tuo aiuto personale per quello.", "Mi darebbe il tuo file tecnico su tutto.", "Mi scriverebbe il tuo nome completo qui."], ["I would need your professional opinion on this.", "I would want your personal help for that.", "I would give your technical file on everything.", "I would write your full name here."], "Giusto! Richiesta di consulenza interna.", "No, è 'il tuo parere professionale'.", "Right! Request for internal consultation.", "No, it's 'your professional opinion'."),
    ("La conferma definitiva arriverà entro la fine del turno.", "The final confirmation will arrive by the end of the shift.", ["La conferma definitiva arriverà entro la fine del turno.", "La risposta breve verrà entro l'inizio della lezione.", "La nota nuova sarà entro la pausa del pranzo.", "La bozza finale andrà entro la fine del lavoro."], ["The confirmation will arrive by the end of the shift.", "The short answer will come by the start of the lesson.", "The new note will be by the lunch break.", "The final draft will go by the end of the work."], "Perfetto! Tempistica lavorativa.", "No, è 'fine del turno'.", "Perfect! Work timing.", "No, it's 'end of the shift'."),
    ("Mi scusi, ma l'email indicata non è mai arrivata.", "I'm sorry, but the indicated email never arrived.", ["Mi scusi, ma l'email indicata non è mai arrivata.", "Scusami, ma il file detto non è mai stato visto.", "Mi spiace, ma la nota scritta non è mai stata letta.", "Scusi, ma il link messo non è mai stato aperto."], ["I'm sorry, but the indicated email never arrived.", "Sorry, but the said file was never seen.", "I'm sorry, but the written note was never read.", "Excuse me, but the put link was never opened."], "Esatto! Segnalazione di mancato arrivo.", "No, è 'mai arrivata'.", "Exactly! Reporting non-arrival.", "No, it's 'never arrived'."),
    ("Ho verificato e l'errore era nel mio indirizzo email.", "I checked and the error was in my email address.", ["Ho verificato e l'errore era nel mio indirizzo email.", "Ho visto e lo sbaglio era nel tuo numero di telefono.", "Ho controllato e il problema era nel suo nome utente.", "Ho trovato e l'errore era nella mia cartella file."], ["I checked and the error was in my email address.", "I saw and the mistake was in your phone number.", "I checked and the problem was in his username.", "I found and the error was in my file folder."], "Giusto! Ammissione di errore.", "No, è 'nel mio indirizzo email'.", "Right! Admission of error.", "No, it's 'in my email address'."),
    ("Ti invio nuovamente i documenti corretti in allegato.", "I'm sending you the corrected documents again as an attachment.", ["Ti invio nuovamente i documenti corretti in allegato.", "Ti mando subito i file sbagliati in ufficio.", "Ti do ancora le note brevi in borsa.", "Ti scrivo poi le email lunghe in spam."], ["I'm sending you the corrected documents again as an attachment.", "I'm sending you the wrong files to the office immediately.", "I'm giving you the short notes in the bag again.", "I'm writing you the long emails in spam later."], "Perfetto! Correzione e rinvio.", "No, è 'in allegato'.", "Perfect! Correction and resending.", "No, it's 'as an attachment'."),
    ("Resto a disposizione per qualsiasi chiarimento in merito.", "I remain available for any clarification on the matter.", ["Resto a disposizione per qualsiasi chiarimento in merito.", "Vado a casa per ogni aiuto nel lavoro.", "Spero a disposizione per qualche nota nel file.", "Torno a disposizione per nessuno sbaglio nel link."], ["I remain available for any clarification on the matter.", "I go home for every help in the work.", "I hope available for some note in the file.", "I come back available for no mistake in the link."], "Esatto! Chiusura email formale tipica.", "No, è 'a disposizione'.", "Exactly! Typical formal email closing.", "No, it's 'available'."),
    ("Grazie per il feedback, lo terrò in considerazione.", "Thanks for the feedback, I will take it into consideration.", ["Grazie per il feedback, lo terrò in considerazione.", "Prego per la nota, la vedrò in ufficio.", "Scusa per lo sbaglio, lo farò in fretta.", "Grazie per l'aiuto, lo darò in omaggio."], ["Thanks for the feedback, I will take it into consideration.", "You're welcome for the note, I'll see it in the office.", "Sorry for the mistake, I'll do it quickly.", "Thanks for the help, I'll give it as a gift."], "Giusto! Accoglienza di suggerimenti.", "No, è 'in considerazione'.", "Right! Welcoming suggestions.", "No, it's 'into consideration'."),
    ("La scadenza per la consegna è stata fissata per venerdì.", "The delivery deadline has been set for Friday.", ["La scadenza per la consegna è stata fissata per venerdì.", "L'inizio per la vendita è stato messo per lunedì.", "La fine per lo studio è stata data per sabato.", "Il termine per l'invio è stato fatto per giovedì."], ["The delivery deadline has been set for Friday.", "The start for the sale has been put for Monday.", "The end for the study has been given for Saturday.", "The term for the sending has been made for Thursday."], "Perfetto! Definizione di scadenza.", "No, è 'venerdì'.", "Perfect! Defining a deadline.", "No, it's 'Friday'."),
    ("Hai già controllato se ci sono nuove email importanti?", "Have you already checked if there are new important emails?", ["Hai già controllato se ci sono nuove email importanti?", "Hai già visto se ci sono nuovi file grandi?", "Hai già letto se ci sono nuove note brevi?", "Hai già trovato se ci sono nuovi link utili?"], ["Have you already checked if there are new important emails?", "Have you already seen if there are new large files?", "Have you already read if there are new short notes?", "Have you already found if there are new useful links?"], "Esatto! Controllo periodico.", "No, è 'email importanti'.", "Exactly! Periodic check.", "No, it's 'important emails'."),
    ("Non ho avuto il tempo di rispondere a tutti oggi.", "I didn't have time to reply to everyone today.", ["Non ho avuto il tempo di rispondere a tutti oggi.", "Non ho avuto la voglia di scrivere a nessuno ora.", "Non ho avuto il modo di parlare a tutti ieri.", "Non ho avuto il file di dare a nessuno poi."], ["I didn't have time to reply to everyone today.", "I didn't have the desire to write to anyone now.", "I didn't have the way to talk to everyone yesterday.", "I didn't have the file to give to anyone then."], "Giusto! Giustificazione per pendenza.", "No, significa 'I didn't have time to reply'.", "Right! Justification for pending tasks.", "No, it means 'I didn't have time to reply'."),
    ("Mi scuso per la risposta tardiva alla tua richiesta.", "I apologize for the late response to your request.", ["Mi scuso per la risposta tardiva alla tua richiesta.", "Mi prego per la nota breve alla tua domanda.", "Mi scuso per il file perso alla tua nota.", "Mi scuso per il link errato alla tua email."], ["I apologize for the late response to your request.", "I beg for the short note to your question.", "I apologize for the lost file to your note.", "I apologize for the wrong link to your email."], "Perfetto! Scusa per il ritardo.", "No, è 'risposta tardiva'.", "Perfect! Apology for delay.", "No, it's 'late response'."),
    ("Ti invio il link per partecipare alla riunione online.", "I'm sending you the link to join the online meeting.", ["Ti invio il link per partecipare alla riunione online.", "Ti mando il file per vedere la lezione a casa.", "Ti do la nota per fare la festa in ufficio.", "Ti scrivo l'email per annullare il pranzo poi."], ["I'm sending you the link to join the online meeting.", "I'm sending you the file to see the lesson at home.", "I'm giving you the note to have the party in the office.", "I'm writing you the email to cancel the lunch then."], "Esatto! Invito digitale.", "No, è 'riunione online'.", "Exactly! Digital invitation.", "No, it's 'online meeting'."),
    ("Hai ricevuto la notifica della nuova policy?", "Did you receive the notification of the new policy?", ["Hai ricevuto la notifica della nuova policy?", "Hai visto l'avviso della nuova regola?", "Hai letto la bozza della nuova legge?", "Hai perso la nota della nuova ditta?"], ["Did you receive the notification of the new policy?", "Did you see the notice of the new rule?", "Did you read the draft of the new law?", "Did you lose the note of the new company?"], "Giusto! Verifica ricezione info.", "No, è 'la notifica'.", "Right! Verifying info receipt.", "No, it's 'the notification'."),
    ("Il problema è stato risolto e il sistema è attivo.", "The problem has been resolved and the system is active.", ["Il problema è stato risolto e il sistema è attivo.", "Lo sbaglio è stato fatto e il disco è rotto.", "Il guasto è stato visto e il computer è spento.", "L'errore è stato trovato e il file è perso."], ["The problem has been resolved and the system is active.", "The mistake has been made and the disk is broken.", "The breakdown has been seen and the computer is off.", "The error has been found and the file is lost."], "Perfetto! Risoluzione di un problema.", "No, è 'risolto'.", "Perfect! Resolving a problem.", "No, it's 'resolved'."),
    ("Per favore, fammi sapere se hai ricevuto tutto.", "Please, let me know if you received everything.", ["Per favore, fammi sapere se hai ricevuto tutto.", "Per cortesia, dimmi se hai visto nessuno.", "Per piacere, scrivi se hai perso qualcosa.", "Per favore, chiama se hai trovato nulla."], ["Please, let me know if you received everything.", "Please, tell me if you saw no one.", "Please, write if you lost something.", "Please, call if you found nothing."], "Esatto! Chiusura con richiesta di conferma.", "No, è 'se hai ricevuto tutto'.", "Exactly! Closing with confirmation request.", "No, it's 'if you received everything'."),
    ("Grazie ancora per il tuo aiuto prezioso in questo.", "Thanks again for your valuable help in this.", ["Grazie ancora per il tuo aiuto prezioso in questo.", "Prego ancora per il tuo file utile in quello.", "Scusa ancora per il tuo errore grave in tutto.", "Grazie ancora per il tuo tempo lungo in poi."], ["Thanks again for your valuable help in this.", "You're welcome again for your useful file in that.", "Sorry again for your serious mistake in everything.", "Thanks again for your long time then."], "Giusto! Ringraziamento sentito.", "No, è 'aiuto prezioso'.", "Right! Heartfelt thanks.", "No, it's 'valuable help'."),
    ("Ci vediamo domani per discutere i dettagli della spedizione.", "See you tomorrow to discuss the shipping details.", ["Ci vediamo domani per discutere i dettagli della spedizione.", "Ci sentiamo oggi per vedere le note del file.", "Ci scriviamo ora per fare i piani del lavoro.", "Ci vediamo poi per cancellare le bozze della ditta."], ["See you tomorrow to discuss the shipping details.", "We'll talk today to see the file notes.", "We'll write each other now to make the work plans.", "We'll see each other later to cancel the company drafts."], "Perfetto! Appuntamento di lavoro.", "No, è 'i dettagli della spedizione'.", "Perfect! Work appointment.", "No, it's 'the shipping details'."),
    ("Buona serata e a risentirci presto via email.", "Good evening and talk to you soon via email.", ["Buona serata e a risentirci presto via email.", "Buon giorno e a rivederci dopo in ufficio.", "Buona notte e a risentirci mai più via chat.", "Buon pranzo e a risentirci domani via telefono."], ["Good evening and talk to you soon via email.", "Good day and see you later in the office.", "Good night and never talk to you again via chat.", "Good lunch and talk to you tomorrow via phone."], "Esatto! Saluto finale cordiale.", "No, è 'via email'.", "Exactly! Friendly final greeting.", "No, it's 'via email'."),
]

def save_json(data, filename, type_name):
    final_data = []
    for i, item in enumerate(data):
        final_data.append(create_entry(type_name, i+1, *item))
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(final_data, f, ensure_ascii=False, indent=2)

target_dir = "src/data/exports/workstudy/email_follow_up/"
os.makedirs(target_dir, exist_ok=True)

save_json(vocab_data, os.path.join(target_dir, "workstudy_email_follow_up_vocabulary.json"), "vocabulary")
save_json(phrases_data, os.path.join(target_dir, "workstudy_email_follow_up_phrases.json"), "phrase")
save_json(sentences_data, os.path.join(target_dir, "workstudy_email_follow_up_sentences.json"), "sentence")

print("Files generated successfully.")
