
const fs = require('fs');

const diff1 = [
  { italian: 'gatto', plural: 'gatti', english: 'cat', difficulty: 1 },
  { italian: 'cane', plural: 'cani', english: 'dog', difficulty: 1 }, // Wait, cane ends in -e, that's diff 2 usually but let's stick to simple -o/-a for diff 1
  { italian: 'libro', plural: 'libri', english: 'book', difficulty: 1 },
  { italian: 'casa', plural: 'case', english: 'house', difficulty: 1 },
  { italian: 'ragazzo', plural: 'ragazzi', english: 'boy', difficulty: 1 },
  { italian: 'ragazza', plural: 'ragazze', english: 'girl', difficulty: 1 },
  { italian: 'tavolo', plural: 'tavoli', english: 'table', difficulty: 1 },
  { italian: 'sedia', plural: 'sedie', english: 'chair', difficulty: 1 },
  { italian: 'penna', plural: 'penne', english: 'pen', difficulty: 1 },
  { italian: 'mela', plural: 'mele', english: 'apple', difficulty: 1 },
  { italian: 'palla', plural: 'palle', english: 'ball', difficulty: 1 },
  { italian: 'bambino', plural: 'bambini', english: 'child (m)', difficulty: 1 },
  { italian: 'bambina', plural: 'bambine', english: 'child (f)', difficulty: 1 },
  { italian: 'amico', plural: 'amici', english: 'friend (m)', difficulty: 1 },
  { italian: 'amica', plural: 'amiche', english: 'friend (f)', difficulty: 1 },
  { italian: 'scuola', plural: 'scuole', english: 'school', difficulty: 1 },
  { italian: 'pizza', plural: 'pizze', english: 'pizza', difficulty: 1 },
  { italian: 'scarpa', plural: 'scarpe', english: 'shoe', difficulty: 1 },
  { italian: 'vestito', plural: 'vestiti', english: 'dress/suit', difficulty: 1 },
  { italian: 'occhio', plural: 'occhi', english: 'eye', difficulty: 1 },
  { italian: 'orecchio', plural: 'orecchi', english: 'ear', difficulty: 1 },
  { italian: 'braccio', plural: 'braccia', english: 'arm', difficulty: 1 }, // braccio/braccia is irregular actually
  { italian: 'mano', plural: 'mani', english: 'hand', difficulty: 1 },
  { italian: 'piede', plural: 'piedi', english: 'foot', difficulty: 1 }, // -e -> -i
  { italian: 'nonno', plural: 'nonni', english: 'grandfather', difficulty: 1 },
  { italian: 'nonna', plural: 'nonne', english: 'grandmother', difficulty: 1 },
  { italian: 'fratello', plural: 'fratelli', english: 'brother', difficulty: 1 },
  { italian: 'sorella', plural: 'sorelle', english: 'sister', difficulty: 1 },
  { italian: 'zio', plural: 'zie', english: 'uncle', difficulty: 1 }, // Wait zio/zii
  { italian: 'zia', plural: 'zie', english: 'aunt', difficulty: 1 },
  { italian: 'medico', plural: 'medici', english: 'doctor', difficulty: 1 },
  { italian: 'albero', plural: 'alberi', english: 'tree', difficulty: 1 },
  { italian: 'fiore', plural: 'fiori', english: 'flower', difficulty: 1 },
  { italian: 'tazza', plural: 'tazze', english: 'cup', difficulty: 1 },
  { italian: 'piatto', plural: 'piatti', english: 'plate', difficulty: 1 },
  { italian: 'finestra', plural: 'finestre', english: 'window', difficulty: 1 },
  { italian: 'porta', plural: 'porte', english: 'door', difficulty: 1 },
].slice(0, 34);

// Re-adjusting to ensure strict patterns for Diff 1
const strictDiff1 = [
  { italian: 'gatto', plural: 'gatti', english: 'cat', difficulty: 1 },
  { italian: 'libro', plural: 'libri', english: 'book', difficulty: 1 },
  { italian: 'casa', plural: 'case', english: 'house', difficulty: 1 },
  { italian: 'ragazzo', plural: 'ragazzi', english: 'boy', difficulty: 1 },
  { italian: 'ragazza', plural: 'ragazze', english: 'girl', difficulty: 1 },
  { italian: 'tavolo', plural: 'tavoli', english: 'table', difficulty: 1 },
  { italian: 'sedia', plural: 'sedie', english: 'chair', difficulty: 1 },
  { italian: 'penna', plural: 'penne', english: 'pen', difficulty: 1 },
  { italian: 'mela', plural: 'mele', english: 'apple', difficulty: 1 },
  { italian: 'palla', plural: 'palle', english: 'ball', difficulty: 1 },
  { italian: 'bambino', plural: 'bambini', english: 'child (m)', difficulty: 1 },
  { italian: 'bambina', plural: 'bambine', english: 'child (f)', difficulty: 1 },
  { italian: 'scuola', plural: 'scuole', english: 'school', difficulty: 1 },
  { italian: 'pizza', plural: 'pizze', english: 'pizza', difficulty: 1 },
  { italian: 'scarpa', plural: 'scarpe', english: 'shoe', difficulty: 1 },
  { italian: 'vestito', plural: 'vestiti', english: 'dress/suit', difficulty: 1 },
  { italian: 'nonno', plural: 'nonni', english: 'grandfather', difficulty: 1 },
  { italian: 'nonna', plural: 'nonne', english: 'grandmother', difficulty: 1 },
  { italian: 'fratello', plural: 'fratelli', english: 'brother', difficulty: 1 },
  { italian: 'sorella', plural: 'sorelle', english: 'sister', difficulty: 1 },
  { italian: 'zia', plural: 'zie', english: 'aunt', difficulty: 1 },
  { italian: 'albero', plural: 'alberi', english: 'tree', difficulty: 1 },
  { italian: 'tazza', plural: 'tazze', english: 'cup', difficulty: 1 },
  { italian: 'piatto', plural: 'piatti', english: 'plate', difficulty: 1 },
  { italian: 'finestra', plural: 'finestre', english: 'window', difficulty: 1 },
  { italian: 'porta', plural: 'porte', english: 'door', difficulty: 1 },
  { italian: 'quaderno', plural: 'quaderni', english: 'notebook', difficulty: 1 },
  { italian: 'macchina', plural: 'macchine', english: 'car', difficulty: 1 },
  { italian: 'bottiglia', plural: 'bottiglie', english: 'bottle', difficulty: 1 },
  { italian: 'foglietto', plural: 'foglietti', english: 'small sheet of paper', difficulty: 1 },
  { italian: 'letto', plural: 'letti', english: 'bed', difficulty: 1 },
  { italian: 'borsa', plural: 'borse', english: 'bag', difficulty: 1 },
  { italian: 'pacco', plural: 'pacchi', english: 'package', difficulty: 1 },
  { italian: 'gioco', plural: 'giochi', english: 'game', difficulty: 1 },
];

const diff2 = [
  { italian: 'cane', plural: 'cani', english: 'dog', difficulty: 2 },
  { italian: 'fiore', plural: 'fiori', english: 'flower', difficulty: 2 },
  { italian: 'piede', plural: 'piedi', english: 'foot', difficulty: 2 },
  { italian: 'ponte', plural: 'ponti', english: 'bridge', difficulty: 2 },
  { italian: 'notte', plural: 'notti', english: 'night', difficulty: 2 },
  { italian: 'chiave', plural: 'chiavi', english: 'key', difficulty: 2 },
  { italian: 'mare', plural: 'mari', english: 'sea', difficulty: 2 },
  { italian: 'padre', plural: 'padri', english: 'father', difficulty: 2 },
  { italian: 'madre', plural: 'madri', english: 'mother', difficulty: 2 },
  { italian: 'nome', plural: 'nomi', english: 'name', difficulty: 2 },
  { italian: 'voce', plural: 'voci', english: 'voice', difficulty: 2 },
  { italian: 'luce', plural: 'luci', english: 'light', difficulty: 2 },
  { italian: 'cane', plural: 'cani', english: 'dog', difficulty: 2 },
  { italian: 'bicchiere', plural: 'bicchieri', english: 'glass', difficulty: 2 },
  { italian: 'ristorante', plural: 'ristoranti', english: 'restaurant', difficulty: 2 },
  { italian: 'studente', plural: 'studenti', english: 'student', difficulty: 2 },
  { italian: 'insegnante', plural: 'insegnanti', english: 'teacher', difficulty: 2 },
  { italian: 'stazione', plural: 'stazioni', english: 'station', difficulty: 2 },
  { italian: 'colazione', plural: 'colazioni', english: 'breakfast', difficulty: 2 },
  { italian: 'lezione', plural: 'lezioni', english: 'lesson', difficulty: 2 },
  { italian: 'canzone', plural: 'canzoni', english: 'song', difficulty: 2 },
  { italian: 'estate', plural: 'estati', english: 'summer', difficulty: 2 },
  { italian: 'nazione', plural: 'nazioni', english: 'nation', difficulty: 2 },
  { italian: 'situazione', plural: 'situazioni', english: 'situation', difficulty: 2 },
  { italian: 'informazione', plural: 'informazioni', english: 'information', difficulty: 2 },
  { italian: 'televisione', plural: 'televisioni', english: 'television', difficulty: 2 },
  { italian: 'attore', plural: 'attori', english: 'actor', difficulty: 2 },
  { italian: 'autore', plural: 'autori', english: 'author', difficulty: 2 },
  { italian: 'dolore', plural: 'dolori', english: 'pain', difficulty: 2 },
  { italian: 'colore', plural: 'colori', english: 'color', difficulty: 2 },
  { italian: 'errore', plural: 'errori', english: 'error', difficulty: 2 },
  { italian: 'ordine', plural: 'ordini', english: 'order', difficulty: 2 },
  { italian: 'esame', plural: 'esami', english: 'exam', difficulty: 2 },
];

const diff3 = [
  { italian: 'uomo', plural: 'uomini', english: 'man', difficulty: 3 },
  { italian: 'uovo', plural: 'uova', english: 'egg', difficulty: 3 },
  { italian: 'dito', plural: 'dita', english: 'finger', difficulty: 3 },
  { italian: 'braccio', plural: 'braccia', english: 'arm', difficulty: 3 },
  { italian: 'ginocchio', plural: 'ginocchia', english: 'knee', difficulty: 3 },
  { italian: 'sopracciglio', plural: 'sopracciglia', english: 'eyebrow', difficulty: 3 },
  { italian: 'labbro', plural: 'labbra', english: 'lip', difficulty: 3 },
  { italian: 'muro', plural: 'mura', english: 'wall (of a city)', difficulty: 3 },
  { italian: 'osso', plural: 'ossa', english: 'bone', difficulty: 3 },
  { italian: 'paio', plural: 'paia', english: 'pair', difficulty: 3 },
  { italian: 'migliaio', plural: 'migliaia', english: 'thousand', difficulty: 3 },
  { italian: 'centinaio', plural: 'centinaia', english: 'hundred', difficulty: 3 },
  { italian: 'sport', plural: 'sport', english: 'sport', difficulty: 3 },
  { italian: 'film', plural: 'film', english: 'film', difficulty: 3 },
  { italian: 'bar', plural: 'bar', english: 'bar', difficulty: 3 },
  { italian: 'computer', plural: 'computer', english: 'computer', difficulty: 3 },
  { italian: 'caffè', plural: 'caffè', english: 'coffee', difficulty: 3 },
  { italian: 'città', plural: 'città', english: 'city', difficulty: 3 },
  { italian: 'università', plural: 'università', english: 'university', difficulty: 3 },
  { italian: 'tabù', plural: 'tabù', english: 'taboo', difficulty: 3 },
  { italian: 'virtù', plural: 'virtù', english: 'virtue', difficulty: 3 },
  { italian: 're', plural: 're', english: 'king', difficulty: 3 },
  { italian: 'specie', plural: 'specie', english: 'species', difficulty: 3 },
  { italian: 'serie', plural: 'serie', english: 'series', difficulty: 3 },
  { italian: 'crisi', plural: 'crisi', english: 'crisis', difficulty: 3 },
  { italian: 'tesi', plural: 'tesi', english: 'thesis', difficulty: 3 },
  { italian: 'analisi', plural: 'analisi', english: 'analysis', difficulty: 3 },
  { italian: 'foto', plural: 'foto', english: 'photo', difficulty: 3 },
  { italian: 'auto', plural: 'auto', english: 'car (short)', difficulty: 3 },
  { italian: 'moto', plural: 'moto', english: 'motorcycle', difficulty: 3 },
  { italian: 'cinema', plural: 'cinema', english: 'cinema', difficulty: 3 },
  { italian: 'problema', plural: 'problemi', english: 'problem', difficulty: 3 }, // -a -> -i
  { italian: 'tema', plural: 'temi', english: 'theme', difficulty: 3 },
];

const allWords = [...strictDiff1, ...diff2, ...diff3];
console.log('Total words:', allWords.length);
fs.writeFileSync('src/data/pluralWords.json', JSON.stringify(allWords, null, 2));
