import json
import os

translations = {
    "accettano": "they accept",
    "accordo": "agreement",
    "adesso": "now",
    "aeroporto": "airport",
    "aiutarla": "to help you",
    "aiuto": "help",
    "alcune": "some",
    "all": "to the",
    "alla": "to the",
    "allo": "to the",
    "alloggerà": "you will stay",
    "alloggerò": "I will stay",
    "allora": "then",
    "anche": "also",
    "ancora": "still",
    "andare": "to go",
    "andiamo": "let's go",
    "arrivare": "to arrive",
    "arrivata": "arrived",
    "arrivederci": "goodbye",
    "arriverà": "will arrive",
    "arrivino": "they arrive",
    "arte": "art",
    "aspetterò": "I will wait",
    "aspetto": "I wait",
    "assicurazione": "insurance",
    "attaccata": "attached",
    "autobus": "bus",
    "automatica": "automatic",
    "bagaglio": "luggage",
    "bene": "well",
    "benvenuto": "welcome",
    "biglietteria": "ticket office",
    "biglietti": "tickets",
    "biglietto": "ticket",
    "binario": "platform",
    "bisogna": "it is necessary",
    "bisogno": "need",
    "blu": "blue",
    "buon": "good",
    "buona": "good",
    "buongiorno": "good morning",
    "capito": "understood",
    "caricare": "to load",
    "carrelli": "trolleys",
    "carrello": "trolley",
    "carta": "card",
    "centro": "center",
    "cercherò": "I will look for",
    "certamente": "certainly",
    "che": "that",
    "checkin": "check-in",
    "chiamata": "call",
    "chiameremo": "we will call",
    "circa": "about",
    "città": "city",
    "colore": "color",
    "come": "how",
    "comprare": "to buy",
    "comprarli": "to buy them",
    "con": "with",
    "contanti": "cash",
    "convalidano": "they validate",
    "convalidarlo": "to validate it",
    "copia": "copy",
    "costa": "it costs",
    "credito": "credit",
    "dal": "from the",
    "dato": "given",
    "davanti": "in front",
    "del": "of the",
    "della": "of the",
    "delle": "of the",
    "destro": "right",
    "deve": "one must",
    "dichiarare": "to declare",
    "dieci": "ten",
    "dipende": "it depends",
    "dispiace": "sorry",
    "dobbiamo": "we must",
    "dogana": "customs",
    "dopo": "after",
    "dove": "where",
    "durante": "during",
    "ecco": "here is",
    "eccola": "here it is",
    "eccoli": "here they are",
    "effetti": "effects",
    "entrambi": "both",
    "entro": "within",
    "era": "was",
    "etichetta": "tag",
    "euro": "euros",
    "europa": "Europe",
    "express": "express",
    "famiglia": "family",
    "favore": "favor",
    "gentile": "kind",
    "gialle": "yellow",
    "giornata": "day",
    "giorni": "days",
    "giusto": "right",
    "grande": "big",
    "gratuiti": "free",
    "grazie": "thank you",
    "guardare": "to look",
    "hanno": "they have",
    "hotel": "hotel",
    "imbarco": "boarding",
    "indicazioni": "directions",
    "indirizzo": "address",
    "informazioni": "information",
    "ingresso": "entrance",
    "iniziato": "started",
    "inizio": "beginning",
    "intenzione": "intention",
    "interessante": "interesting",
    "invece": "instead",
    "italia": "Italy",
    "jfk": "JFK",
    "lasciarmi": "to leave me",
    "lei": "you",
    "leonardo": "Leonardo",
    "lontano": "far",
    "macchinette": "machines",
    "maggio": "May",
    "marca": "brand",
    "meno": "less",
    "metta": "put",
    "mette": "it takes",
    "mia": "my",
    "mille": "thousand",
    "minuti": "minutes",
    "mio": "my",
    "mobili": "mobile",
    "modello": "model",
    "modo": "way",
    "molti": "many",
    "molto": "very",
    "motivi": "reasons",
    "muoversi": "to move",
    "nastro": "belt",
    "navetta": "shuttle",
    "nazionale": "national",
    "nera": "black",
    "new": "New",
    "noi": "us",
    "nome": "name",
    "non": "not",
    "nostre": "our",
    "nulla": "nothing",
    "numero": "number",
    "nuovo": "new",
    "oggi": "today",
    "ogni": "every",
    "ora": "hour",
    "ore": "hours",
    "ottima": "excellent",
    "ottimo": "great",
    "otto": "eight",
    "paese": "country",
    "pagare": "to pay",
    "parte": "leaves",
    "passaporto": "passport",
    "pensa": "thinks",
    "per": "for",
    "perfetto": "perfect",
    "permanenza": "stay",
    "personali": "personal",
    "pesante": "heavy",
    "piano": "floor",
    "piccola": "small",
    "più": "more",
    "pollice": "thumb",
    "posso": "I can",
    "preferisco": "I prefer",
    "prego": "you're welcome",
    "prenda": "take",
    "prenderò": "I will take",
    "presso": "at",
    "presto": "soon",
    "prima": "before",
    "proprio": "really",
    "pure": "also",
    "purtroppo": "unfortunately",
    "può": "one can",
    "qual": "which",
    "qualcosa": "something",
    "quando": "when",
    "quanto": "how much",
    "questo": "this",
    "qui": "here",
    "quindici": "fifteen",
    "rapporto": "report",
    "regola": "rule",
    "ricevuta": "receipt",
    "ricordi": "remember",
    "rigido": "rigid",
    "rimanere": "to stay",
    "rimango": "I stay",
    "ritorno": "return",
    "roma": "Rome",
    "rossa": "red",
    "salire": "to go up",
    "samsonite": "Samsonite",
    "sanitaria": "sanitary",
    "scale": "stairs",
    "scanner": "scanner",
    "scelta": "choice",
    "schermo": "screen",
    "scopo": "purpose",
    "scuro": "dark",
    "scusi": "excuse me",
    "secondo": "according to",
    "segua": "follow",
    "serve": "it serves",
    "sicuramente": "surely",
    "smarrimento": "loss",
    "solito": "usual",
    "solo": "only",
    "sono": "I am",
    "speriamo": "let's hope",
    "sportello": "counter",
    "stato": "been",
    "stazione": "station",
    "sua": "your",
    "sui": "on the",
    "sul": "on the",
    "sulla": "on the",
    "sullo": "on the",
    "suo": "your",
    "superiore": "upper",
    "telefono": "telephone",
    "tempo": "time",
    "termini": "Termini",
    "traffico": "traffic",
    "trasporti": "transport",
    "treno": "train",
    "trenta": "thirty",
    "turismo": "tourism",
    "tutta": "all",
    "tutte": "all",
    "tutto": "everything",
    "una": "one",
    "usarli": "to use them",
    "uscita": "exit",
    "vacanza": "holiday",
    "valida": "valid",
    "valigia": "suitcase",
    "valigie": "suitcases",
    "vedo": "I see",
    "veloce": "fast",
    "venti": "twenty",
    "verdi": "green",
    "verso": "towards",
    "via": "way",
    "viaggia": "travels",
    "viaggio": "trip",
    "vicino": "near",
    "visitare": "to visit",
    "volo": "flight",
    "vostra": "your",
    "york": "York",
    "zona": "zone"
}

def main():
    path = 'src/data/exports/travel/airport_arrival/travel_airport_arrival_vocabulary.json'
    with open(path, 'r', encoding='utf-8') as f:
        vocab = json.load(f)
    
    for item in vocab:
        word = item['italian']
        if word in translations:
            item['english'] = translations[word]
        elif not item['english']:
            print(f"Missing translation for: {word}")
            
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    main()
