import json
import os

file_path = 'src/data/exports/shopping/returning_an_item/shopping_returning_an_item_vocabulary.json'
with open(file_path, 'r', encoding='utf-8') as f:
    vocab = json.load(f)

translations = {
    'abbastanza': 'enough',
    'abbiamo': 'we have',
    'abbiate': 'you have (subjunctive/formal)',
    'accetto': 'I accept',
    'acquisto': 'purchase',
    'aggiornato': 'updated',
    'agli': 'to the',
    'aiutarla': 'to help you (formal)',
    'aiutarti': 'to help you',
    'aiuto': 'help',
    'alla': 'to the',
    'allora': 'then',
    'altra': 'another',
    'altre': 'others',
    'altri': 'others',
    'amari': 'bitter',
    'amaro': 'bitter',
    'anche': 'also',
    'ancora': 'still',
    'appetito': 'appetite',
    'approccio': 'approach',
    'aperto': 'open',
    'aperti': 'open',
    'area': 'area',
    'arrivederci': 'goodbye',
    'articolo': 'item',
    'articoli': 'items',
    'aspettare': 'to wait',
    'aspetto': 'I wait',
    'attaccate': 'attached',
    'auguro': 'I wish',
    'avanti': 'forward',
    'avere': 'to have',
    'avete': 'you have',
    'azienda': 'company',
    'aziendale': 'company-wide',
    'bagno': 'bath / swim',
    'basta': 'it is enough',
    'bastano': 'they are enough',
    'bene': 'well',
    'benissimo': 'very well',
    'bicicletta': 'bicycle',
    'blu': 'blue',
    'buona': 'good',
    'buon': 'good',
    'buongiorno': 'good morning',
    'buono': 'voucher / good',
    'buoni': 'vouchers / good',
    'buco': 'hole',
    'buchi': 'holes',
    'camerini': 'fitting rooms',
    'camicia': 'shirt',
    'cambiare': 'to change',
    'cambio': 'exchange',
    'cane': 'dog',
    'cani': 'dogs',
    'cantare': 'to sing',
    'canzone': 'song',
    'capisco': 'I understand',
    'carta': 'card / paper',
    'carte': 'cards',
    'cassa': 'counter / cash desk',
    'cena': 'dinner',
    'certamente': 'certainly',
    'che': 'what / that',
    'chiara': 'clear',
    'chiare': 'clear',
    'ciao': 'hi',
    'cinema': 'cinema',
    'città': 'city',
    'colazione': 'breakfast',
    'comodo': 'comfortable / convenient',
    'comprare': 'to buy',
    'comprato': 'bought',
    'completo': 'complete',
    'con': 'with',
    'confezione': 'package / gift wrap',
    'conferma': 'confirmation',
    'consegnare': 'to deliver',
    'contanti': 'cash',
    'continuato': 'continuous',
    'controllare': 'to check',
    'controllarla': 'to check it',
    'controllo': 'I check',
    'copia': 'copy',
    'corro': 'I run',
    'corsa': 'run / race',
    'credito': 'credit',
    'cucinare': 'to cook',
    'dalle': 'from',
    'dei': 'of the',
    'deliziosa': 'delicious',
    'denaro': 'money',
    'dentro': 'inside',
    'destra': 'right',
    'deve': 'must',
    'devo': 'I must',
    'di': 'of',
    'dieci': 'ten',
    'difettosa': 'defective',
    'difettoso': 'defective',
    'differenza': 'difference',
    'diciannove': 'nineteen',
    'disponibile': 'available',
    'disponibili': 'available',
    'documento': 'document',
    'dormire': 'to sleep',
    'dove': 'where',
    'due': 'two',
    'e': 'and',
    'ecco': 'here',
    'eccolo': 'here it is',
    'eccola': 'here it is',
    'eccoli': 'here they are',
    'elettronica': 'electronic',
    'etichette': 'labels / tags',
    'fare': 'to do / to make',
    'facciamo': 'we do / we make',
    'fate': 'you (pl) do / you make',
    'ferma': 'stops',
    'fino': 'until',
    'firmare': 'to sign',
    'fiori': 'flowers',
    'fondo': 'back / bottom',
    'fortissimo': 'very loud / very strong',
    'freni': 'brakes',
    'gatti': 'cats',
    'gatto': 'cat',
    'gelato': 'ice cream',
    'gentilezza': 'kindness',
    'giornata': 'day',
    'giorni': 'days',
    'già': 'already',
    'giusta': 'right / correct',
    'grazie': 'thanks',
    'guarda': 'look',
    'guardare': 'to look',
    'guidare': 'to drive',
    'ho': 'I have',
    'ieri': 'yesterday',
    'igienica': 'hygienic / toilet',
    'imballaggio': 'packaging',
    'importo': 'amount',
    'in': 'in',
    'inconveniente': 'inconvenience',
    'indietro': 'back',
    'indossato': 'worn',
    'informazioni': 'information',
    'l': 'the',
    'la': 'the',
    'le': 'the / them',
    'li': 'them',
    'lo': 'the / it',
    'lavorativi': 'working / business',
    'letto': 'bed',
    'macchina': 'car / machine',
    'magazzino': 'warehouse / stockroom',
    'maglione': 'sweater',
    'mai': 'never',
    'mancia': 'tip',
    'mandare': 'to send',
    'mangiare': 'to eat',
    'mangiato': 'eaten',
    'manica': 'sleeve',
    'manuali': 'manuals',
    'mare': 'sea',
    'marmellata': 'jam',
    'media': 'medium',
    'medici': 'doctors',
    'mesi': 'months',
    'messaggio': 'message',
    'mettere': 'to put',
    'mezzo': 'half',
    'mi': 'me',
    'mille': 'thousand',
    'molto': 'very / a lot',
    'musica': 'music',
    'ne': 'of it',
    'negozio': 'shop / store',
    'nessun': 'no / none',
    'no': 'no',
    'non': 'not',
    'notte': 'night',
    'nove': 'nine',
    'nuova': 'new',
    'nuovamente': 'again',
    'nuovo': 'new',
    'nuotare': 'to swim',
    'offriamo': 'we offer',
    'ogni': 'every',
    'ora': 'now',
    'orario': 'schedule / time',
    'ordinare': 'to order',
    'ordine': 'order',
    'originale': 'original',
    'orologio': 'watch',
    'ospedale': 'hospital',
    'ottimo': 'excellent',
    'pacchetto': 'package',
    'pane': 'bread',
    'panini': 'sandwiches',
    'pantaloni': 'pants',
    'pari': 'equal / even',
    'parla': 'speaks',
    'partire': 'to leave / to depart',
    'pazienza': 'patience',
    'per': 'for',
    'perché': 'why / because',
    'perfetta': 'perfect',
    'perfetto': 'perfect',
    'però': 'however',
    'pesci': 'fishes',
    'pezzo': 'piece',
    'piace': 'pleases / like',
    'piatto': 'plate / dish',
    'piccolo': 'small',
    'pizza': 'pizza',
    'pomeriggio': 'afternoon',
    'possa': 'can (subjunctive)',
    'possiamo': 'we can',
    'possibile': 'possible',
    'posso': 'I can',
    'posto': 'place',
    'prego': 'you are welcome',
    'prendere': 'to take',
    'prenderla': 'to take it',
    'preparo': 'I prepare',
    'preparando': 'preparing',
    'presto': 'soon / early',
    'prezzo': 'price',
    'problema': 'problem',
    'procedere': 'to proceed',
    'prodotto': 'product',
    'prossima': 'next',
    'provare': 'to try',
    'punti': 'points / stores',
    'qualche': 'some',
    'qualsiasi': 'any',
    'quando': 'when',
    'quanto': 'how much',
    'questi': 'these',
    'questo': 'this',
    'questa': 'this',
    'qui': 'here',
    'registrato': 'registered',
    'regalo': 'gift',
    'reso': 'return',
    'resi': 'returns',
    'restituire': 'to return',
    'ricevuta': 'receipt',
    'rimborso': 'refund',
    'rimborsare': 'to refund',
    'rispetto': 'compared to',
    'rotto': 'broken',
    'rumorosi': 'noisy',
    'salati': 'salty',
    'salata': 'salty',
    'saldi': 'sales',
    'salve': 'hello',
    'sapone': 'soap',
    'sbagliato': 'wrong',
    'scaleremo': 'we will deduct',
    'scambio': 'exchange',
    'scarpe': 'shoes',
    'scatola': 'box',
    'scelta': 'choice',
    'scontrino': 'receipt',
    "scusi": "excuse me",
    "se": "if",
    "sei": "six",
    "sembra": "seems",
    "sembrano": "they seem",
    "sempre": "always",
    "senza": "without",
    "serve": "needs",
    "servono": "they need",
    "settimana": "week",
    "sicurezza": "safety",
    "si": "yes / itself",
    "siamo": "we are",
    "simpatica": "nice / pleasant",
    "simpatici": "nice / pleasant",
    "sistema": "system",
    "sognare": "to dream",
    "sogni": "dreams",
    "soldi": "money",
    "sole": "sun",
    "solo": "only",
    "sono": "I am / they are",
    "spero": "I hope",
    "spesa": "expense / shopping",
    "spenderlo": "to spend it",
    "speso": "spent",
    "spiaggia": "beach",
    "sport": "sport",
    "stampa": "print",
    "stampando": "printing",
    "stasera": "tonight",
    "stessi": "same",
    "stesso": "same",
    "stanchi": "tired",
    "stazione": "station",
    "su": "on",
    "sua": "his / her / your (formal)",
    "subito": "immediately",
    "sulla": "on the",
    "taglia": "size",
    "tecnico": "technical",
    'tempo': 'time / weather',
    'temporali': 'storms',
    'titolo': 'title',
    'totale': 'total',
    'trattasi': 'it is about',
    'transazione': 'transaction',
    'tre': 'three',
    'treno': 'train',
    'treni': 'trains',
    'troppo': 'too / too much',
    'tutto': 'all / everything',
    'un': 'a / an',
    'una': 'a / an',
    'uno': 'one / a',
    'usare': 'to use',
    'va': 'goes / okay',
    "vanno": "they go / they are okay",
    "vado": "I go",
    "vale": "is worth / is valid",
    "valido": "valid",
    "vecchi": "old",
    "vecchio": "old",
    "vediamo": "we see",
    "vederlo": "to see it",
    "vedere": "to see",
    "veloce": "fast",
    "vendita": "sale",
    "verdi": "green",
    "vestiti": "clothes",
    "viaggio": "trip",
    "vicino": "near",
    "volo": "flight",
    "vorrei": "I would like",
    "vuole": "wants",
    "zucchero": "sugar"
}

for item in vocab:
    it = item['italian'].lower()
    if it in translations:
        item['english'] = translations[it]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)
