import json

def translate_vocab(item):
    mapping = {
        "abbiamo": "we have",
        "accadde": "happened",
        "adesso": "now",
        "adoro": "I love",
        "affascinante": "fascinating",
        "affreschi": "frescoes",
        "agricoltori": "farmers",
        "aiutarmi": "help me",
        "alcune": "some",
        "all": "to the",
        "alla": "to the",
        "allora": "then",
        "altri": "others",
        "amato": "loved",
        "amo": "I love",
        "amore": "love",
        "anche": "also",
        "ancora": "still / again",
        "andiamo": "let's go",
        "anno": "year",
        "anonimo": "anonymous",
        "antica": "ancient",
        "antiche": "ancient",
        "antico": "ancient",
        "aperto": "open",
        "architetto": "architect",
        "archivio": "archive",
        "arte": "art",
        "artigiani": "artisans",
        "artista": "artist",
        "attuale": "current / relevant",
        "austero": "austere",
        "avermi": "having me",
        "avuto": "had",
        "avvertito": "warned",
        "base": "base",
        "battaglie": "battles",
        "bellissima": "beautiful",
        "bellissimi": "beautiful",
        "bello": "beautiful / nice",
        "bene": "well",
        "benvenuti": "welcome",
        "botteghe": "workshops / shops",
        "bravissimi": "very good",
        "buongiorno": "good morning",
        "campana": "bell",
        "capisce": "understands / is understood",
        "capisco": "I understand",
        "casa": "home / house",
        "centro": "center",
        "cercatore": "seeker",
        "cerimonia": "ceremony",
        "certamente": "certainly",
        "certo": "of course",
        "che": "that / which",
        "chi": "who",
        "chiesa": "church",
        "cittadina": "town / citizen",
        "cittadini": "citizens",
        "cittadino": "citizen",
        "città": "city",
        "col": "with the",
        "come": "how / like",
        "comune": "municipality / common",
        "con": "with",
        "concordo": "I agree",
        "conoscitore": "connoisseur / expert",
        "conosciuto": "known",
        "continuare": "to continue",
        "continuiamo": "let's continue",
        "cosa": "thing / what",
        "cose": "things",
        "così": "so / like this",
        "crescere": "to grow",
        "cultura": "culture",
        "curiosi": "curious",
        "curioso": "curious",
        "davvero": "really",
        "dedica": "dedication",
        "dedicati": "dedicated",
        "dei": "of the",
        "del": "of the",
        "dell": "of the",
        "della": "of the",
        "delle": "of the",
        "dice": "says",
        "dicono": "they say",
        "difficile": "difficult",
        "diritti": "rights",
        "discorsi": "speeches",
        "distruggendo": "destroying",
        "diventare": "to become",
        "diventato": "become",
        "diverso": "different",
        "documenti": "documents",
        "dodicesimo": "twelfth",
        "dopo": "after",
        "dove": "where",
        "durante": "during",
        "edifici": "buildings",
        "edificio": "building",
        "elegante": "elegant",
        "entrare": "to enter",
        "entriamo": "let's enter",
        "epoca": "era",
        "era": "was",
        "erano": "were",
        "esattamente": "exactly",
        "esercizio": "exercise",
        "esiste": "exists",
        "esprime": "expresses",
        "eventi": "events",
        "evento": "event",
        "facciamo": "we do / we make",
        "famiglia": "family",
        "famosa": "famous",
        "famosi": "famous",
        "famoso": "famous",
        "figlio": "son",
        "figurati": "don't mention it",
        "filosofo": "philosopher",
        "finestre": "windows",
        "firma": "signature / signing",
        "fondata": "founded",
        "fondatore": "founder",
        "fortuna": "luck / fortune",
        "fuoco": "fire",
        "galleria": "gallery",
        "giro": "tour / turn",
        "gli": "the",
        "governava": "ruled",
        "governo": "government",
        "grande": "great / big",
        "grazie": "thanks",
        "guarda": "look",
        "guida": "guide",
        "hanno": "they have",
        "idee": "ideas",
        "immagino": "I imagine",
        "imparare": "to learn",
        "imparato": "learned",
        "importante": "important",
        "importanti": "important",
        "incendio": "fire",
        "incredibile": "incredible",
        "ingresso": "entrance / admission",
        "iniziato": "started",
        "insegnato": "taught",
        "interessa": "interests",
        "interessante": "interesting",
        "interno": "interior",
        "invasione": "invasion",
        "iscrizione": "inscription",
        "italia": "Italy",
        "italiani": "Italians",
        "italiano": "Italian",
        "latino": "Latin",
        "lavoro": "work / job",
        "legame": "link / connection",
        "leggere": "to read",
        "leggerla": "to read it",
        "libero": "free",
        "libertà": "freedom",
        "libri": "books",
        "libro": "book",
        "locale": "local",
        "locali": "local",
        "lombardo": "Lombard",
        "loro": "their",
        "lui": "him",
        "maggio": "May",
        "mattina": "morning",
        "medievale": "medieval",
        "medievali": "medieval",
        "medioevo": "Middle Ages",
        "mese": "month",
        "moderna": "modern",
        "moderno": "modern",
        "molta": "much / a lot of",
        "molti": "many",
        "molto": "very / a lot",
        "momento": "moment",
        "monumenti": "monuments",
        "monumento": "monument",
        "morte": "death",
        "mostra": "exhibition / show",
        "muro": "wall",
        "museo": "museum",
        "musica": "music",
        "nascita": "birth",
        "nato": "born",
        "nel": "in the",
        "nell": "in the",
        "nella": "in the",
        "nobile": "noble",
        "noi": "us",
        "non": "not",
        "nostra": "our",
        "nostro": "our",
        "nuove": "new",
        "oggi": "today",
        "ogni": "every",
        "onorato": "honored",
        "ora": "now / hour",
        "originali": "original",
        "origini": "origins",
        "ospita": "houses / hosts",
        "ottimo": "excellent",
        "ottocento": "nineteenth century",
        "pace": "peace",
        "palazzi": "palaces",
        "palazzo": "palace",
        "parla": "speaks",
        "parola": "word",
        "parole": "words",
        "partecipare": "to participate",
        "particolare": "particular / unique",
        "passato": "past",
        "passeggiata": "walk",
        "per": "for",
        "perché": "why / because",
        "pericolo": "danger",
        "periodo": "period",
        "persone": "people",
        "piace": "pleases / like",
        "piacere": "pleasure",
        "piacerebbe": "would like",
        "piano": "floor / slowly",
        "piazza": "square",
        "piccola": "small",
        "piccole": "small",
        "piena": "full",
        "pietre": "stones",
        "più": "more",
        "possiamo": "we can",
        "possibile": "possible",
        "potente": "powerful",
        "potete": "you can",
        "prediletto": "favorite",
        "preferite": "you prefer",
        "prego": "you're welcome",
        "preziosi": "precious",
        "primo": "first",
        "principale": "main",
        "privata": "private",
        "problemi": "problems",
        "produzione": "production",
        "profonda": "profound / deep",
        "pronti": "ready",
        "pronto": "ready",
        "proprio": "exactly / right",
        "provare": "to try",
        "pubblico": "public",
        "pure": "also / as well",
        "qual": "what / which",
        "quale": "which",
        "quando": "when",
        "quattordicesimo": "fourteenth",
        "quel": "that",
        "quella": "that",
        "questa": "this",
        "queste": "these",
        "questi": "these",
        "questo": "this",
        "qui": "here",
        "quindi": "so / therefore",
        "raccontano": "they tell",
        "raccontato": "told",
        "racconti": "stories",
        "racconto": "story",
        "rappresentano": "they represent",
        "realtà": "reality",
        "resti": "remains",
        "ricca": "rich",
        "ricorda": "remembers / reminds",
        "ricordarlo": "to remember him",
        "risale": "dates back",
        "ritratti": "portraits",
        "romana": "Roman",
        "romanico": "Romanesque",
        "romano": "Roman",
        "sacra": "sacred",
        "sala": "room / hall",
        "salvati": "saved",
        "sapere": "to know",
        "sapete": "you know",
        "scritta": "written",
        "scritto": "written",
        "scrittore": "writer",
        "scure": "dark",
        "secoli": "centuries",
        "secolo": "century",
        "seguitemi": "follow me",
        "seguono": "they follow",
        "seicento": "seventeenth century",
        "sentirla": "to hear it",
        "settecento": "eighteenth century",
        "sezione": "section",
        "siete": "you are",
        "significa": "means",
        "significativo": "significant",
        "situazione": "situation",
        "sofferto": "suffered",
        "sola": "alone",
        "solo": "only",
        "sono": "I am / they are",
        "sorprenderà": "will surprise",
        "speciale": "special",
        "spento": "put out / extinguished",
        "spiegazione": "explanation",
        "spieghiamo": "we explain",
        "stata": "been",
        "stati": "been / states",
        "stato": "been / state",
        "statua": "statue",
        "stava": "was",
        "stile": "style",
        "storia": "history",
        "storici": "historical",
        "storico": "historical",
        "storie": "stories",
        "sua": "its / his / her",
        "successa": "happened",
        "successiva": "next",
        "successo": "happened / success",
        "sue": "its / his / her",
        "sul": "on the",
        "sulla": "on the",
        "suo": "its / his / her",
        "suoi": "its / his / her",
        "suonato": "rung / played",
        "svegliati": "woken up",
        "svolge": "takes place",
        "targa": "plaque",
        "teatro": "theater",
        "tempesta": "storm",
        "tempi": "times",
        "tessuti": "fabrics",
        "testo": "text",
        "tiene": "holds / takes place",
        "tipico": "typical",
        "tra": "between / among",
        "tradizione": "tradition",
        "tradizioni": "traditions",
        "trattato": "treaty",
        "triste": "sad",
        "turisti": "tourists",
        "tutti": "all / everyone",
        "uffici": "offices",
        "una": "a / an",
        "uomo": "man",
        "usa": "uses",
        "usiamo": "we use",
        "vecchia": "old",
        "vede": "sees",
        "vedere": "to see",
        "vederla": "to see it",
        "vedete": "you see",
        "vedi": "you see",
        "vedo": "I see",
        "verità": "truth",
        "vero": "true / right",
        "verso": "towards",
        "vicini": "neighbors",
        "vicino": "near",
        "visitare": "to visit",
        "viveva": "lived",
        "vivevano": "lived",
        "vogliamo": "we want",
        "voi": "you",
        "volentieri": "gladly",
        "volete": "you want",
        "vorrei": "I would like",
        "vostra": "your",
        "vuoi": "you want"
    }
    it = item['italian'].lower().strip()
    if it in mapping:
        item['english'] = mapping[it]
    return item

def translate_phrase(item):
    mapping = {
        "Andiamo a vedere i ritratti allora. Grazie per la spiegazione.": "Let's go see the portraits then. Thanks for the explanation.",
        "Capisco. C'è un monumento o una statua che ricorda questo evento?": "I understand. Is there a monument or a statue that commemorates this event?",
        "Capisco. Ora il palazzo è un museo o è ancora una casa privata?": "I understand. Is the palace a museum now or is it still a private house?",
        "Capisco. Questa tradizione dei tessuti esiste ancora nella città moderna?": "I understand. Does this fabric tradition still exist in the modern city?",
        "Capisco. È per questo che ha una statua così grande in piazza?": "I understand. Is that why it has such a large statue in the square?",
        "Che bello! Qual è il suo libro più conosciuto in Italia?": "How nice! What is his best-known book in Italy?",
        "Cosa rappresentano questi affreschi? Sono storie di battaglie o di pace?": "What do these frescoes represent? Are they stories of battles or of peace?",
        "Davvero? Di quale secolo è questo palazzo così particolare?": "Really? From which century is this very unique palace?",
        "Davvero? Quindi è diventato famoso solo dopo la sua morte?": "Really? So he only became famous after his death?",
        "Davvero? È un racconto incredibile! Quando è successo esattamente?": "Really? It's an incredible story! When exactly did it happen?",
        "Dove sono questi documenti? Mi piacerebbe vedere l'archivio storico.": "Where are these documents? I would like to see the historical archive.",
        "Entriamo pure! Sono pronto per vedere gli affreschi medievali.": "Let's go in! I'm ready to see the medieval frescoes.",
        "Grazie per avermi raccontato la sua storia. È un uomo davvero affascinante.": "Thanks for telling me his story. He is a truly fascinating man.",
        "Immagino. Qual era il lavoro più comune per un cittadino allora?": "I imagine. What was the most common job for a citizen back then?",
        "Incredibile! Chi viveva in questo edificio molti secoli fa?": "Incredible! Who lived in this building many centuries ago?",
        "Incredibile! È ancora possibile visitare il teatro romano oggi?": "Incredible! Is it still possible to visit the Roman theater today?",
        "Incredibile. Qual era il pericolo? Un'invasione o un incendio?": "Incredible. What was the danger? An invasion or a fire?",
        "Interessante. C'è un fondatore famoso che ha iniziato questa tradizione?": "Interesting. Is there a famous founder who started this tradition?",
        "Interessante. Mi piace molto questo stile austero ma elegante.": "Interesting. I really like this austere but elegant style.",
        "Mi piacerebbe leggerla. È scritta in italiano moderno o in latino?": "I would like to read it. Is it written in modern Italian or in Latin?",
        "Mi piacerebbe partecipare. In quale mese si svolge questa cerimonia?": "I would like to participate. In which month does this ceremony take place?",
        "No, non lo so. È un re o un artista importante del passato?": "No, I don't know. Is he a king or an important artist from the past?",
        "Ottimo! Amo vedere l'interno dei palazzi storici italiani.": "Excellent! I love seeing the interior of historical Italian palaces.",
        "Per fortuna la campana ha suonato! I documenti sono stati salvati?": "Luckily the bell rang! Were the documents saved?",
        "Possiamo entrare a vedere la galleria d'arte questa mattina?": "Can we go in to see the art gallery this morning?",
        "Si vede! Il palazzo è molto elegante. Chi era l'architetto?": "It shows! The palace is very elegant. Who was the architect?",
        "Sì, adoro i racconti delle tradizioni locali. Cosa è successo?": "Yes, I love the stories of local traditions. What happened?",
        "Sì, buongiorno. Vorrei sapere quando è stata fondata questa città.": "Yes, good morning. I would like to know when this city was founded.",
        "Sì, certamente! È un ottimo esercizio per imparare parole nuove.": "Yes, certainly! It is an excellent exercise for learning new words.",
        "Sì, ho imparato molto. Siete un ottimo conoscitore della storia!": "Yes, I learned a lot. You are a great connoisseur of history!",
        "Sì, la vedo. È una parola che si usa ancora oggi in italiano?": "Yes, I see it. Is it a word that is still used in Italian today?",
        "Sì, mi interessa molto il passato romano. Ci sono monumenti di quel periodo?": "Yes, I am very interested in the Roman past. Are there monuments from that period?",
        "Sì, sono pronto e molto curioso. Grazie ancora, guida!": "Yes, I'm ready and very curious. Thanks again, guide!",
        "Sì, vedo delle parole. Potete aiutarmi a leggere il testo antico?": "Yes, I see some words. Can you help me read the ancient text?",
        "Sì, volentieri. Il Medioevo è un secolo molto affascinante per me.": "Yes, gladly. The Middle Ages is a very fascinating century for me.",
        "Sì, volentieri. Sono curioso di vedere altri edifici storici.": "Yes, gladly. I am curious to see other historical buildings.",
        "Vero. Grazie per avermi insegnato queste cose sulla vostra città.": "True. Thanks for teaching me these things about your city.",
        "È un evento molto significativo. Quando è successa questa pace?": "It is a very significant event. When did this peace happen?",
        "È una dedica molto profonda. Era amato da tutti i cittadini?": "It is a very profound dedication. Was he loved by all the citizens?",
        "È una storia triste ma molto importante per la cultura locale.": "It is a sad story but very important for the local culture."
    }
    it = item['italian'].strip()
    if it in mapping:
        item['english'] = mapping[it]
    return item

def translate_sentence(item):
    mapping = {
        "Accadde nel 1345. Da quel momento la città ha iniziato a crescere e a diventare ricca.": "It happened in 1345. From that moment the city began to grow and become rich.",
        "Accadde nel Seicento. La città era in pericolo e la campana ha avvertito tutti i cittadini.": "It happened in the seventeenth century. The city was in danger and the bell warned all the citizens.",
        "All'interno ci sono affreschi bellissimi che raccontano eventi storici importanti.": "Inside there are beautiful frescoes that tell of important historical events.",
        "Bravissimi! Vedete la parola 'pericolo'? Significa che c'era una situazione difficile.": "Very good! Do you see the word 'pericolo'? It means there was a difficult situation.",
        "Buongiorno! Benvenuti al Museo di Storia Locale. Siete qui per imparare la storia della nostra città?": "Good morning! Welcome to the Local History Museum. Are you here to learn the history of our city?",
        "C'è una storia molto vecchia su questa chiesa e la sua campana. Vuoi sentirla?": "There is a very old story about this church and its bell. Do you want to hear it?",
        "Certo, abbiamo i resti di un antico teatro romano proprio vicino alla piazza principale.": "Of course, we have the remains of an ancient Roman theater right near the main square.",
        "Concordo. Vogliamo entrare ora o preferite continuare il giro della piazza?": "I agree. Do we want to enter now or do you prefer to continue the tour of the square?",
        "Dice: 'Al figlio prediletto, cercatore di verità'. Esprime l'amore della città per lui.": "It says: 'To the favorite son, seeker of truth'. It expresses the city's love for him.",
        "Dicono che la campana ha suonato da sola durante una grande tempesta nel passato.": "They say the bell rang by itself during a great storm in the past.",
        "Era la casa di una famiglia molto potente che governava la città nel passato.": "It was the home of a very powerful family that ruled the city in the past.",
        "Era un grande scrittore e filosofo nato qui nel Settecento. Ha scritto molti libri famosi.": "He was a great writer and philosopher born here in the eighteenth century. He wrote many famous books.",
        "Era un incendio che stava distruggendo l'archivio storico vicino alla chiesa.": "It was a fire that was destroying the historical archive near the church.",
        "Esattamente. La storia locale è piena di parole che usiamo ancora. È un legame col passato.": "Exactly. Local history is full of words we still use. It's a link to the past.",
        "Figurati! Adesso continuiamo la nostra passeggiata verso il palazzo antico. Andiamo?": "Don't mention it! Now let's continue our walk towards the ancient palace. Shall we go?",
        "Fu una nobile famiglia del quattordicesimo secolo. Abbiamo i loro ritratti nella sala successiva.": "It was a noble family from the fourteenth century. We have their portraits in the next room.",
        "Guarda questa statua al centro della piazza. È il nostro cittadino più famoso. Sapete chi è?": "Look at this statue in the center of the square. It is our most famous citizen. Do you know who it is?",
        "Guarda questo edificio con le finestre piccole. È il palazzo più antico della piazza.": "Look at this building with the small windows. It is the oldest palace in the square.",
        "Il suo libro più famoso parla della libertà e dei diritti dei cittadini. È ancora molto attuale.": "His most famous book speaks of freedom and the rights of citizens. It is still very relevant today.",
        "In quella sezione spieghiamo come vivevano i cittadini molti secoli fa. È molto diverso da oggi.": "In that section we explain how citizens lived many centuries ago. It is very different from today.",
        "In realtà, ai suoi tempi ha avuto molti problemi con il governo locale per le sue idee.": "Actually, in his time he had many problems with the local government for his ideas.",
        "L'architetto è anonimo, ma il suo stile è tipico del romanico lombardo.": "The architect is anonymous, but his style is typical of Lombard Romanesque.",
        "L'archivio è al primo piano. Abbiamo anche una mostra speciale sul Medioevo. Volete vederla?": "The archive is on the first floor. We also have a special exhibition on the Middle Ages. Do you want to see it?",
        "La nostra città ha origini molto antiche, risale all'epoca romana. È un periodo che vi interessa?": "Our city has very ancient origins, dating back to the Roman era. Is it a period that interests you?",
        "Molti erano agricoltori o artigiani. La città era famosa per la produzione di tessuti preziosi.": "Many were farmers or artisans. The city was famous for the production of precious fabrics.",
        "Oggi ospita gli uffici del comune e una piccola galleria d'arte antica.": "Today it houses the municipal offices and a small gallery of ancient art.",
        "Ogni anno facciamo una cerimonia qui per ricordarlo. È un evento con molta musica e discorsi.": "Every year we hold a ceremony here to remember him. It's an event with a lot of music and speeches.",
        "Prego! Seguitemi, la storia della nostra città vi sorprenderà. Siete pronti?": "You're welcome! Follow me, the history of our city will surprise you. Are you ready?",
        "Rappresentano la firma del trattato di pace tra la nostra città e i vicini.": "They represent the signing of the peace treaty between our city and the neighbors.",
        "Si tiene a maggio, il mese della sua nascita. È una bellissima tradizione cittadina.": "It is held in May, the month of his birth. It is a beautiful city tradition.",
        "Sì, c'è una piccola targa sul muro della chiesa con il racconto della storia.": "Yes, there is a small plaque on the church wall with the story of the event.",
        "Sì, ci sono ancora alcune piccole botteghe che seguono le antiche tradizioni. È molto bello.": "Yes, there are still some small workshops that follow the ancient traditions. It is very beautiful.",
        "Sì, esattamente. Molti monumenti sono dedicati a persone che hanno sofferto per la libertà.": "Yes, exactly. Many monuments are dedicated to people who suffered for freedom.",
        "Sì, i cittadini si sono svegliati e hanno spento il fuoco. Da allora la campana è sacra.": "Yes, the citizens woke up and put out the fire. Since then the bell has been sacred.",
        "Sì, l'ingresso è libero per i cittadini e per i turisti curiosi come voi.": "Yes, admission is free for citizens and for curious tourists like you.",
        "Sì, la città lo ha onorato nell'Ottocento con questo monumento. Vedete l'iscrizione sulla base?": "Yes, the city honored him in the nineteenth century with this monument. Do you see the inscription on the base?",
        "Sì, è aperto al pubblico. Ma qui nel museo potete vedere i documenti originali dell'epoca.": "Yes, it is open to the public. But here in the museum you can see original documents from the era.",
        "È del dodicesimo secolo. Vedi le pietre scure? Sono originali dell'epoca medievale.": "It is from the twelfth century. Do you see the dark stones? They are original from the medieval era.",
        "È in un italiano un po' antico, ma si capisce bene. Volete provare a leggerla?": "It's in a slightly ancient Italian, but it's well understood. Do you want to try reading it?",
        "È stato un piacere! Ora sapete perché questa chiesa è così importante per noi.": "It was a pleasure! Now you know why this church is so important to us."
    }
    it = item['italian'].strip()
    if it in mapping:
        item['english'] = mapping[it]
    return item

paths = {
    "vocab": "src/data/exports/culture/local_history/culture_local_history_vocabulary.json",
    "phrases": "src/data/exports/culture/local_history/culture_local_history_phrases.json",
    "sentences": "src/data/exports/culture/local_history/culture_local_history_sentences.json"
}

for key, path in paths.items():
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    if key == "vocab":
        data = [translate_vocab(item) for item in data]
    elif key == "phrases":
        data = [translate_phrase(item) for item in data]
    elif key == "sentences":
        data = [translate_sentence(item) for item in data]
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

