import json

translations = {
    'abbiamo': 'we have',
    'accompagnare': 'to accompany',
    'accordo': 'agreement',
    'acqua': 'water',
    'adesso': 'now',
    'aiuto': 'help',
    'alla': 'to the',
    'allora': 'then',
    'anche': 'also',
    'ancora': 'still/again',
    'andare': 'to go',
    'aperto': 'open',
    'apre': 'opens',
    'arrivederci': 'goodbye',
    'ascolto': 'listening',
    'aspettiamo': 'we wait',
    'atto': 'act',
    'auguro': 'I wish',
    'averne': 'to have some',
    'avete': 'you have',
    'bar': 'bar',
    'bellissimo': 'very beautiful',
    'bene': 'well',
    'bere': 'to drink',
    'biglietti': 'tickets',
    'bisogno': 'need',
    'borsa': 'bag',
    'buon': 'good',
    'buona': 'good',
    'buonasera': 'good evening',
    'buono': 'good',
    'caffè': 'coffee',
    'calma': 'calm',
    'campanello': 'bell',
    'capito': 'understood',
    'capo': 'item/garment',
    'cappotti': 'coats',
    'carta': 'card/paper',
    'cellulari': 'cell phones',
    'centro': 'center',
    'certamente': 'certainly',
    'certo': 'sure',
    'che': 'what/that',
    'chiavi': 'keys',
    'cinque': 'five',
    'cioccolatino': 'chocolate',
    'cominciare': 'to start',
    'con': 'with',
    'contenti': 'happy',
    'cosa': 'what',
    'costa': 'costs',
    'costano': 'cost (plural)',
    'costo': 'cost',
    'così': 'so/like this',
    'custodito': 'guarded',
    'dalla': 'from the',
    'dei': 'of the',
    'del': 'of the',
    'dell': 'of the',
    'desidera': 'desires',
    'desiderate': 'you (plural) desire',
    'devo': 'I must',
    'dieci': 'ten',
    'direttore': 'conductor/director',
    'divertimento': 'fun',
    'dobbiamo': 'we must',
    'dopo': 'after',
    'dove': 'where',
    'dovete': 'you must',
    'dritto': 'straight',
    'due': 'two',
    'dura': 'lasts',
    'ecco': 'here is',
    'eccoli': 'here they are',
    'emergenza': 'emergency',
    'emozione': 'emotion/excitement',
    'esattamente': 'exactly',
    'esatto': 'exact',
    'euro': 'euro',
    'fare': 'to do/make',
    'favore': 'favor',
    'fila': 'row',
    'finalmente': 'finally',
    'fine': 'end',
    'finire': 'to finish',
    'fino': 'until',
    'forte': 'strong',
    'foto': 'photo',
    'foyer': 'foyer',
    'fretta': 'hurry',
    'gentilissimo': 'very kind',
    'girare': 'to turn',
    'godetevi': 'enjoy',
    'grazie': 'thank you',
    'guardaroba': 'cloakroom',
    'guardiamo': 'we look',
    'importante': 'important',
    'inizia': 'starts',
    'iniziando': 'starting',
    'inizio': 'beginning',
    'intervallo': 'intermission',
    'lasciare': 'to leave',
    'lei': 'you (formal)',
    'mancia': 'tip',
    'meglio': 'better',
    'mentre': 'while',
    'mille': 'thousand',
    'minuti': 'minutes',
    'minuto': 'minute',
    'molto': 'very',
    'naturale': 'natural',
    'nei': 'in the',
    'nella': 'in the',
    'nelle': 'in the',
    'neri': 'black',
    'niente': 'nothing',
    'non': 'not',
    'nostra': 'our',
    'nostri': 'our',
    'numero': 'number',
    'obbligatoria': 'mandatory',
    'oggetti': 'objects',
    'ogni': 'every',
    'ombrello': 'umbrella',
    'opera': 'opera',
    'ora': 'now/hour',
    'orchestra': 'orchestra',
    'pagare': 'to pay',
    'palchi': 'boxes',
    'pausa': 'break',
    'per': 'for',
    'perdere': 'to lose',
    'perfetto': 'perfect',
    'piacere': 'pleasure',
    'piano': 'floor',
    'più': 'more',
    'platea': 'stalls',
    'poco': 'little',
    'poi': 'then',
    'portafoglio': 'wallet',
    'porto': 'I bring/carry',
    'possiamo': 'we can',
    'possibile': 'possible',
    'posso': 'I can',
    'posti': 'seats',
    'potete': 'you can',
    'preferisce': 'prefers',
    'preferisco': 'I prefer',
    'prego': 'you are welcome',
    'prendere': 'to take',
    'prenderemo': 'we will take',
    'prendo': 'I take',
    'preoccupi': 'worry',
    'presente': 'present',
    'preso': 'taken',
    'prevista': 'planned/expected',
    'prima': 'before',
    'programma': 'program',
    'pronti': 'ready',
    'proseguimento': 'continuation',
    'può': 'can',
    'qualcosa': 'something',
    'qualcuno': 'someone',
    'quando': 'when',
    'quanto': 'how much',
    'quaranta': 'forty',
    'quattro': 'four',
    'questa': 'this',
    'qui': 'here',
    'quindici': 'fifteen',
    'ragione': 'reason',
    'ricominciare': 'to start again',
    'ricordate': 'remember',
    'riprende': 'restarts',
    'ritirare': 'to collect',
    'ritiro': 'collection/retrieval',
    'ritorno': 'return',
    'sala': 'hall/room',
    'sbrigarci': 'to hurry up',
    'scale': 'stairs',
    'scusate': 'excuse me (plural)',
    'secondo': 'second',
    'sempre': 'always',
    'sentirete': 'you will hear',
    'sento': 'I feel',
    'serata': 'evening',
    'siamo': 'we are',
    'sicurezza': 'safety',
    'signori': 'gentlemen',
    'sinistra': 'left',
    'sipario': 'curtain',
    'soldi': 'money',
    'solo': 'only',
    'sono': 'they are / I am',
    'spegnere': 'to turn off',
    'spengo': 'I turn off',
    'speriamo': 'we hope',
    'spettacolo': 'show',
    'sta': 'is',
    'stasera': 'tonight',
    'stessa': 'same',
    'subito': 'immediately',
    'suonare': 'to play (instrument)',
    'suonerà': 'will ring/play',
    'superiore': 'upper',
    'tasche': 'pockets',
    'tempo': 'time',
    'torniamo': 'we return',
    'totale': 'total',
    'tra': 'between/in (time)',
    'trama': 'plot',
    'tranquillo': 'calm',
    'trova': 'finds/is located',
    'tutta': 'all',
    'tutto': 'all',
    'una': 'a',
    'uno': 'one',
    'uscire': 'to go out',
    'uscita': 'exit',
    'valore': 'value',
    'vedere': 'to see',
    'venti': 'twenty',
    'vicino': 'near',
    'video': 'video',
    'vietato': 'forbidden',
    'visto': 'seen',
    'voglio': 'I want',
    'volete': 'you want',
    'vorrei': 'I would like',
    'vostri': 'your'
}

vocab_file = 'src/data/exports/culture/theater_evening/culture_theater_evening_vocabulary.json'

with open(vocab_file, 'r') as f:
    data = json.load(f)

for item in data:
    word = item['italian']
    if word in translations:
        item['english'] = translations[word]

with open(vocab_file, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Translations applied successfully.")
