import json
import os

translations = {
  "abbastanza": "enough",
  "acqua": "water",
  "acquistare": "to buy",
  "adesso": "now",
  "affari": "business",
  "aiutarla": "help you (formal)",
  "albergo": "hotel",
  "all": "at the / to the",
  "alla": "at the / to the",
  "allora": "then",
  "altri": "others",
  "anche": "also",
  "ancora": "again / still",
  "andare": "to go",
  "andiamo": "let's go",
  "andrà": "will go",
  "andrò": "I will go",
  "angolo": "corner",
  "arriva": "arrives",
  "arrivare": "to arrive",
  "arrivati": "arrived",
  "arrivederci": "goodbye",
  "arte": "art",
  "aspettando": "waiting",
  "aspettare": "to wait",
  "atrio": "lobby / hall",
  "attraversa": "crosses",
  "attraversare": "to cross",
  "automatici": "automatic",
  "bar": "bar / cafe",
  "barre": "bars",
  "basta": "enough / just",
  "bellissimo": "very beautiful",
  "bene": "well / good",
  "biglietterie": "ticket offices",
  "biglietti": "tickets",
  "biglietto": "ticket",
  "borsa": "bag",
  "buon": "good",
  "buona": "good (feminine)",
  "buongiorno": "good morning",
  "buono": "good",
  "capisco": "I understand",
  "capito": "understood",
  "carta": "card / paper",
  "cento": "hundred",
  "centrale": "central",
  "centro": "center",
  "cercando": "looking for",
  "certamente": "certainly",
  "certo": "sure",
  "che": "what / that",
  "checkin": "check-in",
  "città": "city",
  "codice": "code",
  "come": "how / like",
  "comodo": "comfortable",
  "comprare": "to buy",
  "con": "with",
  "consiglio": "advice / I recommend",
  "continuare": "to continue",
  "continui": "continue (imperative/formal)",
  "corra": "run (formal imperative)",
  "cosa": "what / thing",
  "costa": "costs",
  "credito": "credit",
  "dal": "from the",
  "davanti": "in front of",
  "davvero": "really",
  "dei": "of the / some",
  "del": "of the",
  "dell": "of the",
  "della": "of the",
  "delle": "of the",
  "dentro": "inside",
  "desidera": "desires",
  "destinazione": "destination",
  "destra": "right",
  "deve": "must (he/she/it) / you must (formal)",
  "devo": "I must",
  "dice": "says",
  "dieci": "ten",
  "dietro": "behind",
  "distributori": "vending machines / distributors",
  "documenti": "documents",
  "domani": "tomorrow",
  "dopo": "after",
  "dov": "where",
  "dove": "where",
  "dovrò": "I will have to",
  "dritto": "straight",
  "due": "two",
  "ecco": "here is",
  "eccola": "here it is (feminine)",
  "edificio": "building",
  "entrare": "to enter",
  "esattamente": "exactly",
  "esatto": "exact",
  "euro": "euro",
  "faccia": "do/make (formal imperative)",
  "faccio": "I do / I make",
  "facile": "easy",
  "fantastici": "fantastic (plural)",
  "farò": "I will do / I will make",
  "fatica": "effort / fatigue",
  "fatto": "done / made",
  "fessura": "slot / slit",
  "figurati": "don't mention it",
  "fino": "until / up to",
  "fontana": "fountain",
  "forse": "maybe",
  "fredda": "cold",
  "frequenti": "frequent",
  "funziona": "works",
  "fuori": "outside",
  "galleria": "gallery",
  "gentilissimo": "very kind",
  "giornata": "day",
  "girare": "to turn",
  "giri": "turn (formal imperative)",
  "già": "already",
  "grand": "great / big",
  "grande": "big / great",
  "hai": "you have",
  "hanno": "they have",
  "hotel": "hotel",
  "identità": "identity",
  "indicare": "to indicate",
  "indicazioni": "directions",
  "ingresso": "entrance",
  "inserire": "to insert",
  "inserisco": "I insert",
  "inserito": "inserted",
  "isolati": "blocks",
  "lei": "you (formal) / she",
  "linea": "line",
  "locali": "local (plural)",
  "lontana": "far",
  "luce": "light",
  "lungo": "along / long",
  "macchine": "cars / machines",
  "macchinetta": "machine / vending machine",
  "male": "bad / poorly",
  "mattina": "morning",
  "meno": "less",
  "metri": "meters",
  "metta": "put (formal imperative)",
  "mezza": "half",
  "miei": "my / mine (plural)",
  "milano": "Milan",
  "mille": "thousand",
  "mio": "my / mine",
  "molte": "many (feminine plural)",
  "molto": "very / much",
  "movimento": "movement",
  "municipio": "city hall",
  "musei": "museums",
  "museo": "museum",
  "nella": "in the",
  "nessun": "no / any",
  "niente": "nothing",
  "noi": "we / us",
  "non": "not",
  "nostra": "our (feminine)",
  "nostri": "our (masculine plural)",
  "oggi": "today",
  "ogni": "every",
  "online": "online",
  "ora": "hour / now",
  "ottimo": "excellent",
  "pago": "I pay",
  "parco": "park",
  "passeggiata": "walk / stroll",
  "pedonale": "pedestrian",
  "per": "for",
  "perfetta": "perfect (feminine)",
  "perfetto": "perfect",
  "permanenza": "stay",
  "personale": "personal / staff",
  "piacere": "pleasure",
  "piazza": "square",
  "pin": "pin",
  "poi": "then",
  "ponte": "bridge",
  "porti": "bring (imperative)",
  "posso": "I can",
  "prendere": "to take",
  "presto": "early / soon",
  "prima": "before / first",
  "principale": "main",
  "proprio": "really / own",
  "può": "can (he/she/it) / you can (formal)",
  "qualcosa": "something",
  "quando": "when",
  "quanti": "how many",
  "quanto": "how much",
  "quaranta": "forty",
  "quasi": "almost",
  "quello": "that",
  "questa": "this",
  "questo": "this",
  "qui": "here",
  "rapido": "fast / quick",
  "reception": "reception",
  "regionale": "regional",
  "riesce": "manages / succeeds",
  "rilassarsi": "to relax",
  "riposare": "to rest",
  "roma": "Rome",
  "salvatore": "savior",
  "salve": "hello",
  "sarà": "will be",
  "sbriga": "hurries up",
  "scansionare": "to scan",
  "scegliere": "to choose",
  "scelto": "chosen",
  "schermo": "screen",
  "sconto": "discount",
  "sei": "you are / six",
  "selezionato": "selected",
  "selezioni": "select (formal imperative)",
  "semaforo": "traffic light",
  "sembra": "seems",
  "serve": "needs",
  "sete": "thirst",
  "settimana": "week",
  "siamo": "we are",
  "sicuramente": "surely",
  "sicuro": "sure",
  "sinistra": "left",
  "sola": "alone (feminine)",
  "soldi": "money",
  "solo": "only",
  "sono": "they are / I am",
  "soprattutto": "especially",
  "sotto": "under",
  "spero": "I hope",
  "sta": "stays / is",
  "stampa": "print / press",
  "stanco": "tired",
  "stato": "been / state",
  "sto": "I stay / I am",
  "storico": "historical",
  "strada": "street",
  "studenti": "students",
  "sua": "his/her/your (formal)",
  "sul": "on the",
  "sulla": "on the",
  "sullo": "on the",
  "suo": "his/her/your (formal)",
  "tempo": "time",
  "tessera": "card",
  "tipo": "type",
  "traffico": "traffic",
  "treni": "trains",
  "treno": "train",
  "trenta": "thirty",
  "troppo": "too much",
  "tutti": "all / everyone",
  "tutto": "everything",
  "una": "a / an",
  "uno": "one / a",
  "usare": "to use",
  "uso": "I use / use",
  "vacanza": "vacation",
  "vada": "go (formal imperative)",
  "valigia": "suitcase",
  "vecchio": "old",
  "vedere": "to see",
  "vedo": "I see",
  "vedrà": "will see (you formal)",
  "veloce": "fast",
  "verso": "towards",
  "viaggio": "trip",
  "vicina": "near",
  "voglio": "I want",
  "volevo": "I wanted",
  "vuole": "wants",
  "A sinistra alla farmacia. E poi devo continuare dritto?": "Left at the pharmacy. And then should I continue straight?",
  "Capito. Sa se ci sono treni frequenti per Milano oggi?": "Understood. Do you know if there are frequent trains to Milan today?",
  "Codice inserito. Sto aspettando la stampa del biglietto.": "Code inserted. I am waiting for the ticket to print.",
  "Devo arrivare all'albergo, è qui vicino a noi sulla strada.": "I need to get to the hotel, it's near us here on the street.",
  "Dritto per cento metri. E dopo il parco cosa faccio?": "Straight for a hundred meters. And after the park what do I do?",
  "Dritto per questa strada, ho capito. E poi?": "Straight down this street, I understand. And then?",
  "Due isolati dritto. La stazione è sulla destra o sinistra?": "Two blocks straight. Is the station on the right or left?",
  "Fatto! Lo schermo dice trenta euro. Adesso pago?": "Done! The screen says thirty euros. Do I pay now?",
  "Girare a destra al semaforo. È prima del ponte?": "Turn right at the traffic light. Is it before the bridge?",
  "Grazie ancora per l'aiuto con la valigia pesante. Arrivederci!": "Thanks again for the help with the heavy suitcase. Goodbye!",
  "Grazie mille per l'aiuto! È stato molto gentile. Arrivederci.": "Thank you so much for your help! You've been very kind. Goodbye.",
  "Grazie mille, è stato gentilissimo. Buona giornata a lei!": "Thank you so much, you've been very kind. Have a good day!",
  "Grazie, buona giornata anche a lei! Arrivederci.": "Thank you, have a good day to you too! Goodbye.",
  "La galleria d'arte? È lontana dal centro storico della città?": "The art gallery? Is it far from the historic city center?",
  "Le dieci e mezza! Allora devo davvero andare veloce. Grazie!": "Half past ten! Then I really have to go fast. Thank you!",
  "Meno male. Ci sono i distributori automatici fuori?": "Thank goodness. Are there vending machines outside?",
  "Meno male. Grazie mille per le indicazioni, molto gentile.": "Thank goodness. Thank you very much for the directions, very kind.",
  "No grazie, oggi voglio solo riposare in piazza un po'.": "No thanks, today I just want to rest in the square a bit.",
  "No grazie, va bene fino all'ingresso principale. Sei un salvatore.": "No thanks, up to the main entrance is fine. You are a lifesaver.",
  "No, lo farò ora alla reception con i miei documenti di identità.": "No, I'll do it now at the reception with my ID documents.",
  "No, ma uso la mappa sul mio telefono. Funziona bene.": "No, but I use the map on my phone. It works well.",
  "Ogni ora, ottimo. Non dovrò aspettare troppo tempo allora.": "Every hour, excellent. I won't have to wait too long then.",
  "Ottimo, ci andrò sicuramente domani mattina presto con la luce.": "Excellent, I will definitely go there tomorrow morning early with the light.",
  "Ottimo, ho proprio sete. Hanno l'acqua fredda lì?": "Excellent, I'm really thirsty. Do they have cold water there?",
  "Perfetto, sulla destra. Devo attraversare la strada per entrare?": "Perfect, on the right. Do I need to cross the street to enter?",
  "Selezionato. Adesso devo indicare il numero di biglietti?": "Selected. Now do I have to indicate the number of tickets?",
  "Solo un biglietto per me, per favore. C'è lo sconto per studenti?": "Just one ticket for me, please. Is there a student discount?",
  "Sono in vacanza per una settimana. Volevo vedere i musei locali.": "I am on vacation for a week. I wanted to see the local museums.",
  "Spero di sì, sono davvero stanco dopo questo lungo viaggio in treno.": "I hope so, I am really tired after this long train trip.",
  "Sì, eccola qui. La devo inserire nella macchinetta?": "Yes, here it is. Do I have to insert it in the machine?",
  "Sì, farò attenzione. Ci sono molte macchine in centro?": "Yes, I will be careful. Are there many cars in the center?",
  "Sì, grazie. Non so come comprare un biglietto.": "Yes, thanks. I don't know how to buy a ticket.",
  "Sì, grazie. Questa borsa è molto pesante per me da sola.": "Yes, thanks. This bag is very heavy for me alone.",
  "Sì, proprio quello. Sei molto gentile, grazie mille davvero.": "Yes, exactly that. You are very kind, thank you very much indeed.",
  "Sì, scusi. Come si arriva alla stazione dei treni?": "Yes, excuse me. How do you get to the train station?",
  "Sì, scusi. Mi sono perso. Dov'è la piazza centrale?": "Yes, excuse me. I'm lost. Where is the central square?",
  "Una fontana grande, perfetto. C'è anche un bar lì?": "A large fountain, perfect. Is there also a bar there?",
  "Uso la carta. La inserisco in questa fessura a destra?": "I use the card. Do I insert it into this slot on the right?",
  "Va bene, ho scelto Roma. E adesso cosa faccio?": "Okay, I chose Rome. And now what do I do?",
  "Voglio il treno rapido, grazie. Quanto costa il biglietto?": "I want the fast train, please. How much does the ticket cost?"
}

base_path = 'src/data/exports/miscellaneous/asking_for_help/'
prefix = 'miscellaneous_asking_for_help'
files = [
    f"{prefix}_vocabulary.json",
    f"{prefix}_phrases.json",
    f"{prefix}_sentences.json"
]

for filename in files:
    path = os.path.join(base_path, filename)
    with open(path, 'r', encoding='utf-8') as f:
        items = json.load(f)
    updated = False
    for item in items:
        if not item.get("english"):
            it = item["italian"].strip()
            if it in translations:
                item["english"] = translations[it]
                updated = True
            else:
                print(f"Missing translation for '{it}' in {filename}")
    if updated:
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(items, f, indent=2, ensure_ascii=False)
        print(f"Updated {filename}")
