import json

file_path = 'src/data/exports/culture/museum_tickets/culture_museum_tickets_vocabulary.json'

with open(file_path, 'r', encoding='utf-8') as f:
    vocab = json.load(f)

translations = {
    "v1": "enough",
    "v2": "we have",
    "v3": "now",
    "v4": "to help you",
    "v5": "help",
    "v6": "at the",
    "v7": "at the",
    "v8": "at the",
    "v9": "then",
    "v10": "else",
    "v11": "also",
    "v12": "opens",
    "v13": "we open",
    "v14": "goodbye",
    "v15": "to listen",
    "v16": "audio guide",
    "v17": "to have",
    "v18": "it's enough",
    "v19": "well",
    "v20": "welcome",
    "v21": "tickets",
    "v22": "ticket",
    "v23": "good",
    "v24": "good morning",
    "v25": "understood",
    "v26": "card",
    "v27": "certainly",
    "v28": "of course",
    "v29": "that",
    "v30": "closes",
    "v31": "closed",
    "v32": "five",
    "v33": "how",
    "v34": "buys",
    "v35": "to buy",
    "v36": "to buy it",
    "v37": "I buy",
    "v38": "with",
    "v39": "keep",
    "v40": "cash",
    "v41": "continuation",
    "v42": "costs",
    "v43": "credit",
    "v44": "from the",
    "v45": "of the",
    "v46": "of the",
    "v47": "of the",
    "v48": "of the",
    "v49": "desires",
    "v50": "right",
    "v51": "must",
    "v52": "I must",
    "v53": "nineteen",
    "v54": "seventeen",
    "v55": "document",
    "v56": "twelve",
    "v57": "tomorrow",
    "v58": "after",
    "v59": "two",
    "v60": "here is",
    "v61": "entrance",
    "v62": "euro",
    "v63": "favor",
    "v64": "end",
    "v65": "day",
    "v66": "already",
    "v67": "the",
    "v68": "thanks",
    "v69": "identity",
    "v70": "information",
    "v71": "English",
    "v72": "to start",
    "v73": "full price",
    "v74": "full price",
    "v75": "she",
    "v76": "language",
    "v77": "map",
    "v78": "my",
    "v79": "thousand",
    "v80": "my",
    "v81": "very",
    "v82": "exhibition",
    "v83": "museum",
    "v84": "rental",
    "v85": "not",
    "v86": "nine",
    "v87": "number",
    "v88": "today",
    "v89": "artwork",
    "v90": "hour",
    "v91": "hours",
    "v92": "excellent",
    "v93": "you pay",
    "v94": "I pay",
    "v95": "for",
    "v96": "perfect",
    "v97": "I can",
    "v98": "prefers",
    "v99": "you're welcome",
    "v100": "to press",
    "v101": "main",
    "v102": "can",
    "v103": "which",
    "v104": "how much",
    "v105": "here",
    "v106": "to return it",
    "v107": "return",
    "v108": "change",
    "v109": "receipt",
    "v110": "remember",
    "v111": "reduced price",
    "v112": "room",
    "v113": "rooms",
    "v114": "hello",
    "v115": "to know",
    "v116": "discount",
    "v117": "only",
    "v118": "am",
    "v119": "student",
    "v120": "students",
    "v121": "sufficient",
    "v122": "your",
    "v123": "temporary",
    "v124": "student card",
    "v125": "total",
    "v126": "thirty",
    "v127": "everything",
    "v128": "last",
    "v129": "a",
    "v130": "university",
    "v131": "one",
    "v132": "exit",
    "v133": "useful",
    "v134": "is valid",
    "v135": "to see",
    "v136": "visit",
    "v137": "to visit",
    "v138": "you",
    "v139": "you want",
    "v140": "I would like"
}

for item in vocab:
    if item['id'] in translations:
        item['english'] = translations[item['id']]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)
