import json
import os

def translate():
    base_path = "src/data/exports/travel/lost_in_a_city"
    prefix = "travel_lost_in_a_city"
    
    vocab_path = os.path.join(base_path, f"{prefix}_vocabulary.json")
    phrases_path = os.path.join(base_path, f"{prefix}_phrases.json")
    
    v_trans = {
        "abbonamenti": "subscriptions/passes",
        "abbonamento": "subscription/pass",
        "accanto": "next to",
        "aiutarla": "to help you",
        "aiuterà": "will help",
        "all": "at the",
        "alla": "at the",
        "alle": "at the (plural)",
        "allora": "then/so",
        "altro": "other/else",
        "anche": "also",
        "ancora": "again/still",
        "andare": "to go",
        "angolo": "corner",
        "apertura": "opening",
        "arrivederci": "goodbye",
        "attraversare": "to cross",
        "attraversi": "cross (imperative)",
        "attraverso": "across/through",
        "autobus": "bus",
        "bella": "beautiful",
        "bene": "well/fine",
        "biglietti": "tickets",
        "bisogno": "need",
        "buon": "good",
        "buona": "good",
        "buonasera": "good evening",
        "buongiorno": "good morning",
        "buono": "good",
        "camminare": "to walk",
        "capito": "understood",
        "carbonara": "carbonara",
        "cartello": "sign",
        "centrale": "central",
        "centro": "center",
        "cerca": "looks for",
        "cercando": "looking for",
        "cerco": "I am looking for",
        "certo": "sure/certainly",
        "che": "that/which/what",
        "chiare": "clear",
        "chiave": "key",
        "chieda": "ask (imperative)",
        "cinque": "five",
        "circa": "about/approximately",
        "città": "city",
        "comodo": "comfortable/convenient",
        "comunque": "anyway",
        "con": "with",
        "consiglio": "advice",
        "continua": "continues",
        "continui": "continue (imperative)",
        "cosa": "thing/what",
        "così": "so/like this",
        "da": "from/by",
        "danno": "they give",
        "davanti": "in front of",
        "del": "of the",
        "della": "of the",
        "deve": "must/has to",
        "di": "of",
        "dieci": "ten",
        "dietro": "behind",
        "dopo": "after",
        "dove": "where",
        "dritto": "straight",
        "e": "and",
        "è": "is",
        "ed": "and (before vowel)",
        "era": "was",
        "esatto": "exact/exactly",
        "facile": "easy",
        "famosa": "famous",
        "fermata": "stop",
        "figuri": "don't mention it",
        "fontana": "fountain",
        "gentile": "kind",
        "gentilissimo": "very kind",
        "giornata": "day",
        "giri": "turn (imperative)",
        "giro": "turn/stroll",
        "giusta": "right/correct",
        "grande": "big",
        "gratuita": "free",
        "gratuite": "free",
        "grazie": "thanks",
        "guida": "guide",
        "ho": "I have",
        "hotel": "hotel",
        "il": "the",
        "in": "in",
        "indicarmi": "show me",
        "indicazioni": "directions",
        "indirizzo": "address",
        "informazioni": "information",
        "isabella": "Isabella",
        "la": "the",
        "lì": "there",
        "le": "the (plural)",
        "lei": "you (formal)",
        "lo": "the/it",
        "lontano": "far",
        "mappa": "map",
        "mappe": "maps",
        "mario": "Mario",
        "metri": "meters",
        "metropolitana": "subway/metro",
        "mezzi": "means/public transport",
        "mille": "thousand",
        "minuti": "minutes",
        "mio": "my",
        "molte": "many",
        "molto": "very/much",
        "nazionale": "national",
        "non": "not",
        "nulla": "nothing",
        "nuovo": "new",
        "onesti": "honest",
        "ora": "now/hour",
        "orari": "schedules/hours",
        "ottima": "excellent",
        "ottimo": "great/excellent",
        "parlare": "to speak",
        "particolare": "particular",
        "passeggiata": "walk",
        "passerà": "will pass",
        "passi": "steps/pass (imperative)",
        "pasta": "pasta",
        "pazienza": "patience",
        "per": "for",
        "perderà": "will lose (oneself)",
        "perfetto": "perfect",
        "perso": "lost",
        "piace": "likes",
        "piatto": "dish",
        "piazza": "square",
        "piedi": "feet",
        "più": "more",
        "pochi": "few",
        "poi": "then",
        "popolo": "people",
        "posso": "I can",
        "postale": "postal",
        "posto": "place",
        "precise": "precise",
        "preferito": "favorite",
        "prego": "you're welcome",
        "prenda": "take (imperative)",
        "prendere": "to take",
        "preoccupi": "worry (imperative)",
        "presto": "soon",
        "prezzi": "prices",
        "prima": "before/first",
        "proprio": "just/really",
        "punto": "point",
        "pure": "also/even/freely",
        "purtroppo": "unfortunately",
        "può": "can/is able to",
        "qualcosa": "something",
        "quale": "which",
        "quanto": "how much",
        "quello": "that",
        "questa": "this",
        "questo": "this",
        "qui": "here",
        "rassicura": "reassures",
        "riferimento": "reference",
        "riposi": "rest (imperative)",
        "ristorante": "restaurant",
        "roma": "Rome",
        "salve": "hello",
        "sapere": "to know",
        "sarà": "will be",
        "sbagliare": "to make a mistake",
        "scelta": "choice",
        "scusi": "excuse me",
        "sembra": "seems",
        "sera": "evening",
        "serata": "evening",
        "sette": "seven",
        "sicura": "safe/sure",
        "significa": "means",
        "singoli": "single",
        "sinistra": "left",
        "smarrito": "lost/misplaced",
        "soli": "alone (plural)",
        "solo": "only/alone",
        "sono": "I am/they are",
        "spagna": "Spain",
        "spesso": "often",
        "stasera": "tonight",
        "stato": "been/state",
        "statue": "statues",
        "stazione": "station",
        "stia": "you are (subjunctive)",
        "sto": "I am",
        "strada": "street/road",
        "sua": "your (formal)",
        "subito": "immediately",
        "succede": "happens",
        "sulla": "on the",
        "tempo": "time",
        "tipica": "typical",
        "tram": "tram",
        "tranquillo": "calm/relaxed",
        "trattoria": "trattoria",
        "tre": "three",
        "trevi": "Trevi",
        "trova": "finds",
        "trovare": "to find",
        "troverà": "will find",
        "trovo": "I find",
        "turisti": "tourists",
        "turistici": "tourist (plural)",
        "turistico": "tourist",
        "tutte": "all",
        "tutti": "all/everyone",
        "tutto": "all/everything",
        "ufficio": "office",
        "una": "a/an",
        "usare": "to use",
        "utile": "useful",
        "vada": "go (imperative)",
        "vado": "I go",
        "vecchia": "old",
        "vede": "sees",
        "vedo": "I see",
        "vedrà": "will see",
        "veloce": "fast",
        "vendono": "they sell",
        "venti": "twenty",
        "vero": "true/real",
        "via": "street",
        "vicina": "near",
        "vicino": "near",
        "visita": "visit",
        "zona": "area",
        "cenerò": "I will have dinner",
        "certamente": "certainly",
        "chiama": "calls/is named",
        "chiesa": "church",
        "chiude": "closes",
        "come": "how/as",
        "conveniente": "convenient/affordable",
        "costa": "costs/coast",
        "costoso": "expensive",
        "dettaglio": "detail",
        "doccia": "shower",
        "edificio": "building",
        "euro": "euro",
        "famiglie": "families",
        "fanno": "they do/make",
        "favore": "favor",
        "giallo": "yellow",
        "giorni": "days",
        "gli": "the (plural)",
        "goda": "enjoy (imperative)",
        "idea": "idea",
        "lontana": "far (feminine)",
        "loro": "them/their"
    }
    
    p_trans = {
        "Ah sì, ora la vedo. È proprio lì davanti a me.": "Ah yes, now I see it. It's right there in front of me.",
        "Arrivederci e grazie ancora per la sua pazienza!": "Goodbye and thanks again for your patience!",
        "Bene, allora vado prima alla fontana e poi lì.": "Fine, then I'll go to the fountain first and then there.",
        "Davanti alla stazione e poi dritto. Ho capito.": "In front of the station and then straight. I understand.",
        "Dieci minuti dritto? Grazie, ora sono più tranquillo.": "Ten minutes straight? Thanks, now I am more at ease.",
        "Dietro la fontana? È facile da trovare allora.": "Behind the fountain? It's easy to find then.",
        "Dritto e poi a sinistra? Ho capito bene, grazie.": "Straight and then to the left? I understood correctly, thanks.",
        "Grazie ancora. Arrivederci e buona giornata!": "Thanks again. Goodbye and have a good day!",
        "Grazie ancora. Vendono anche biglietti per l'autobus lì?": "Thanks again. Do they also sell bus tickets there?",
        "Grazie di tutto, lei è stato molto gentile. Buona serata!": "Thanks for everything, you have been very kind. Good evening!",
        "Grazie mille, buona serata anche a lei! Arrivederci.": "Thanks a lot, good evening to you too! Goodbye.",
        "Grazie! C'è anche un ufficio postale qui vicino?": "Thanks! Is there also a post office nearby?",
        "Grazie! C'è un ristorante buono vicino all'hotel?": "Thanks! Is there a good restaurant near the hotel?",
        "Grazie! Ora vado a prendere la mappa e poi giro.": "Thanks! Now I'm going to get the map and then I'll turn.",
        "Grazie, vado subito a parlare con loro allora.": "Thanks, I'll go talk to them right away then.",
        "La carbonara è il mio piatto preferito! È costoso?": "Carbonara is my favorite dish! Is it expensive?",
        "No, non ho una mappa. Può indicarmi la strada?": "No, I don't have a map. Can you show me the way?",
        "No, purtroppo non lo so. È molto lontano da qui?": "No, unfortunately I don't know. Is it very far from here?",
        "Ottimo! Una mappa gratuita è proprio quello che cerco.": "Great! A free map is exactly what I'm looking for.",
        "Ottimo, la metropolitana è molto veloce a Roma.": "Great, the subway is very fast in Rome.",
        "Perfetto, allora cenerò lì stasera dopo la doccia.": "Perfect, then I'll have dinner there tonight after the shower.",
        "Perfetto. Grazie mille per le indicazioni così precise.": "Perfect. Thanks a lot for such precise directions.",
        "Piazza del Popolo, ho capito. È lontana da qui?": "Piazza del Popolo, I understand. Is it far from here?",
        "Quale piazza? Ce ne sono molte in questa zona.": "Which square? There are many in this area.",
        "Questo mi rassicura molto. Grazie per tutte le informazioni.": "This reassures me a lot. Thanks for all the information.",
        "Solo cinque minuti? Ottimo, posso camminare allora.": "Only five minutes? Great, I can walk then.",
        "Sto cercando il centro, ma non trovo la via giusta.": "I'm looking for the center, but I can't find the right street.",
        "Sì, cerco l'Hotel Roma. Mi sono perso di nuovo.": "Yes, I'm looking for Hotel Roma. I'm lost again.",
        "Sì, cerco l'ufficio informazioni. Ho bisogno di una mappa.": "Yes, I'm looking for the information office. I need a map.",
        "Sì, cerco la Fontana di Trevi. È qui vicino?": "Yes, I'm looking for the Trevi Fountain. Is it nearby?",
        "Sì, mi scusi. Mi sono perso. Non so dove sono.": "Yes, excuse me. I am lost. I don't know where I am.",
        "Sì, per favore. A che ora chiude l'ufficio?": "Yes, please. At what time does the office close?",
        "Sì, vedo il cartello. È molto vicino, grazie mille.": "Yes, I see the sign. It's very close, thanks a lot.",
        "Un abbonamento turistico sembra utile. Quanto costa?": "A tourist pass seems useful. How much does it cost?",
        "Un edificio giallo, ho capito. Grazie per il dettaglio.": "A yellow building, I understand. Thanks for the detail.",
        "Una grande piazza? Come si chiama questa piazza?": "A large square? What is the name of this square?",
        "Una trattoria tipica? Mi piace l'idea. Come si chiama?": "A typical trattoria? I like the idea. What is its name?",
        "Una vecchia chiesa? È un buon punto di riferimento.": "An old church? It's a good reference point.",
        "Va bene, attraverso la piazza e vado a destra.": "All right, I'll cross the square and go to the right.",
        "Venti euro per tre giorni? È molto conveniente.": "Twenty euros for three days? It's very convenient."
    }

    def fill_json(path, translations, is_vocab=False):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        for item in data:
            if not item.get("english"):
                it = item["italian"]
                if is_vocab:
                    it_key = it.strip("?!.,").lower()
                else:
                    it_key = it # Exact match for phrases
                
                if it_key in translations:
                    item["english"] = translations[it_key]
                elif is_vocab and it.lower() in translations:
                    item["english"] = translations[it.lower()]
                else:
                    print(f"Missing translation for: '{it}' (key: '{it_key}')")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    print("Filling vocabulary...")
    fill_json(vocab_path, v_trans, is_vocab=True)
    print("Filling phrases...")
    fill_json(phrases_path, p_trans)

if __name__ == "__main__":
    translate()
