import json

file_path = 'src/data/exports/shopping/shoe_store/shopping_shoe_store_vocabulary.json'

with open(file_path, 'r', encoding='utf-8') as f:
    vocab = json.load(f)

translations = {
    "abbiamo": "we have",
    "abbinano": "they match",
    "accettate": "you (pl) accept",
    "accettiamo": "we accept",
    "acqua": "water",
    "aiutarla": "to help you",
    "aiuto": "help",
    "alla": "to the",
    "allo": "to the",
    "allora": "then",
    "ammorbidisce": "softens",
    "ammortizzano": "they cushion",
    "anche": "also",
    "ancora": "still",
    "andare": "to go",
    "anni": "years",
    "arrivederci": "goodbye",
    "artigianale": "handcrafted",
    "aspetto": "I wait",
    "attimo": "moment",
    "avere": "to have",
    "avete": "you (pl) have",
    "avvicini": "approach / come closer",
    "bancomat": "debit card",
    "belli": "beautiful",
    "bene": "well",
    "bianche": "white",
    "blu": "blue",
    "borsa": "bag",
    "buon": "good",
    "buona": "good",
    "buonasera": "good evening",
    "buongiorno": "good morning",
    "caldi": "warm",
    "calma": "calm",
    "calza": "fits",
    "calzarli": "to put them on",
    "calze": "socks",
    "camminare": "to walk",
    "camminate": "walks",
    "capisco": "I understand",
    "capito": "understood",
    "carta": "card",
    "carte": "cards",
    "casa": "home",
    "cassa": "counter",
    "centoventi": "one hundred twenty",
    "cerca": "searches",
    "cercare": "to search",
    "cerco": "I search / I look for",
    "certamente": "certainly",
    "che": "what / that",
    "città": "city",
    "codice": "code",
    "colore": "color",
    "come": "how",
    "comode": "comfortable",
    "comodo": "comfortable",
    "con": "with",
    "consiglio": "I recommend",
    "contanti": "cash",
    "controllo": "I check",
    "costano": "they cost",
    "costare": "to cost",
    "crema": "cream",
    "credito": "credit",
    "cuoio": "leather",
    "curati": "cared for",
    "da": "from / by",
    "davanti": "in front of",
    "della": "of the",
    "delle": "of the",
    "dei": "of the",
    "devo": "I must",
    "di": "of",
    "dietro": "behind",
    "disponibile": "available",
    "dolore": "pain",
    "dove": "where",
    "dovrebbe": "should",
    "dura": "hard",
    "durano": "they last",
    "e": "and",
    "eccola": "here it is",
    "eccole": "here they are",
    "eccoli": "here they are",
    "eccolo": "here it is",
    "ecco": "here",
    "elegante": "elegant",
    "euro": "euro",
    "faccia": "do / make (subjunctive/imperative)",
    "faccio": "I do / I make",
    "fanno": "they do / they make",
    "fatto": "done",
    "fiscale": "tax / fiscal",
    "flessibile": "flexible",
    "forse": "maybe",
    "ginnastica": "gym / gymnastics",
    "giusta": "right / correct",
    "già": "already",
    "gomma": "rubber",
    "grazie": "thanks",
    "grigio": "gray",
    "ho": "I have",
    "il": "the",
    "immagino": "I imagine",
    "impermeabili": "waterproof",
    "in": "in",
    "infatti": "indeed",
    "infilare": "to slip on / to put on",
    "inserire": "to insert",
    "inserisca": "insert (subjunctive/imperative)",
    "interi": "whole",
    "interessano": "they interest",
    "invece": "instead",
    "inverno": "winter",
    "investimento": "investment",
    "l": "the",
    "la": "the",
    "lacci": "laces",
    "larghezza": "width",
    "larghe": "wide / loose",
    "largo": "wide / loose",
    "le": "them",
    "leggere": "light",
    "leggerissime": "very light",
    "lì": "there",
    "lo": "the / it",
    "lunghe": "long",
    "magari": "maybe",
    "magazzino": "warehouse / stockroom",
    "male": "bad / hurt",
    "marroni": "brown",
    "marrone": "brown",
    "meglio": "better",
    "metta": "put (subjunctive/imperative)",
    "mette": "puts",
    "metto": "I put",
    "mezza": "half",
    "mi": "me",
    "miei": "my",
    "mille": "thousand",
    "misura": "size / measure",
    "modelli": "models",
    "modello": "model",
    "molto": "very / a lot",
    "morbida": "soft",
    "né": "nor",
    "negozio": "shop / store",
    "nemmeno": "not even",
    "neri": "black",
    "nero": "black",
    "neutro": "neutral",
    "no": "no",
    "non": "not",
    "numero": "number / size",
    "numeri": "numbers / sizes",
    "offerta": "offer",
    "omaggio": "gift / free",
    "ora": "now",
    "ottima": "excellent",
    "ottime": "excellent",
    "ottimo": "excellent",
    "ottantacinque": "eighty-five",
    "paio": "pair",
    "paga": "pays",
    "pagare": "to pay",
    "pagamenti": "payments",
    "particolare": "particular",
    "parte": "part",
    "passare": "to pass",
    "passeggiata": "walk",
    "pedometro": "pedometer",
    "pelle": "leather",
    "per": "for",
    "perché": "because / why",
    "perfetta": "perfect",
    "perfette": "perfect",
    "però": "however",
    "pesanti": "heavy",
    "piace": "pleases / like",
    "piacciono": "they please / like",
    "pianta": "sole (of foot) / plant",
    "piccolo": "small",
    "piede": "foot",
    "piedi": "feet",
    "pioggia": "rain",
    "più": "more",
    "posso": "I can",
    "posta": "place",
    "prego": "you're welcome / please",
    "prezzo": "price",
    "provare": "to try on",
    "provarle": "to try them on",
    "proviamo": "let's try",
    "provo": "I try",
    "può": "can / he/she/it can",
    "qualità": "quality",
    "quanto": "how much",
    "quaranta": "forty",
    "quarantadue": "forty-two",
    "quarantaquattro": "forty-four",
    "quarantatré": "forty-three",
    "quarantuno": "forty-one",
    "quella": "that",
    "quelli": "those",
    "questa": "this",
    "queste": "these",
    "questi": "these",
    "questo": "this",
    "qui": "here",
    "resistente": "resistant",
    "resto": "change / rest",
    "ricambio": "replacement / spare",
    "ringrazio": "I thank",
    "scarpa": "shoe",
    "scarpe": "shoes",
    "scatola": "box",
    "scegliere": "to choose",
    "scelta": "choice",
    "scontrino": "receipt",
    "scuro": "dark",
    "sedermi": "to sit down",
    "sedersi": "to sit down",
    "sembrano": "they seem",
    "sente": "feels / hears",
    "sentirà": "will feel / will hear",
    "sento": "I feel / I hear",
    "serata": "evening",
    "serve": "needs / is useful",
    "sessanta": "sixty",
    "settanta": "seventy",
    "siedo": "I sit",
    "solette": "insoles",
    "solito": "usual",
    "solo": "only",
    "sono": "I am / they are",
    "specchio": "mirror",
    "spero": "I hope",
    "sportivi": "sporty / athletic",
    "spray": "spray",
    "stivali": "boots",
    "strette": "tight",
    "sua": "his / her / your (formal)",
    "subito": "immediately",
    "sue": "his / her / your (formal, pl)",
    "suola": "sole",
    "totale": "total",
    "trattata": "treated",
    "trentanove": "thirty-nine",
    "tutte": "all",
    "tutto": "all / everything",
    "ultimo": "last",
    "una": "a / an",
    "uno": "a / an / one",
    "vado": "I go",
    "vanno": "they go",
    "vedere": "to see",
    "vediamo": "let's see",
    "vengono": "they come",
    "vera": "real / true",
    "vestiti": "clothes",
    "vetrina": "window display",
    "vorrei": "I would like",
    "vuole": "wants / you (formal) want",
    "un": "a / an",
    "aiutare": "to help",
    "stretto": "tight",
    "stretta": "tight",
    "comodità": "comfort",
    "preferisce": "prefers",
    "preferisco": "I prefer",
    "prenderlo": "to take it",
    "prendo": "I take",
    "proteggere": "to protect",
    "provi": "you try",
    "punta": "toe / tip",
    "pure": "also / just / go ahead",
    "purtroppo": "unfortunately",
    "qualcosa": "something"
}

for item in vocab:
    it = item['italian'].lower()
    if it in translations:
        item['english'] = translations[it]
    else:
        # Fallback if I missed any in the manual list above
        pass

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)

