import json

file_path = 'src/data/exports/culture/historic_site/culture_historic_site_vocabulary.json'

with open(file_path, 'r', encoding='utf-8') as f:
    vocab = json.load(f)

translations = {
    "adoro": "I love",
    "aiutarla": "to help you",
    "aiuto": "help",
    "all": "at the / to the",
    "alle": "at",
    "allora": "then",
    "alternativo": "alternative",
    "altri": "other",
    "anche": "also",
    "ancora": "still / again",
    "andrò": "I will go",
    "antica": "ancient (f)",
    "antiche": "ancient (f.pl)",
    "aperta": "open (f)",
    "arancioni": "orange (pl)",
    "archeologici": "archaeological (m.pl)",
    "archeologico": "archaeological (m.sg)",
    "area": "area",
    "arrivederci": "goodbye",
    "attento": "careful",
    "attenzione": "attention",
    "audioguida": "audio guide",
    "avanti": "forward / ahead",
    "ben": "well",
    "bene": "well",
    "biglietti": "tickets",
    "biglietto": "ticket",
    "botteghino": "ticket office / box office",
    "buon": "good",
    "buona": "good (f)",
    "buongiorno": "good morning",
    "buttare": "to throw (away)",
    "camminerò": "I will walk",
    "cane": "dog",
    "capisco": "I understand",
    "capito": "understood",
    "cartelli": "signs",
    "cartello": "sign",
    "castello": "castle",
    "cento": "hundred",
    "cercherò": "I will look for",
    "certamente": "certainly",
    "certo": "sure / certainly",
    "cestini": "bins / baskets",
    "che": "that / which",
    "chiude": "it closes",
    "chiudiamo": "we close",
    "chiusa": "closed (f)",
    "cima": "top / peak",
    "circa": "about / approximately",
    "collaborazione": "cooperation",
    "con": "with",
    "continuazione": "continuation",
    "correre": "to run",
    "cortile": "courtyard",
    "costa": "it costs",
    "credo": "I believe / I think",
    "cumulativo": "combined / cumulative",
    "dalla": "from the (f)",
    "davvero": "really / truly",
    "dei": "of the (m.pl)",
    "del": "of the (m.sg)",
    "delicato": "delicate",
    "della": "of the (f.sg)",
    "delle": "of the (f.pl)",
    "desidera": "you want / would you like",
    "diciassette": "seventeen (5 PM)",
    "diciotto": "eighteen (6 PM)",
    "dietro": "behind",
    "dimentichi": "forget (subjunctive/imperative)",
    "disponibile": "available",
    "divertimento": "fun / enjoyment",
    "dodici": "twelve",
    "dove": "where",
    "due": "two",
    "ecco": "here is / here are",
    "edificio": "building",
    "esterno": "outside",
    "euro": "euro",
    "fantastico": "fantastic",
    "fare": "to do / to make",
    "farò": "I will do / I will make",
    "favore": "favor",
    "felici": "happy (pl)",
    "flash": "flash",
    "foto": "photo / photos",
    "frecce": "arrows",
    "giornata": "day",
    "goda": "enjoy (subjunctive/imperative)",
    "grande": "big / large",
    "gratuita": "free (f)",
    "grazie": "thanks",
    "guinzaglio": "leash",
    "idea": "idea",
    "igienici": "hygienic / sanitary",
    "immagino": "I imagine",
    "importante": "important",
    "include": "it includes",
    "inclusa": "included (f)",
    "incredibile": "incredible",
    "indicano": "they indicate",
    "indicazioni": "directions / indications",
    "informativi": "informative (m.pl)",
    "informativo": "informative (m.sg)",
    "informazione": "information",
    "inglese": "English",
    "ingresso": "entrance / entry",
    "inizia": "it starts",
    "intatto": "intact",
    "interessato": "interested",
    "interi": "full (pl)",
    "interno": "inside / interior",
    "leggere": "to read",
    "lei": "you (formal) / her",
    "lingue": "languages",
    "lungo": "along",
    "magnifico": "magnificent",
    "mangiare": "to eat",
    "mappa": "map",
    "medievali": "medieval (pl)",
    "meraviglia": "wonder",
    "mesi": "months",
    "mille": "thousand",
    "molta": "a lot of (f)",
    "molti": "many",
    "molto": "very / a lot",
    "mura": "walls",
    "museo": "museum",
    "nel": "in the (m.sg)",
    "nell": "in the",
    "non": "not",
    "ogni": "every / each",
    "ora": "now / hour",
    "ottimo": "great / excellent",
    "pannelli": "panels",
    "pannello": "panel",
    "panorama": "view / panorama",
    "panoramiche": "panoramic (f.pl)",
    "passeggiata": "walk",
    "peccato": "shame / pity",
    "pena": "pain / worth (in 'vale la pena')",
    "per": "for",
    "percorso": "path / route",
    "perfettamente": "perfectly",
    "perfetto": "perfect",
    "piaccia": "like (subjunctive)",
    "piccola": "small (f)",
    "picnic": "picnic",
    "pietre": "stones",
    "più": "more",
    "porta": "door / gate",
    "portano": "they lead / they carry",
    "portare": "to bring / to carry",
    "possibile": "possible",
    "posso": "I can",
    "pranzo": "lunch",
    "preferisco": "I prefer",
    "prego": "you're welcome / please",
    "prendere": "to take",
    "prendo": "I take",
    "preservare": "to preserve",
    "prezzo": "price",
    "principale": "main",
    "problema": "problem",
    "problemi": "problems",
    "proprio": "just / exactly",
    "pubblico": "public",
    "può": "he/she/it can",
    "qual": "which",
    "qualche": "some",
    "quando": "when",
    "quasi": "almost",
    "quello": "that one",
    "questa": "this (f)",
    "queste": "these (f)",
    "questo": "this (m)",
    "qui": "here",
    "regole": "rules",
    "restauro": "restoration",
    "resti": "remains",
    "riaperta": "reopened (f)",
    "ricordi": "remember (subjunctive/imperative)",
    "rifiuti": "trash / waste",
    "rimarrò": "I will stay",
    "rispetto": "I respect / respect",
    "romane": "Roman (f.pl)",
    "romani": "Roman (m.pl)",
    "romano": "Roman (m.sg)",
    "rovine": "ruins",
    "salire": "to go up / to climb",
    "sarà": "it will be",
    "scala": "staircase",
    "scale": "stairs",
    "scalini": "steps",
    "scusi": "excuse me",
    "secolo": "century",
    "segnato": "marked",
    "segua": "follow (subjunctive/imperative)",
    "seguo": "I follow",
    "sempre": "always",
    "senza": "without",
    "servizi": "services (restrooms)",
    "settore": "sector",
    "siamo": "we are",
    "sicuramente": "surely / definitely",
    "sicurezza": "safety / security",
    "sinistra": "left",
    "sito": "site",
    "solo": "only / just",
    "sono": "they are / I am",
    "spiega": "it explains",
    "stasera": "tonight",
    "stessa": "same (f)",
    "storia": "history",
    "storica": "historical (f)",
    "stretta": "narrow (f)",
    "sua": "your (formal) / his / her",
    "subito": "immediately / right away",
    "sul": "on the (m.sg)",
    "sulla": "on the (f.sg)",
    "sulle": "on the (f.pl)",
    "tardi": "late",
    "teatro": "theater",
    "tempio": "temple",
    "terra": "ground / earth",
    "terreno": "ground / land",
    "terrò": "I will keep",
    "toccare": "to touch",
    "torre": "tower",
    "tra": "between / among / in",
    "tramonto": "sunset",
    "tredicesimo": "thirteenth",
    "trenta": "thirty",
    "tutti": "all / everyone",
    "tutto": "all / everything",
    "ultimo": "last",
    "usare": "to use",
    "vado": "I go",
    "vale": "it's worth",
    "valle": "valley",
    "vedere": "to see",
    "vedo": "I see",
    "verso": "towards",
    "via": "way / street",
    "vicino": "near / nearby",
    "vietato": "forbidden",
    "visita": "visit",
    "visitare": "to visit",
    "visitarlo": "to visit it",
    "visitatori": "visitors",
    "vista": "view",
    "visto": "seen",
    "vorrei": "I would like"
}

for item in vocab:
    it = item['italian']
    if it in translations:
        item['english'] = translations[it]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, indent=2, ensure_ascii=False)
