import json

mapping = {
    "abbiamo": "we have",
    "accende": "turns on",
    "adoro": "I love",
    "aiuta": "helps",
    "aiuto": "help",
    "all": "at the",
    "alla": "to the",
    "alle": "at the",
    "allora": "then",
    "altro": "other",
    "ambiente": "environment",
    "amministrativo": "administrative",
    "anche": "also",
    "ancora": "again / still",
    "andare": "to go",
    "angolo": "corner",
    "anni": "years",
    "appunti": "notes",
    "armadio": "cabinet / wardrobe",
    "arrivato": "arrived / newcomer",
    "assistente": "assistant",
    "attento": "careful",
    "averla": "to have it",
    "avrò": "I will have",
    "badge": "badge",
    "bella": "beautiful / nice",
    "bene": "well",
    "benvenuto": "welcome",
    "bisogno": "need",
    "breve": "short",
    "buon": "good",
    "buona": "good",
    "buongiorno": "good morning",
    "caffè": "coffee",
    "caldo": "hot",
    "calendario": "calendar",
    "capisco": "I understand",
    "cassettiera": "chest of drawers",
    "centesimi": "cents",
    "certamente": "certainly",
    "chat": "chat",
    "che": "that / what",
    "chiave": "key",
    "chiederò": "I will ask",
    "chiedi": "ask",
    "ciao": "hi / bye",
    "cinquanta": "fifty",
    "collega": "colleague",
    "colleghi": "colleagues",
    "come": "how / like",
    "comoda": "comfortable",
    "compagnia": "company",
    "computer": "computer",
    "comunicare": "to communicate",
    "con": "with",
    "concentrarmi": "concentrate myself",
    "conoscerla": "to know her/you (formal)",
    "conoscerti": "to know you (informal)",
    "conoscervi": "to know you (plural)",
    "corridoio": "hallway",
    "cosa": "thing / what",
    "cose": "things",
    "costa": "costs",
    "cucina": "kitchen",
    "dalle": "from the",
    "darla": "to give it",
    "del": "of the",
    "dell": "of the",
    "della": "of the",
    "delle": "of the",
    "diciotto": "eighteen / six o'clock (PM)",
    "dietro": "behind",
    "dinamico": "dynamic",
    "domande": "questions",
    "dopo": "after",
    "dove": "where",
    "due": "two",
    "ecco": "here is",
    "energia": "energy",
    "entrambi": "both",
    "entrare": "to enter",
    "entusiasta": "enthusiastic",
    "ero": "I was",
    "esatto": "exact / exactly",
    "esperienza": "experience",
    "espresso": "espresso",
    "facciamo": "we do / we make",
    "facevi": "you were doing",
    "farebbe": "it would make / do",
    "farlo": "to do it",
    "favore": "favor / please",
    "finestra": "window",
    "finita": "finished",
    "foglio": "sheet (of paper)",
    "fondo": "bottom / end",
    "fortuna": "luck",
    "gentili": "kind",
    "giorno": "day",
    "giulia": "Giulia",
    "giusto": "right / correct",
    "già": "already",
    "gratuiti": "free",
    "grazie": "thank you",
    "grigio": "gray",
    "hai": "you have",
    "importante": "important",
    "informazione": "information",
    "ingresso": "entrance",
    "iniziare": "to start",
    "insieme": "together",
    "installata": "installed",
    "interessante": "interesting",
    "interna": "internal",
    "lascio": "I leave",
    "lavorare": "to work",
    "lavorato": "worked",
    "lavoriamo": "we work",
    "lavoro": "work / job",
    "lei": "she / you (formal)",
    "loro": "they / their",
    "luminoso": "bright",
    "lunedì": "Monday",
    "lungo": "long",
    "macchiato": "macchiato (spotted)",
    "macchinetta": "(coffee) machine",
    "marco": "Marco",
    "marketing": "marketing",
    "materiale": "material",
    "mattina": "morning",
    "meglio": "better",
    "mensa": "canteen / cafeteria",
    "miei": "my (plural)",
    "mille": "thousand",
    "mio": "my",
    "mix": "mix",
    "moderno": "modern",
    "modo": "way",
    "molto": "very / a lot",
    "momento": "moment",
    "monete": "coins",
    "mouse": "mouse",
    "nel": "in the",
    "nell": "in the",
    "nessuno": "nobody",
    "noi": "we",
    "non": "not",
    "nostre": "our (plural)",
    "nostro": "our",
    "notato": "noticed",
    "nove": "nine",
    "nuovo": "new",
    "occupa": "occupies / takes care of",
    "oggetti": "objects",
    "oggi": "today",
    "ogni": "every",
    "open": "open",
    "ora": "now / hour",
    "orario": "schedule / time",
    "organizzare": "to organize",
    "ottima": "excellent / great",
    "ottimo": "excellent / great",
    "parlare": "to speak",
    "password": "password",
    "pausa": "break",
    "pause": "breaks",
    "penne": "pens",
    "pensiero": "thought",
    "penso": "I think",
    "per": "for",
    "perfetta": "perfect",
    "perfetto": "perfect",
    "personali": "personal",
    "piace": "likes",
    "piacere": "pleasure",
    "piacerà": "will like",
    "piaceva": "liked",
    "piccola": "small",
    "più": "more",
    "poco": "little",
    "possibile": "possible",
    "posso": "I can",
    "pranziamo": "we have lunch",
    "pranzo": "lunch",
    "precedente": "previous",
    "preferisci": "you prefer",
    "prendere": "to take",
    "prenderli": "to take them",
    "prendi": "take",
    "prendiamo": "we take",
    "preparata": "prepared",
    "presento": "I introduce",
    "prima": "before / first",
    "problema": "problem",
    "problemi": "problems",
    "pronto": "ready",
    "proprio": "really / own",
    "pure": "also / even",
    "può": "can",
    "quaderni": "notebooks",
    "quaderno": "notebook",
    "qual": "which / what",
    "qualsiasi": "any",
    "quasi": "almost",
    "quello": "that",
    "questa": "this",
    "questo": "this",
    "qui": "here",
    "reparto": "department",
    "respira": "breathes",
    "responsabile": "manager / responsible",
    "ricominciare": "to start again",
    "ricordati": "remember",
    "rilassarsi": "to relax",
    "risparmiare": "to save",
    "riunione": "meeting",
    "roma": "Rome",
    "sacro": "sacred",
    "sai": "you know",
    "sapere": "to know",
    "scelta": "choice",
    "schermo": "screen",
    "scritta": "written",
    "scrivania": "desk",
    "scrivanie": "desks",
    "sedia": "chair",
    "segno": "sign / I mark",
    "segreta": "secret",
    "segreteria": "secretary's office",
    "sei": "you are / six",
    "sembra": "seems",
    "sembrate": "you (plural) seem",
    "semplice": "simple",
    "sempre": "always",
    "sente": "feels / hears",
    "senza": "without",
    "sera": "evening",
    "seriamente": "seriously",
    "serve": "needs / serves",
    "servirebbe": "would need",
    "settore": "sector",
    "siamo": "we are",
    "sicuramente": "definitely",
    "siete": "you (plural) are",
    "simile": "similar",
    "simpatici": "nice / pleasant",
    "sistemare": "to settle / to fix",
    "smart": "smart",
    "solito": "usual",
    "solo": "only",
    "sono": "I am / they are",
    "sotto": "under",
    "space": "space",
    "spaziosa": "spacious",
    "spegnere": "to turn off",
    "spero": "I hope",
    "spieghi": "you explain",
    "spirito": "spirit",
    "squadra": "team",
    "stampante": "printer",
    "standard": "standard",
    "stare": "to stay",
    "stato": "been / state",
    "sua": "his / her / your (formal)",
    "subito": "immediately",
    "sul": "on the",
    "suo": "his / her / your (formal)",
    "tardi": "late",
    "tastiera": "keyboard",
    "tasto": "button / key",
    "team": "team",
    "torniamo": "we return",
    "tra": "between / among / in",
    "tradizione": "tradition",
    "trova": "finds / is located",
    "troverai": "you will find",
    "trovi": "you find",
    "tua": "your (informal)",
    "tuo": "your (informal)",
    "tutti": "all / everyone",
    "tutto": "everything / all",
    "ufficio": "office",
    "una": "a / one",
    "unita": "united / close-knit",
    "usarla": "to use it",
    "usiamo": "we use",
    "utile": "useful",
    "vado": "I go",
    "vedere": "to see",
    "vedi": "you see",
    "vedo": "I see",
    "velocemente": "quickly",
    "venga": "come (formal imperative)",
    "vengo": "I come",
    "venire": "to come",
    "vero": "true / right",
    "via": "way / away",
    "vicino": "near",
    "vieni": "come (informal imperative)",
    "volentieri": "gladly",
    "voleva": "wanted / was needed",
    "vuoi": "you want",
    "vuole": "wants / you want (formal)",
    "working": "working",
    "zucchero": "sugar"
}

input_file = "src/data/exports/workstudy/first_day_at_work/workstudy_first_day_at_work_vocabulary.json"
output_file = "src/data/exports/workstudy/first_day_at_work/workstudy_first_day_at_work_vocabulary.json"

with open(input_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    italian = item['italian']
    if italian in mapping:
        item['english'] = mapping[italian]
    elif item['english'] == "":
        print(f"Warning: No translation for {italian}")

with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
