import json

file_path = '/home/waseageru/parli-italiano/src/data/exports/culture/museum_tickets/culture_museum_tickets_vocabulary.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    "aiutarla": "to help you",
    "ancora": "still",
    "anni": "years",
    "apparecchio": "device",
    "aprite": "you open",
    "auguro": "I wish",
    "bella": "beautiful",
    "benissimo": "very well",
    "chiudiamo": "we close",
    "codice": "code",
    "comprato": "bought",
    "cosa": "what",
    "degli": "some",
    "delle": "some",
    "deposito": "deposit",
    "desiderate": "you want",
    "dica": "tell me",
    "disponibile": "available",
    "diverse": "various",
    "dove": "where",
    "eccolo": "here it is",
    "fatto": "done",
    "finito": "finished",
    "forse": "perhaps",
    "gente": "people",
    "godersi": "to enjoy",
    "grande": "large",
    "guardaroba": "cloakroom",
    "inserire": "to insert",
    "invece": "instead",
    "lasciare": "to leave",
    "lingue": "languages",
    "mattino": "morning",
    "moderna": "modern",
    "molta": "much",
    "momento": "moment",
    "mostrarmelo": "to show it to me",
    "nostro": "our",
    "notizia": "news",
    "nulla": "nothing",
    "online": "online",
    "ottima": "excellent",
    "pagare": "to pay",
    "pittura": "painting",
    "più": "more",
    "possibile": "possible",
    "preferisco": "I prefer",
    "preferite": "you prefer",
    "prezzo": "price",
    "prima": "before",
    "principale": "main",
    "quando": "when",
    "quelli": "those",
    "quello": "that",
    "questa": "this",
    "questo": "this",
    "quindici": "fifteen",
    "riascoltare": "to listen again",
    "ridotti": "reduced",
    "riduzione": "reduction",
    "riporti": "bring back",
    "sconti": "discounts",
    "semplice": "simple",
    "sera": "evening",
    "sotto": "under",
    "spiegazione": "explanation",
    "subito": "immediately",
    "tempo": "time",
    "tranquillo": "quiet",
    "tratta": "it's about",
    "usa": "uses",
    "vado": "I go",
    "validità": "validity",
    "vede": "sees",
    "ventidue": "twenty-two",
    "ventiquattro": "twenty-four",
    "ventisei": "twenty-six",
    "visitiamo": "we visit",
    "volentieri": "gladly",
    "volte": "times",
    "vostra": "your",
    "vuole": "wants",
    "pure": "also"
}

for item in data:
    if item['english'] == "" and item['italian'] in translations:
        item['english'] = translations[item['italian']]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
