import json

translations = {
    "alle": "at the",
    "altre": "other",
    "altro": "other",
    "anche": "also",
    "aperto": "open",
    "attento": "careful",
    "attenzione": "attention",
    "avvertimento": "warning",
    "bagagli": "luggage",
    "bella": "beautiful",
    "bello": "beautiful",
    "bene": "well",
    "benvenuto": "welcome",
    "biglietto": "ticket",
    "bordo": "board",
    "buon": "good",
    "caffè": "coffee",
    "capisco": "I understand",
    "cari": "expensive",
    "cercherò": "I will look for",
    "città": "city",
    "clima": "weather",
    "comprare": "to buy",
    "consiglio": "advice",
    "costa": "it costs",
    "così": "so",
    "dal": "from the",
    "dettagli": "details",
    "diverta": "have fun",
    "divertimento": "fun",
    "dormirà": "you will sleep",
    "dove": "where",
    "euro": "euro",
    "faccia": "make",
    "fame": "hunger",
    "fantastica": "fantastic",
    "fantastico": "fantastic",
    "farò": "I will do",
    "fermo": "I stop",
    "figuri": "don't mention it",
    "fontane": "fountains",
    "forse": "maybe",
    "gentilissimo": "very kind",
    "goda": "enjoy",
    "immagino": "I imagine",
    "impossibile": "impossible",
    "indicazioni": "directions",
    "italia": "Italy",
    "linea": "line",
    "londra": "London",
    "lungo": "long",
    "magari": "maybe",
    "magnifica": "magnificent",
    "mangerò": "I will eat",
    "mente": "mind",
    "mia": "my",
    "molte": "many",
    "mostra": "exhibition",
    "multa": "fine",
    "multe": "fines",
    "nostra": "our",
    "oggi": "today",
    "onesto": "fair",
    "ora": "now",
    "portone": "large door",
    "presto": "soon",
    "prezzi": "prices",
    "prezzo": "price",
    "prima": "first",
    "qualcosa": "something",
    "quella": "that",
    "qui": "here",
    "riposo": "rest",
    "rosso": "red",
    "salate": "high",
    "sarò": "I will be",
    "sera": "evening",
    "serve": "is needed",
    "sette": "seven",
    "sicuramente": "surely",
    "sole": "sun",
    "spero": "I hope",
    "spesso": "often",
    "sui": "about the",
    "tabaccaio": "tobacconist",
    "tardi": "late",
    "tempo": "time",
    "terrò": "I will keep",
    "timbrare": "to validate",
    "tranquilla": "quiet",
    "tutti": "all",
    "ultima": "last",
    "vengo": "I come",
    "vero": "true",
    "viaggio": "trip",
    "viene": "you come",
    "visita": "visit",
    "visitarlo": "to visit it",
    "vista": "view",
    "voglio": "I want",
    "volta": "time",
    "zona": "area"
}

file_path = 'src/data/exports/travel/asking_directions/travel_asking_directions_vocabulary.json'
with open(file_path, 'r') as f:
    data = json.load(f)

updated_count = 0
for item in data:
    if item['english'] == '' and item['italian'] in translations:
        item['english'] = translations[item['italian']]
        updated_count += 1

with open(file_path, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} translations.")
