import json

translations = {
    "abbiamo": "we have",
    "accontentare": "to satisfy / to please",
    "accordo": "agreement / agreed",
    "aceto": "vinegar",
    "acqua": "water",
    "aggiungere": "to add",
    "aggiungiamo": "we add",
    "aggiungo": "I add",
    "aggiunti": "added",
    "alla": "to the / at the",
    "allora": "then / so",
    "altro": "other / else",
    "amaro": "bitter / amaro (liquor)",
    "ananas": "pineapple",
    "anche": "also / too",
    "antipasto": "appetizer / starter",
    "appetito": "appetite",
    "arriva": "it arrives / coming",
    "arrivo": "I arrive / coming / I'll be right back",
    "aspettare": "to wait",
    "assicuratevi": "make sure (plural)",
    "attendo": "I wait / I am waiting",
    "attesa": "waiting / wait",
    "avena": "oat",
    "avere": "to have",
    "averla": "to have it (fem.)",
    "avete": "you have (plural/formal)",
    "balsamico": "balsamic",
    "bene": "well / good",
    "benissimo": "very well",
    "bere": "to drink",
    "bicchiere": "glass",
    "bicchierino": "small glass",
    "biologici": "organic",
    "brodo": "broth",
    "buon": "good",
    "buona": "good (fem.)",
    "buongiorno": "good morning",
    "burro": "butter",
    "cacao": "cocoa",
    "caffè": "coffee",
    "capisco": "I understand / I see",
    "cappuccino": "cappuccino",
    "carne": "meat",
    "casa": "home / house",
    "ceci": "chickpeas",
    "cercavo": "I was looking for",
    "cerchiamo": "we try / we look for",
    "certamente": "certainly",
    "che": "that / which / what",
    "chef": "chef",
    "chiedere": "to ask",
    "chiedo": "I ask",
    "circa": "about / around",
    "clienti": "customers",
    "con": "with",
    "condimento": "dressing / condiment",
    "contiene": "it contains",
    "controllare": "to check",
    "cotto": "cooked",
    "dedicata": "dedicated",
    "dei": "of the / some",
    "del": "of the / some",
    "delizioso": "delicious",
    "della": "of the / some",
    "dentro": "inside",
    "desidera": "he/she desires / would you like",
    "dica": "speak / tell me",
    "dice": "he/she says",
    "dolce": "sweet / dessert",
    "dolci": "sweets / desserts",
    "dopo": "after / later",
    "duro": "hard",
    "entrambi": "both",
    "esattamente": "exactly",
    "essere": "to be",
    "extravergine": "extra virgin",
    "faccia": "he/she makes / let (me) make",
    "facciamo": "we make / we do",
    "farina": "flour",
    "fatta": "made (fem.)",
    "fatti": "made (plural)",
    "fatto": "made",
    "fine": "end",
    "formaggio": "cheese",
    "fragole": "strawberries",
    "fresca": "fresh (fem.)",
    "fresche": "fresh (plural fem.)",
    "fresco": "fresh",
    "frutta": "fruit",
    "funghi": "mushrooms",
    "gassata": "sparkling / carbonated",
    "gentile": "kind",
    "giardino": "garden",
    "giorno": "day",
    "glielo": "(it) to him/her/you",
    "grano": "grain / wheat",
    "grazie": "thank you / thanks",
    "griglia": "grill",
    "insalata": "salad",
    "insieme": "together",
    "intera": "entire / whole",
    "latte": "milk",
    "leggero": "light",
    "lei": "she / you (formal)",
    "lievito": "yeast",
    "limoncello": "limoncello",
    "limone": "lemon",
    "limoni": "lemons",
    "liquore": "liquor",
    "lista": "list",
    "macedonia": "fruit salad",
    "maionese": "mayonnaise",
    "mangio": "I eat",
    "melanzane": "eggplants / aubergines",
    "melone": "melon",
    "menu": "menu",
    "mille": "thousand",
    "minuti": "minutes",
    "mista": "mixed",
    "modifica": "change / modification",
    "molte": "many (fem.)",
    "molti": "many",
    "molto": "very / much",
    "mozzarella": "mozzarella",
    "naturale": "still / natural",
    "nell": "in the",
    "nessun": "no / none",
    "niente": "nothing",
    "noi": "we",
    "non": "not",
    "nostra": "our (fem.)",
    "nostro": "our",
    "oggi": "today",
    "olio": "oil",
    "oliva": "olive",
    "opzioni": "options / choices",
    "ordinare": "to order",
    "ottima": "excellent (fem.)",
    "ottimo": "excellent",
    "pagina": "page",
    "pane": "bread",
    "panna": "cream",
    "parmigiano": "parmesan",
    "pasta": "pasta",
    "pazienza": "patience",
    "peperoni": "peppers",
    "per": "for",
    "perché": "because / why",
    "perfetto": "perfect",
    "però": "but / however",
    "pesce": "fish",
    "piatti": "dishes",
    "piatto": "dish",
    "piacere": "pleasure",
    "piacevole": "pleasant",
    "più": "more",
    "poco": "little / bit / while",
    "poi": "then",
    "pollo": "chicken",
    "pomodoro": "tomato",
    "portarle": "to bring you (formal)",
    "posso": "I can",
    "possono": "they can",
    "possiamo": "we can",
    "possibile": "possible",
    "porto": "I bring",
    "potete": "you can (plural)",
    "preferisce": "you prefer (formal) / he/she prefers",
    "preferisco": "I prefer",
    "prenderla": "to take it (fem.)",
    "prendo": "I'll have / I take",
    "pronti": "ready (plural)",
    "problema": "problem",
    "problemi": "problems",
    "proprio": "exactly / really",
    "pure": "also / as well / go ahead",
    "puro": "pure",
    "purtroppo": "unfortunately",
    "può": "can / he/she/it can / you can (formal)",
    "qualche": "some / any",
    "qualcos": "something",
    "qualcosa": "something",
    "qualcos'altro": "something else",
    "quali": "which (plural)",
    "quella": "that one (fem.)",
    "quello": "that one",
    "questa": "this one (fem.)",
    "questo": "this one",
    "richiede": "it requires",
    "ringrazio": "I thank",
    "riso": "rice",
    "risotto": "risotto",
    "saporita": "flavorful / tasty",
    "scelta": "choice",
    "scusa": "excuse / apology",
    "se": "if",
    "sezione": "section",
    "sembra": "it seems / it sounds",
    "senza": "without",
    "sicurezza": "safety / certainty",
    "sia": "be / it is",
    "siete": "you are (plural)",
    "subito": "immediately / right away",
    "stagione": "season",
    "sorbetto": "sorbet",
    "soia": "soy",
    "solo": "only / alone",
    "sono": "I am / they are",
    "sopra": "on top / above",
    "tardi": "late",
    "tofu": "tofu",
    "togliere": "to remove",
    "toscano": "Tuscan",
    "tra": "between / in (time)",
    "tranquillamente": "quietly / without problems",
    "tre": "three",
    "troppa": "too much (fem.)",
    "trovare": "to find",
    "trova": "finds / you find",
    "tutti": "all / everyone",
    "tutto": "all / everything",
    "un": "a / an",
    "una": "a / an (fem.)",
    "uova": "eggs",
    "usano": "they use",
    "usare": "to use",
    "userà": "he/she will use",
    "usiamo": "we use",
    "vedere": "to see",
    "vegana": "vegan (fem.)",
    "vegane": "vegan (plural fem.)",
    "vegani": "vegan (plural masc.)",
    "vegano": "vegan",
    "vegetale": "vegetable (adj.)",
    "vegetariani": "vegetarian",
    "venti": "twenty",
    "verdure": "vegetables",
    "volete": "you want (plural)",
    "volevo": "I wanted",
    "vorrebbe": "he/she would like",
    "vorrei": "I would like",
    "vuole": "he/she wants / do you want",
    "zuccheri": "sugars",
    "zucchero": "sugar",
    "zucchine": "zucchini / courgettes",
    "zuppa": "soup"
}

with open('src/data/exports/dining/vegetarian_meal/dining_vegetarian_meal_vocabulary.json', 'r') as f:
    data = json.load(f)

missing = []
for item in data:
    it = item['italian']
    if it in translations:
        item['english'] = translations[it]
    else:
        missing.append(it)

if missing:
    print(f"Still missing translations for: {missing}")
else:
    print("All translations filled!")

with open('src/data/exports/dining/vegetarian_meal/dining_vegetarian_meal_vocabulary.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
