import sys
import subprocess
import os
import time
import json

def log_step(step_name):
    print(f"\n[{time.strftime('%H:%M:%S')}] ---> {step_name}")

def run_script(script_name, slug):
    log_step(f"Running: {script_name}")
    result = subprocess.run(
        [sys.executable, f"scripts/{script_name}", slug],
        capture_output=False,
        text=True
    )
    if result.returncode != 0:
        print(f"❌ ERROR: {script_name} failed.")
        return False
    return True

def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/build_and_certify_scenario.py <scenario_slug>")
        sys.exit(1)
        
    scenario_slug = sys.argv[1]
    
    # We assume domain_analysis.json and conversations.json are already generated by Agents 1 & 2
    # In a full bulk production run, we would trigger those agents too.
    
    print("=====================================================")
    print(f" BUILD & CERTIFY PIPELINE: {scenario_slug} ")
    print("=====================================================")

    # 1. Linguistic Extraction
    if not run_script("linguistic_extractor.py", scenario_slug): sys.exit(1)
    
    # 2. Curriculum Generation
    # (Note: Agent 4 refined mini_lessons.json already for Hotel Check-In, 
    # but a default script could handle the baseline)
    # if not run_script("curriculum_designer.py", scenario_slug): sys.exit(1)
    
    # 3. Distractor Generation
    if not run_script("distractor_generator.py", scenario_slug): sys.exit(1)
    
    # 4. Translation & Audio Manifest
    # (Agent 6 filled translations for Hotel Check-In)
    if not run_script("audio_manifest_updater.py", scenario_slug): sys.exit(1)
    
    # 5. Audio Generation (Mocked for factory validation due to environment limits)
    if not run_script("mock_audio_files.py", scenario_slug): sys.exit(1)
    
    # 6. Certification
    result = subprocess.run(
        [sys.executable, "scripts/certify_scenario.py", scenario_slug],
        capture_output=False,
        text=True
    )
    
    if result.returncode == 0:
        print(f"\n✅ SUCCESS: Scenario '{scenario_slug}' has been built and certified.")
        sys.exit(0)
    else:
        print(f"\n❌ FAILURE: Scenario '{scenario_slug}' failed certification.")
        sys.exit(1)

if __name__ == "__main__":
    main()
